// ============================================================
// source/4-c/bank_10.c  —  GENERATED by `python -m na1dream.cli.decompile_all`
// 1 bytecode subroutines from bank 10 of Nobunaga's Ambition (USA).nes
// Deterministic (fixed ROM -> identical C). DO NOT hand-edit — regenerate via the tool.
// Pipeline: vm-disasm.py (execution-validated lengths) -> vm_decompile.py (opcode-keyed front-end) -> dream.py (DREAM structurer; V2 fallback).
// ============================================================

// $8003 play_audio_by_id
// (body @ $8008)

word play_audio_by_id(void) {
    phi_ret_808e = (audio_wait_gate == 1);    // $800D
    if (phi_ret_808e) {    // $8008
        if (((unsigned)sound_request_id > (unsigned)64)) {    // $8010
            return ((unsigned)sound_request_id > (unsigned)64);    // $8019
        } else {
            if (((unsigned)sound_request_id < (unsigned)27)) {    // $801A
                local11 = (sound_request_id * 3);    // $8028
                syscall_audio_load_voice(1, 10, *(word*)(((local11 << 1) + 0x8617)));    // $8034
                syscall_audio_load_voice(2, 10, *(word*)((((local11 + 1) << 1) + 0x8617)));    // $8044
                syscall_audio_load_voice(3, 10, *(word*)((((local11 + 2) << 1) + 0x8617)));    // $8054
                syscall_audio_control(1, 1);    // $805B
                syscall_audio_control(2, 1);    // $8062
                phi_ret_808e = syscall_audio_control(3, 1);    // $806D
            } else {
                local9 = *(word*)(((sound_request_id << 1) + 0x8617));    // $8079
                local10 = (*(byte*)(local9) & 4);    // $807E
                syscall_audio_load_voice(local10, 10, local9);    // $8083
                phi_ret_808e = syscall_audio_control(local10, 1);    // $808A
            }
            return phi_ret_808e;    // $808E
        }
    } else {
        return phi_ret_808e;    // $808E
    }
}

