// ============================================================
// source/4-c/bank_14.c  —  GENERATED by `python -m na1dream.cli.decompile_all`
// 3 bytecode subroutines from bank 14 of Nobunaga's Ambition (USA).nes
// Deterministic (fixed ROM -> identical C). DO NOT hand-edit — regenerate via the tool.
// Pipeline: vm-disasm.py (execution-validated lengths) -> vm_decompile.py (opcode-keyed front-end) -> dream.py (DREAM structurer; V2 fallback).
// ============================================================

// $8003 cutscene_delay
// (body @ $8008)

word cutscene_delay(word arg1) {
    while (arg1) {    // $8018
        local11 = 50;    // $800D
        do {    // $800E
            local11 = (local11 - 1);    // $8010
        } while (local11);
        arg1 = (arg1 - 1);    // $8017
    }
    return arg1;    // $801C
}

// $801D draw_sprite_grid
// (body @ $8022)

word draw_sprite_grid(word arg1, word arg2, word arg3, word arg4) {
    syscall16_sram_wrap(arg1, arg4, (fp - 152), 6);    // $8029
    local7 = *(byte*)(fp - 152);    // $8030
    local6 = *(byte*)(fp - 151);    // $8034
    *(word*)(fp - 144) = (fp - 78);    // $803A
    syscall16_sram_wrap(arg1, *(word*)(fp - 150), (fp - 78), 64);    // $8042
    *(word*)(fp - 146) = (fp - 142);    // $804B
    syscall16_sram_wrap(arg1, *(word*)(fp - 148), (fp - 142), 64);    // $8053
    local5 = 16;    // $8059
    local8 = arg3;    // $805B
    local11 = 0;    // $805D
    while ((local11 < local6)) {    // $80A0
        local9 = arg2;    // $8062
        local10 = 0;    // $8064
        while ((local10 < local7)) {    // $8091
            *(word*)(fp - 146) = (*(word*)(fp - 146) + 1);    // $806C
            *(word*)(fp - 144) = (*(word*)(fp - 144) + 1);    // $8076
            local5 = (local5 + 1);    // $8080
            syscall_set_sprite(((local5 + 1) - 1), local9, local8, *(byte*)(((*(word*)(fp - 144) + 1) - 1)), *(byte*)(((*(word*)(fp - 146) + 1) - 1)));    // $8084
            local10 = (local10 + 1);    // $808A
            local9 = (local9 + 8);    // $8090
        }
        local11 = (local11 + 1);    // $8099
        local8 = (local8 + 8);    // $809F
    }
    return syscall_wait_for_nmi();    // $80AC
}

// $80AD run_cutscene
// (body @ $80B2)

word run_cutscene(void) {
    *(word*)(fp - 41) = ((cutscene_id * 5) + cutscene_table);    // $80BB
    local7 = *(byte*)(*(word*)(fp - 41));    // $80C0
    *(word*)(fp - 33) = (fp - 31);    // $80C6
    syscall16_sram_wrap(local7, *(word*)((*(word*)(fp - 41) + 1)), (fp - 31), 21);    // $80CF
    *(word*)(fp - 35) = *(word*)(fp - 33);    // $80D5
    phi_val_80f8 = 16;    // $80D9
    while ((local11 < 32)) {    // $80F8
        *(word*)(fp - 35) = (*(word*)(fp - 35) + 1);    // $80E4
        syscall16_sram_wrap(local7, ((*(word*)(fp - 35) + 1) - 1), (fp - 36), 1);    // $80E9
        palette_write_wrap(local11, *(byte*)(fp - 36));    // $80F2
        phi_val_80f8 = (local11 + 1);    // $80F7
        local11 = phi_val_80f8;    // $80F8
    }
    ppu_upload_block_wrap(local7, *(word*)((*(word*)(fp - 33) + 17)), 0x0100, *(byte*)((*(word*)(fp - 33) + 16)));    // $8110
L_8118:
    *(word*)(fp - 35) = *(word*)((*(word*)(fp - 41) + 3));    // $8118
L_811A:
    *(word*)(fp - 35) = (*(word*)(fp - 35) + 1);    // $811D
    switch (*(byte*)(((*(word*)(fp - 35) + 1) - 1))) {    // $8121
    case 65469: goto L_81EC;    // $8121
    case 65470: goto L_8195;    // $8121
    case 65471: goto L_81DC;    // $8121
    case 65472: goto L_81F2;    // $8121
    case 65473: goto L_8225;    // $8121
    case 65474: goto L_8225;    // $8121
    case 65475: goto L_8225;    // $8121
    case 65476: goto L_8225;    // $8121
    case 65477: goto L_8225;    // $8121
    case 65478: goto L_8154;    // $8121
    case 65479: goto L_8225;    // $8121
    case 65480: goto L_8225;    // $8121
    case 65481: goto L_8225;    // $8121
    case 65482: goto L_8225;    // $8121
    case 65483: goto L_8225;    // $8121
    case 65484: goto L_81CB;    // $8121
    case 65485: goto L_8216;    // $8121
    case 65486: goto L_8225;    // $8121
    case 65487: goto L_8225;    // $8121
    case 65488: goto L_8185;    // $8121
    case 65489: goto L_81BC;    // $8121
    case 65490: goto L_8167;    // $8121
    default: goto L_8225;    // $8121
    }    // $8121
L_8154:
    *(word*)(fp - 35) = (*(word*)(fp - 35) + 1);    // $8157
    local10 = *(byte*)(((*(word*)(fp - 35) + 1) - 1));    // $815B
    *(word*)(fp - 35) = (*(word*)(fp - 35) + 1);    // $815F
    local9 = *(byte*)(((*(word*)(fp - 35) + 1) - 1));    // $8163
    goto L_811A;    // $8164
L_8167:
    local10 = (local10 + *(byte*)(*(word*)(fp - 35)));    // $816D
    *(word*)(fp - 35) = (*(word*)(fp - 35) + 1);    // $8171
    if (!((*(byte*)(((*(word*)(fp - 35) + 1) - 1)) > 127))) goto L_811A;    // $8178
    local10 = (local10 - 0x0100);    // $8181
    goto L_811A;    // $8182
L_8185:
    *(word*)(fp - 35) = (*(word*)(fp - 35) + 1);    // $8188
    local10 = *(byte*)(((*(word*)(fp - 35) + 1) - 1));    // $818C
    *(word*)(fp - 35) = (*(word*)(fp - 35) + 1);    // $8190
    local9 = *(byte*)(((*(word*)(fp - 35) + 1) - 1));    // $8194
L_8195:
    syscall16_sram_wrap(local7, *(word*)((*(word*)(fp - 33) + 19)), (fp - 53), 10);    // $81A1
    *(word*)(fp - 35) = (*(word*)(fp - 35) + 1);    // $81AC
    draw_sprite_grid(local7, local10, local9, *(word*)(((*(byte*)(((*(word*)(fp - 35) + 1) - 1)) << 1) + (fp - 53))));    // $81B8
L_81BC:
    *(word*)(fp - 35) = (*(word*)(fp - 35) + 1);    // $81BF
    cutscene_delay(*(byte*)(((*(word*)(fp - 35) + 1) - 1)));    // $81C4
    goto L_811A;    // $81C8
L_81CB:
    *(word*)(fp - 35) = (*(word*)(fp - 35) + 1);    // $81CE
    *(byte*)(fp - 39) = *(byte*)(((*(word*)(fp - 35) + 1) - 1));    // $81D2
    *(word*)(fp - 38) = *(word*)(fp - 35);    // $81D7
    goto L_811A;    // $81D9
L_81DC:
    *(byte*)(fp - 39) = (*(byte*)(fp - 39) - 1);    // $81E0
    if (!(((*(byte*)(fp - 39) - 1) + 1))) goto L_811A;    // $81E4
    goto L_8118;    // $81E9
L_81EC:
    delay_loop(50);    // $81EE
L_81F2:
    local8 = 16;    // $81F4
L_81F5:
    syscall_set_sprite(local8, 248, 248, 0, 2);    // $81FF
    local8 = (local8 + 1);    // $8205
    if ((local8 < 64)) goto L_81F5;    // $820A
    syscall_wait_for_nmi();    // $820F
    goto L_811A;    // $8213
L_8216:
    *(word*)(fp - 35) = (*(word*)(fp - 35) + 1);    // $8219
    call_bank10_entry(*(byte*)(((*(word*)(fp - 35) + 1) - 1)));    // $821E
    goto L_811A;    // $8222
L_8225:
    return call_bank10_entry(*(byte*)(((*(word*)(fp - 35) + 1) - 1)));    // $8225
}

