"""Decompile-all driver — the "see the whole picture" payoff (EPIC step 3b/4).

Persists `decompiled/bank_NN.c`: every bytecode subroutine in the 4 CODE banks
(0, 1, 2, 15 — banks 03-14 are data, 0 bytecode subs), decompiled to readable C.
Deterministic: fixed ROM -> identical C forever, so this is run ONCE and the .c
files are committed. Reading the engine becomes opening a file, never re-running
a tool. Regenerate only when vm-disasm.py or vm_decompile.py themselves improve.

Pipeline (all execution-validated, see ROADMAP / project_nobunaga_vm_disasm_recovered):
  vm-disasm.py  ROM -> v2 VM-asm listing (correct lengths, recursive-descent subs)
  vm_decompile.py  listing -> C  (spec-agnostic: dispatch keyed on the opcode byte)

Usage:
  py -3 tools/decompile-all.py                 # all 4 code banks -> decompiled/
  py -3 tools/decompile-all.py --banks 1       # one bank
  py -3 tools/decompile-all.py --out-dir foo   # alternate output dir
"""

import argparse
import io
import importlib.util
import re
import sys
import tempfile
from contextlib import redirect_stdout
from pathlib import Path

HERE = Path(__file__).parent
ROOT = HERE.parent
sys.path.insert(0, str(HERE))

LABELS_TOML = ROOT / "mesen-labels.toml"


def _switchable_label_banks():
    """addr -> bank for labels in the switchable $8000-$BFFF window, keyed by their
    [prg.bankN] toml section.

    Banks 0/1/2 share the $8000-$BFFF CPU window, so a [prg.bank1] label must NOT
    leak onto bank 2's code at the same address. `nobunaga_vm.load_labels()` flattens
    the toml to {addr: name} and discards the section, so without this map the
    decompiler is bank-blind for the window (bug surfaced 2026-05-31 by the regen
    cross-bank guard: bank-1's $83A2 label bled onto bank-2 combat code).

    RAM/ZP (<$8000) and fixed bank-15 ($C000+) labels are bank-independent and are
    intentionally excluded here so they stay global. ~73 $C000+ labels mis-filed
    under [prg.bank0] are >= $C000, so they fall outside the window and remain global.
    """
    text = LABELS_TOML.read_text(encoding="utf-8")
    sec_re = re.compile(r'^\s*\[prg\.bank(\d+)\]')
    lbl_re = re.compile(r'"0x([0-9A-Fa-f]+)"\s*=\s*\{')
    out, cur = {}, None
    for line in text.splitlines():
        m = sec_re.match(line)
        if m:
            cur = int(m.group(1)); continue
        if line.lstrip().startswith('['):      # left the prg.bankN sections
            cur = None; continue
        m = lbl_re.search(line)
        if m and cur is not None:
            addr = int(m.group(1), 16)
            if 0x8000 <= addr < 0xC000:
                out[addr] = cur
    return out


SWITCHABLE_BANK = _switchable_label_banks()


def _load(name, filename):
    spec = importlib.util.spec_from_file_location(name, HERE / filename)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


vmdisasm = _load("vmdisasm", "vm-disasm.py")
import vm_decompile  # underscore name → importable directly
from nobunaga_vm import NobunagaVM

CODE_BANKS = [0, 1, 2, 15]   # the only banks containing bytecode (rest are data)


def decompile_bank(bank, out_dir, tmp_dir):
    """Decompile every sub in `bank` → out_dir/bank_NN.c. Returns (n_subs, n_lines)."""
    vm = NobunagaVM()
    vm.switch_bank(bank)
    mem = vm.mem
    base, size = vmdisasm.bank_range(bank)
    stubs = vmdisasm.find_stubs(mem, base, size)
    # Bank-aware label set: drop switchable-window ($8000-$BFFF) labels that belong
    # to a DIFFERENT bank's section so they don't leak onto this bank's code at the
    # same CPU address. <$8000 (RAM/ZP) and >=$C000 (fixed bank 15) stay global.
    # Unknown switchable addrs (no recorded section) default to kept.
    labels = {a: n for a, (n, _c) in vm.labels.items()
              if not (0x8000 <= a < 0xC000) or SWITCHABLE_BANK.get(a, bank) == bank}

    # 1. Render the execution-validated v2 listing for this bank (intermediate;
    #    not committed — vm-disasm.py regenerates it deterministically on demand).
    listing, misaligned = vmdisasm.render(bank, stubs, mem, labels, len(vm.labels))
    asm_path = tmp_dir / f"bank_{bank:02d}_vm.v2.asm"
    asm_path.write_text(listing, encoding="utf-8")

    # 2. Decompile each sub (vm_decompile prints to stdout — capture per sub).
    parts = [
        f"// ============================================================",
        f"// decompiled/bank_{bank:02d}.c  —  GENERATED by tools/decompile-all.py",
        f"// {len(stubs)} bytecode subroutines from bank {bank} of "
        f"Nobunaga's Ambition (USA).nes",
        f"// Deterministic (fixed ROM -> identical C). DO NOT hand-edit — "
        f"regenerate via the tool.",
        f"// Pipeline: vm-disasm.py (v2, execution-validated lengths) -> "
        f"vm_decompile.py (opcode-keyed).",
        f"// ============================================================",
        "",
    ]
    if misaligned:
        parts.append(f"// WARNING: {misaligned} subs did not tile cleanly "
                     f"(see vm-disasm.py --check {bank}).\n")

    for stub in stubs:
        buf = io.StringIO()
        with redirect_stdout(buf):
            vm_decompile.decompile(str(asm_path), stub, labels)
        # Drop the per-sub "// Decompiled from <path>" line: it names the ephemeral
        # temp listing (non-deterministic path) and is redundant with the bank
        # header. Everything else is a pure function of the ROM.
        sub_c = "\n".join(l for l in buf.getvalue().splitlines()
                          if not l.startswith("// Decompiled from"))
        parts.append(sub_c.rstrip("\n"))
        parts.append("")  # blank line between subs

    text = "\n".join(parts) + "\n"
    out_path = out_dir / f"bank_{bank:02d}.c"
    out_path.write_text(text, encoding="utf-8")
    return len(stubs), text.count("\n")


def main():
    ap = argparse.ArgumentParser(description="Decompile-all driver")
    ap.add_argument("--banks", default=",".join(map(str, CODE_BANKS)),
                    help="comma-separated bank list (default: the 4 code banks)")
    ap.add_argument("--out-dir", default=str(ROOT / "decompiled"),
                    help="output directory for bank_NN.c (default: ./decompiled)")
    args = ap.parse_args()

    banks = [int(b, 0) for b in args.banks.split(",") if b.strip()]
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    total_subs = total_lines = 0
    # Intermediate v2 listings are regenerable (vm-disasm.py is deterministic), so
    # they live in an ephemeral temp dir — only the .c files are persisted.
    with tempfile.TemporaryDirectory() as td:
        tmp_dir = Path(td)
        for bank in banks:
            n_subs, n_lines = decompile_bank(bank, out_dir, tmp_dir)
            total_subs += n_subs
            total_lines += n_lines
            print(f"  bank {bank:>2}: {n_subs:>3} subs -> "
                  f"{out_dir.name}/bank_{bank:02d}.c ({n_lines} lines)")
    print(f"\nDecompiled {total_subs} subroutines across {len(banks)} banks "
          f"({total_lines} lines of C) -> {out_dir}/")


if __name__ == "__main__":
    main()
