// ============================================================
// source/3-c-basic/bank_15.raw.c  —  GENERATED by `python -m na1dream.cli.decompile_all`  (BASIC: bytecode -> direct goto-infused C, the intermediary form the structure engine folds; the CFG-equivalence reference for bank_15.c)
// 135 bytecode subroutines from bank 15 of Nobunaga's Ambition (USA).nes
// Deterministic (fixed ROM -> identical C). DO NOT hand-edit — regenerate via the tool.
// Pipeline: vm-disasm.py (execution-validated lengths) -> vm_decompile.py (opcode-keyed) — NO structuring: the direct goto/label form.
// ============================================================

// $CA03 call_bank10_entry
// (body @ $CA08)

word call_bank10_entry(word arg1) {
    sound_request_id = arg1;    // $CA09
    return call_bank_wrap(10);    // $CA11
}

// $CA12 deduct_byte_at
// (body @ $CA17)

word deduct_byte_at(word arg1, word arg2) {
    if (!((*(byte*)(arg1) < *(byte*)&arg2))) goto L_CA27;    // $CA20
    goto L_CA2F;    // $CA24
L_CA27:
L_CA2F:
    *(byte*)(arg1) = (*(byte*)(arg1) - *(byte*)&arg2);    // $CA2F
    return (*(byte*)(arg1) - *(byte*)&arg2);    // $CA30
}

// $CA31 word_sub_saturating
// (body @ $CA36)

word word_sub_saturating(word arg1, word arg2) {
    local11 = (*(word*)(arg1) - arg2);    // $CA3A
    if (!(((*(word*)(arg1) - arg2) < 0))) goto L_CA42;    // $CA3D
    local11 = 0;    // $CA41
L_CA42:
    *(word*)(arg1) = local11;    // $CA44
    return local11;    // $CA45
}

// $CA46 rng_next_wrapper
// (body @ $CA4B)

word rng_next_wrapper(void) {
    return syscall_rng_next();    // $CA51
}

// $CA52 rng_mod
// (body @ $CA57)

word rng_mod(word arg1) {
    if ((arg1 >= 1)) goto L_CA5F;    // $CA5A
    return 0;    // $CA5E
L_CA5F:
    return (rng_next_wrapper() % arg1);    // $CA64
}

// $CA65 is_digit
// (body @ $CA6A)

word is_digit(word arg1) {
    return (((unsigned)48 <= (unsigned)arg1) && ((unsigned)arg1 <= (unsigned)57));    // $CA7D
}

// $CA7E strlen
// (body @ $CA83)

word strlen(word arg1) {
    local11 = 0;    // $CA84
    goto L_CA90;    // $CA85
L_CA88:
    arg1 = (arg1 + 1);    // $CA8A
    local11 = (local11 + 1);    // $CA8E
L_CA90:
    if (*(byte*)(arg1)) goto L_CA88;    // $CA92
    return local11;    // $CA96
}

// $CA97 fill_bytes_ca97
// (body @ $CA9C)

word fill_bytes_ca97(word arg1, word arg2, word arg3) {
    goto L_CAAB;    // $CA9C
L_CA9F:
    arg1 = (arg1 + 1);    // $CAA1
    *(byte*)(((arg1 + 1) - 1)) = *(byte*)&arg3;    // $CAA7
    arg2 = (arg2 - 1);    // $CAAA
L_CAAB:
    if (arg2) goto L_CA9F;    // $CAAC
    return arg2;    // $CAAF
}

// $CAB0 strcmp
// (body @ $CAB5)

word strcmp(word arg1, word arg2) {
    goto L_CAC7;    // $CAB5
L_CAB8:
    if (*(byte*)(arg1)) goto L_CABF;    // $CABA
    return 0;    // $CABE
L_CABF:
    arg1 = (arg1 + 1);    // $CAC1
    arg2 = (arg2 + 1);    // $CAC5
L_CAC7:
    if ((*(byte*)(arg1) == *(byte*)(arg2))) goto L_CAB8;    // $CACE
    return (*(byte*)(arg1) - *(byte*)(arg2));    // $CAD8
}

// $CAD9 strcpy
// (body @ $CADE)

word strcpy(word arg1, word arg2) {
    local11 = arg1;    // $CADF
L_CAE0:
    arg1 = (arg1 + 1);    // $CAE2
    arg2 = (arg2 + 1);    // $CAE7
    *(byte*)(((arg1 + 1) - 1)) = *(byte*)(((arg2 + 1) - 1));    // $CAEA
    if (*(byte*)(((arg2 + 1) - 1))) goto L_CAE0;    // $CAEB
    return local11;    // $CAEF
}

// $CAF0 memchr
// (body @ $CAF5)

word memchr(word arg1, word arg2, word arg3) {
    goto L_CB0B;    // $CAF5
L_CAF8:
    if (!((*(byte*)(arg1) == *(byte*)&arg2))) goto L_CB05;    // $CB00
    return arg1;    // $CB04
L_CB05:
    arg1 = (arg1 + 1);    // $CB07
    arg3 = (arg3 - 1);    // $CB0A
L_CB0B:
    if (arg3) goto L_CAF8;    // $CB0C
    return 0;    // $CB10
}

// $CB11 is_lower
// (body @ $CB16)

word is_lower(word arg1) {
    return ((97 <= *(byte*)&arg1) && (*(byte*)&arg1 <= 122));    // $CB2F
}

// $CB30 to_upper
// (body @ $CB35)

word to_upper(word arg1) {
    if (!(is_lower(*(byte*)&arg1))) goto L_CB48;    // $CB3D
    phi_ret_cb4b = (*(byte*)&arg1 + -32);    // $CB45
    goto L_CB4B;    // $CB45
L_CB48:
    phi_ret_cb4b = *(byte*)&arg1;    // $CB48
L_CB4B:
    return phi_ret_cb4b;    // $CB4B
}

// $CB4C abs16
// (body @ $CB51)

word abs16(word arg1) {
    return ((arg1 < 0) ? (-arg1) : arg1);    // $CB5D
}

// $CB5E min_word
// (body @ $CB63)

word min_word(word arg1, word arg2) {
    return ((arg1 < arg2) ? arg1 : arg2);    // $CB6E
}

// $CB6F max_word
// (body @ $CB74)

word max_word(word arg1, word arg2) {
    return ((arg1 > arg2) ? arg1 : arg2);    // $CB7F
}

// $CB80 swap_byte
// (body @ $CB85)

word swap_byte(word arg1, word arg2) {
    tmp_byte = *(byte*)(arg1);    // $CB87
    *(byte*)(arg1) = *(byte*)(arg2);    // $CB8D
    *(byte*)(arg2) = tmp_byte;    // $CB92
    return tmp_byte;    // $CB93
}

// $CB94 swap_word
// (body @ $CB99)

word swap_word(word arg1, word arg2) {
    local11 = *(word*)(arg1);    // $CB9B
    *(word*)(arg1) = *(word*)(arg2);    // $CB9F
    *(word*)(arg2) = local11;    // $CBA2
    return local11;    // $CBA3
}

// $CBA4 chr_bank0_set_wrap
// (body @ $CBA9)

word chr_bank0_set_wrap(word arg1) {
    return syscall_set_chr_bank0_reg(arg1);    // $CBB0
}

// $CBB1 call_bank_wrap
// (body @ $CBB6)

word call_bank_wrap(word arg1) {
    return syscall_call_bank(arg1);    // $CBBC
}

// $CBBD syscall16_sram_wrap
// (body @ $CBC2)

word syscall16_sram_wrap(word arg1, word arg2, word arg3, word arg4) {
    return syscall_memcpy_banked(arg1, arg2, arg3, arg4);    // $CBCC
}

// $CC35 palette_swap
// (body @ $CC3A)

word palette_swap(word arg1) {
    return syscall_palette_swap(arg1);    // $CC41
}

// $CC42 ppu_fill_rect_wrap
// (body @ $CC47)

word ppu_fill_rect_wrap(word arg1, word arg2, word arg3, word arg4, word arg5) {
    return syscall_ppu_fill_rect(0, arg1, arg2, arg3, arg4, arg5);    // $CC53
}

// $CC54 ppu_copy_rect_wrap
// (body @ $CC59)

word ppu_copy_rect_wrap(word arg1, word arg2, word arg3, word arg4, word arg5, word arg6) {
    return syscall_ppu_copy_rect(0, arg1, arg2, arg3, arg4, arg5, arg6);    // $CC68
}

// $CC69 clear_rect_right_panel
// (body @ $CC6E)

word clear_rect_right_panel(void) {
    return ppu_fill_rect_wrap(22, 7, 29, 18, 1);    // $CC7A
}

// $CC7B set_cursor
// (body @ $CC80)

word set_cursor(word arg1, word arg2) {
    ui_window_col = arg1;    // $CC81
    ui_cursor_row = arg2;    // $CC85
    return arg2;    // $CC88
}

// $CC89 open_message_window
// (body @ $CC8E)

word open_message_window(void) {
    ppu_fill_rect_wrap(2, (ui_msg_col_shift_flag ? 20 : 22), 19, 25, 1);    // $CCA2
    return set_cursor(2, (ui_msg_col_shift_flag ? 20 : 22));    // $CCB9
}

// $CCBA ui_get_7bf9
// (body @ $CCBF)

word ui_get_7bf9(void) {
    ppu_fill_rect_wrap(20, 20, 29, 25, 1);    // $CCC8
    ui_state_flag_7bf9 = 0;    // $CCCD
    return 0;    // $CCD0
}

// $CCD1 clear_rect_top_strip
// (body @ $CCD6)

word clear_rect_top_strip(void) {
    return ppu_fill_rect_wrap(2, 3, 29, 3, 1);    // $CCE0
}

// $CCE1 reset_prompt_selection
// (body @ $CCE6)

word reset_prompt_selection(void) {
    ppu_fill_rect_wrap(2, 26, 29, 26, 1);    // $CCEE
    ui_input_sel_latch_7fdf = 255;    // $CCF5
    return 255;    // $CCF8
}

// $CCF9 get_6f5d_or_ff
// (body @ $CCFE)

word get_6f5d_or_ff(void) {
    ppu_fill_rect_wrap(0, 4, 31, 19, 1);    // $CD05
    phi_ret_cd1f = (selected_record_idx_9e3c != 255);    // $CD10
    if (!(phi_ret_cd1f)) goto L_CD1F;    // $CD10
    latched_selected_record_idx = selected_record_idx_9e3c;    // $CD16
    selected_record_idx_9e3c = 255;    // $CD1C
    phi_ret_cd1f = 255;    // $CD1C
L_CD1F:
    return phi_ret_cd1f;    // $CD1F
}

// $CD20 repaint_screen
// (body @ $CD25)

word repaint_screen(void) {
    palette_swap(1);    // $CD26
    fill_nametable_wrap();    // $CD2A
    fill_attr_wrap();    // $CD2D
    if (!(ui_pending_flag_7fc9)) goto L_CD4F;    // $CD33
    palette_write_wrap(7, 33);    // $CD39
    palette_write_wrap(11, 48);    // $CD40
    palette_write_wrap(15, 48);    // $CD47
    ui_pending_flag_7fc9 = 0;    // $CD4C
L_CD4F:
    if (!(ui_pending_flag_7fc7)) goto L_CD7E;    // $CD52
    local11 = 0;    // $CD56
L_CD57:
    palette_write_wrap(local11, *(word*)(((local11 << 1) + strategic_map_bg_palette)));    // $CD60
    local11 = (local11 + 1);    // $CD66
    if (((unsigned)local11 < (unsigned)4)) goto L_CD57;    // $CD6A
    ppu_upload_block_wrap(4, strategic_map_chr_tiles, 0x15B0, 36);    // $CD76
    ui_pending_flag_7fc7 = 0;    // $CD7B
L_CD7E:
    palette_swap(0);    // $CD7F
    if ((selected_record_idx_9e3c == 255)) goto L_CD99;    // $CD8A
    latched_selected_record_idx = selected_record_idx_9e3c;    // $CD90
    selected_record_idx_9e3c = 255;    // $CD96
L_CD99:
    ui_input_sel_latch_7fdf = 255;    // $CD9C
    set_cursor(2, 20);    // $CDA2
    ui_state_flag_7bf9 = 0;    // $CDA7
    combat_unit_window_mode_flag = 0;    // $CDAB
    return 0;    // $CDAE
}

// $CDAF cursor_advance_row
// (body @ $CDB4)

word cursor_advance_row(void) {
    ui_window_col = 2;    // $CDB5
    ui_cursor_row = (ui_cursor_row + 1);    // $CDBC
    phi_ret_cdc9 = ((unsigned)(ui_cursor_row + 1) > (unsigned)27);    // $CDC2
    if (!(phi_ret_cdc9)) goto L_CDC9;    // $CDC2
    ui_cursor_row = 3;    // $CDC6
    phi_ret_cdc9 = 3;    // $CDC6
L_CDC9:
    return phi_ret_cdc9;    // $CDC9
}

// $CDCA char_classify
// (body @ $CDCF)

word char_classify(word arg1) {
    if (!((*(byte*)&arg1 >= 95))) goto L_CDF4;    // $CDD5
    if (!((*(byte*)&arg1 <= 122))) goto L_CDF4;    // $CDDE
    goto L_CE11;    // $CDE3
L_CDE6:
    if (!((*(byte*)&arg1 <= 90))) goto L_CDFD;    // $CDEC
    goto L_CE11;    // $CDF1
L_CDF4:
    if ((*(byte*)&arg1 >= 65)) goto L_CDE6;    // $CDFA
L_CDFD:
    if (!((*(byte*)&arg1 >= 45))) goto L_CE1D;    // $CE03
    if (!((*(byte*)&arg1 <= 58))) goto L_CE1D;    // $CE0C
L_CE11:
L_CE16:
    *(byte*)&arg1 = (*(byte*)&arg1 - 40);    // $CE16
    return *(byte*)&arg1;    // $CE1C
L_CE1D:
    switch (*(byte*)&arg1) {    // $CE20
        case 32: goto L_CE55;    // $CE20
        case 33: goto L_CE55;    // $CE20
        case 35: goto L_CE5A;    // $CE20
        case 37: goto L_CE5F;    // $CE20
        case 40: goto L_CE64;    // $CE20
        case 41: goto L_CE64;    // $CE20
        case 42: goto L_CE69;    // $CE20
        case 43: goto L_CE69;    // $CE20
        case 44: goto L_CE69;    // $CE20
        case 60: goto L_CE73;    // $CE20
        case 62: goto L_CE78;    // $CE20
        case 63: goto L_CE78;    // $CE20
        default: goto L_CE7D;    // $CE20
    }    // $CE20
L_CE55:
    goto L_CE11;    // $CE57
L_CE5A:
    goto L_CE16;    // $CE5C
L_CE5F:
    goto L_CE16;    // $CE61
L_CE64:
    goto L_CE11;    // $CE66
L_CE69:
    goto L_CE16;    // $CE70
L_CE73:
    goto L_CE16;    // $CE75
L_CE78:
    goto L_CE11;    // $CE7A
L_CE7D:
    goto L_CE16;    // $CE7E
}

// $CE81 char_advance_width
// (body @ $CE86)

word char_advance_width(word arg1) {
    if (!((*(byte*)&arg1 == 10))) goto L_CE92;    // $CE8B
    return cursor_advance_row();    // $CE91
L_CE92:
    *(byte*)&arg1 = char_classify(*(byte*)&arg1);    // $CE9A
    syscall_ppu_fill_rect(0, ui_window_col, ui_cursor_row, ui_window_col, ui_cursor_row, *(byte*)&arg1);    // $CEAF
    ui_window_col = (ui_window_col + 1);    // $CEB7
    phi_ret_cec3 = ((unsigned)(ui_window_col + 1) > (unsigned)31);    // $CEBD
    if (!(phi_ret_cec3)) goto L_CEC3;    // $CEBD
    phi_ret_cec3 = cursor_advance_row();    // $CEC0
L_CEC3:
    return phi_ret_cec3;    // $CEC3
}

// $CEC4 redraw_window
// (body @ $CEC9)

word redraw_window(word arg1) {
    goto L_CF1E;    // $CEC9
L_CECC:
    if (!((cur_char == 10))) goto L_CEEC;    // $CED1
    if ((local11 == ui_window_col)) goto L_CF1B;    // $CED9
    goto L_CF13;    // $CEE9
L_CEEC:
    buf_ptr = (buf_ptr + 1);    // $CEEF
    *(byte*)(((buf_ptr + 1) - 1)) = char_classify(cur_char);    // $CEFB
    ui_window_col = (ui_window_col + 1);    // $CF00
    if (!(((ui_window_col + 1) == 32))) goto L_CF27;    // $CF06
L_CF13:
L_CF1B:
    ppu_copy_rect_wrap(local11, ui_cursor_row, 31, ui_cursor_row, &tile_buf, 4);    // $CF17
L_CF1E:
    cursor_advance_row();    // $CF1B
    local11 = ui_window_col;    // $CF21
    buf_ptr = &tile_buf;    // $CF25
L_CF27:
    arg1 = (arg1 + 1);    // $CF29
    cur_char = *(byte*)(((arg1 + 1) - 1));    // $CF2C
    if (*(byte*)(((arg1 + 1) - 1))) goto L_CECC;    // $CF2F
    phi_ret_cf4f = (local11 != ui_window_col);    // $CF37
    if (!(phi_ret_cf4f)) goto L_CF4F;    // $CF37
    phi_ret_cf4f = ppu_copy_rect_wrap(local11, ui_cursor_row, (ui_window_col - 1), ui_cursor_row, &tile_buf, 4);    // $CF4B
L_CF4F:
    return phi_ret_cf4f;    // $CF4F
}

// $CF50 fill_nametable_wrap
// (body @ $CF55)

word fill_nametable_wrap(void) {
    return syscall_fill_nametable(0, 1);    // $CF5C
}

// $CF5D fill_attr_wrap
// (body @ $CF62)

word fill_attr_wrap(void) {
    return syscall_fill_attr_quadrant(0, 0);    // $CF69
}

// $CF6A ppu_render_rect_wrap
// (body @ $CF6F)

word ppu_render_rect_wrap(word arg1, word arg2, word arg3, word arg4, word arg5) {
    return syscall_ppu_render_rect(0, arg1, arg2, arg3, arg4, arg5);    // $CF7B
}

// $CF7C ppu_upload_block_wrap
// (body @ $CF81)

word ppu_upload_block_wrap(word arg1, word arg2, word arg3, word arg4) {
    return syscall_ppu_upload_block(arg1, arg2, arg3, arg4);    // $CF8A
}

// $CF8B palette_write_wrap
// (body @ $CF90)

word palette_write_wrap(word arg1, word arg2) {
    return syscall_palette_write(arg1, arg2);    // $CF97
}

// $CF98 num_to_ascii
// (body @ $CF9D)

word num_to_ascii(word arg1, word arg2, word arg3) {
    if (!(((unsigned)arg2 < (unsigned)arg3))) goto L_CFBC;    // $CFA0
    *(word*)(arg1) = (*(word*)(arg1) + 1);    // $CFA7
    *(byte*)(((*(word*)(arg1) + 1) - 1)) = (((unsigned)arg2 < (unsigned)10) ? (arg2 + 48) : (arg2 + 55));    // $CFB9
    return 1;    // $CFBB
L_CFBC:
    local11 = num_to_ascii(arg1, ((unsigned)arg2 / (unsigned)arg3), arg3);    // $CFC6
    num_to_ascii(arg1, ((unsigned)arg2 % (unsigned)arg3), arg3);    // $CFCD
    return (local11 + 1);    // $CFD3
}

// $CFD4 atoi_decimal
// (body @ $CFD9)

word atoi_decimal(word arg1) {
    local11 = 0;    // $CFDA
    goto L_CFED;    // $CFDB
L_CFDE:
    local11 = (digit + (local11 * 10));    // $CFE7
    *(word*)(arg1) = (*(word*)(arg1) + 1);    // $CFEC
L_CFED:
    digit = (*(byte*)(*(word*)(arg1)) + -48);    // $CFF2
    if (((*(byte*)(*(word*)(arg1)) + -48) < 10)) goto L_CFDE;    // $CFF7
    return local11;    // $CFFB
}

// $CFFC format_string
// (body @ $D001)

word format_string(word arg1, word arg2) {
    arg1 = (arg1 + 2);    // $D003
    fmt_cursor = *(word*)(((arg1 + 2) + -2));    // $D007
    vararg_ptr = arg1;    // $D00A
    goto L_D018;    // $D00C
L_D00F:
    arg2 = (arg2 + 1);    // $D011
    *(byte*)(((arg2 + 1) - 1)) = ch;    // $D017
L_D018:
    fmt_cursor = (fmt_cursor + 1);    // $D01B
    ch = *(byte*)(((fmt_cursor + 1) - 1));    // $D01F
    if (!(*(byte*)(((fmt_cursor + 1) - 1)))) goto L_D130;    // $D022
    if (!((ch == 37))) goto L_D00F;    // $D02B
    out_cursor = &conv_buf;    // $D031
    width = 6;    // $D034
    has_precision = 0;    // $D037
    ch = *(byte*)(fmt_cursor);    // $D03C
    if (!(is_digit(ch))) goto L_D055;    // $D047
    atoi_decimal(&fmt_cursor);    // $D04E
    goto L_D056;    // $D052
L_D055:
L_D056:
    pad = 0;    // $D056
    fmt_cursor = (fmt_cursor + 1);    // $D05B
    ch = *(byte*)(((fmt_cursor + 1) - 1));    // $D05F
    if (!((*(byte*)(((fmt_cursor + 1) - 1)) == 46))) goto L_D07F;    // $D065
    width = atoi_decimal(&fmt_cursor);    // $D070
    has_precision = 1;    // $D073
    fmt_cursor = (fmt_cursor + 1);    // $D078
    ch = *(byte*)(((fmt_cursor + 1) - 1));    // $D07C
L_D07F:
    switch (to_upper(ch)) {    // $D087
        case 0: goto L_D12F;    // $D087
        case 67: goto L_D0D0;    // $D087
        case 68: goto L_D09C;    // $D087
        case 83: goto L_D0B7;    // $D087
        default: goto L_D00F;    // $D087
    }    // $D087
L_D09C:
    vararg_ptr = (vararg_ptr + 2);    // $D0A0
    pad = (pad - num_to_ascii(&out_cursor, *(word*)(((vararg_ptr + 2) + -2)), 10));    // $D0B2
    goto L_D0E5;    // $D0B4
L_D0B7:
    vararg_ptr = (vararg_ptr + 2);    // $D0BA
    out_cursor = *(word*)(((vararg_ptr + 2) + -2));    // $D0BF
    pad = (pad - strlen(out_cursor));    // $D0CB
    goto L_D0FC;    // $D0CD
L_D0D0:
    pad = (pad - 1);    // $D0D3
    out_cursor = (out_cursor + 1);    // $D0D8
    vararg_ptr = (vararg_ptr + 2);    // $D0DF
    *(byte*)(((out_cursor + 1) - 1)) = *(word*)(((vararg_ptr + 2) + -2));    // $D0E4
L_D0E5:
    *(byte*)(out_cursor) = 0;    // $D0E8
    out_cursor = &conv_buf;    // $D0EC
    has_precision = 0;    // $D0EF
    goto L_D0FC;    // $D0F1
L_D0F4:
    arg2 = (arg2 + 1);    // $D0F6
    *(byte*)(((arg2 + 1) - 1)) = 32;    // $D0FB
L_D0FC:
    pad = (pad - 1);    // $D0FF
    if ((((pad - 1) + 1) > 0)) goto L_D0F4;    // $D104
L_D107:
    if (!(*(byte*)(out_cursor))) goto L_D018;    // $D10A
    if (!((!(has_precision) || (width > 0)))) goto L_D127;    // $D116
    arg2 = (arg2 + 1);    // $D11B
    *(byte*)(((arg2 + 1) - 1)) = *(byte*)(out_cursor);    // $D121
    width = (width - 1);    // $D125
L_D127:
    out_cursor = (out_cursor + 1);    // $D12A
    goto L_D107;    // $D12C
L_D12F:
    return (out_cursor + 1);    // $D12F
L_D130:
    *(byte*)(arg2) = 0;    // $D132
    return 0;    // $D133
}

// $D134 draw_message
// (body @ $D139)

word draw_message(word arg1) {
    format_string(&arg1, &msg_buf);    // $D141
    return redraw_window(&msg_buf);    // $D14D
}

// $D14E poll_input
// (body @ $D153)

word poll_input(void) {
    local11 = 2;    // $D154
    switch (ui_input_mode) {    // $D158
        case 0: goto L_D169;    // $D158
        case 1: goto L_D1E1;    // $D158
        case 2: goto L_D1E8;    // $D158
        case 3: goto L_D1EE;    // $D158
        case 4: goto L_D24E;    // $D158
        default: goto L_D16B;    // $D158
    }    // $D158
L_D169:
    phi_val_d16a = 0;    // $D169
L_D16A:
    local11 = phi_val_d16a;    // $D16A
L_D16B:
    if (((unsigned)local11 > (unsigned)1)) goto L_D1C9;    // $D16E
L_D171:
    local11 = (local11 & 1);    // $D174
    if (!(((local11 & 1) != ui_input_sel_latch_7fdf))) goto L_D1AD;    // $D179
    local9 = ui_window_col;    // $D17F
    local8 = ui_cursor_row;    // $D183
    ppu_render_rect_wrap(20, 26, 29, 26, 1);    // $D18D
    set_cursor(21, 26);    // $D195
    draw_message(0xF68A, (local11 + 1));    // $D19F
    set_cursor(local9, local8);    // $D1A5
    ui_input_sel_latch_7fdf = local11;    // $D1AA
L_D1AD:
    if ((ui_timer_gate_flag_7fe7 == 2)) goto L_D269;    // $D1B2
    frame_counter = (frame_counter - 1);    // $D1B9
    switch ((frame_counter - 1)) {    // $D1BC
        case 100: goto L_D252;    // $D1BC
        case 0: goto L_D270;    // $D1BC
        default: goto L_D269;    // $D1BC
    }    // $D1BC
L_D1C9:
    phi_val_d1ca = 0;    // $D1C9
L_D1CA:
    local11 = phi_val_d1ca;    // $D1CA
    if (!((*(byte*)((local11 + 0x7FD5)) != fief_owner(local10)))) goto L_D171;    // $D1D9
    phi_val_d1ca = (local11 + 1);    // $D1DE
    goto L_D1CA;    // $D1DE
L_D1E1:
    phi_val_d1e4 = selected_province_idx;    // $D1E1
L_D1E4:
    local10 = phi_val_d1e4;    // $D1E4
    goto L_D16B;    // $D1E5
L_D1E8:
    phi_val_d1e4 = battle_defending_province;    // $D1EB
    goto L_D1E4;    // $D1EB
L_D1EE:
    if ((mem_7FE1 != 255)) goto L_D23D;    // $D1F5
    phi_val_d1fe = 0;    // $D1F9
    goto L_D1FE;    // $D1F9
L_D1FC:
    phi_val_d1fe = (local11 + 1);    // $D1FD
L_D1FE:
    local11 = phi_val_d1fe;    // $D1FE
    if (!((*(byte*)((local11 + 0x7FD5)) != selected_province_owner()))) goto L_D214;    // $D20B
    if (((unsigned)local11 < (unsigned)8)) goto L_D1FC;    // $D211
L_D214:
    if (!(((unsigned)local11 >= (unsigned)8))) goto L_D237;    // $D217
    phi_val_d220 = 0;    // $D21B
    goto L_D220;    // $D21B
L_D21E:
    phi_val_d220 = (local11 + 1);    // $D21F
L_D220:
    local11 = phi_val_d220;    // $D220
    if ((*(byte*)((local11 + 0x7FD5)) != fief_owner(battle_defending_province))) goto L_D21E;    // $D231
    local11 = (local11 + 1);    // $D236
L_D237:
    mem_7FE1 = (local11 & 1);    // $D23A
L_D23D:
    local11 = mem_7FE1;    // $D240
    if (!(cur_combat_side)) goto L_D16B;    // $D244
    phi_val_d16a = (local11 ^ 1);    // $D24B
    goto L_D16A;    // $D24B
L_D24E:
    phi_val_d16a = 1;    // $D24F
    goto L_D16A;    // $D24F
L_D252:
L_D269:
    syscall_set_sprite(0, (ui_window_col << 3), ((ui_cursor_row << 3) - 1), 0, ui_timer_gate_flag_7fe7);    // $D265
    return syscall_read_controller(local11);    // $D26F
L_D270:
    syscall_set_sprite(0, 248, 248, 0, 2);    // $D27A
    frame_counter = 200;    // $D281
    goto L_D269;    // $D284
}

// $D287 wait_button_edge
// (body @ $D28C)

word wait_button_edge(void) {
L_D28C:
    if (poll_input()) goto L_D28C;    // $D28F
    local11 = 0;    // $D293
L_D294:
    local11 = poll_input();    // $D297
    if (!(poll_input())) goto L_D294;    // $D298
    return local11;    // $D29C
}

// $D29D read_frame_timer
// (body @ $D2A2)

word read_frame_timer(word arg1) {
    ui_timer_gate_flag_7fe7 = (arg1 ? (arg1 - 1) : 2);    // $D2AC
    if (arg1) goto L_D2CA;    // $D2B0
    syscall_set_sprite(0, 248, 248, 0, 2);    // $D2BD
    phi_ret_d2f8 = syscall_wait_for_nmi();    // $D2C7
    goto L_D2F8;    // $D2C7
L_D2CA:
    if ((arg1 != 1)) goto L_D2DB;    // $D2CD
    phi_d2ec_0 = 248;    // $D2D8
    phi_d2ec_1 = 248;    // $D2D8
    phi_d2ec_2 = 0;    // $D2D8
    phi_d2ec_3 = 2;    // $D2D8
    goto L_D2EC;    // $D2D8
L_D2DB:
    phi_d2ec_0 = (ui_window_col << 3);    // $D2EB
    phi_d2ec_1 = ((ui_cursor_row << 3) - 1);    // $D2EB
    phi_d2ec_2 = 0;    // $D2EB
    phi_d2ec_3 = ui_timer_gate_flag_7fe7;    // $D2EB
L_D2EC:
    syscall_set_sprite(0, phi_d2ec_0, phi_d2ec_1, phi_d2ec_2, phi_d2ec_3);    // $D2EE
    frame_counter = 200;    // $D2F5
    phi_ret_d2f8 = 200;    // $D2F5
L_D2F8:
    return phi_ret_d2f8;    // $D2F8
}

// $D2F9 clear_rect_left_upper
// (body @ $D2FE)

word clear_rect_left_upper(void) {
    return ppu_fill_rect_wrap(2, 8, 9, 19, 1);    // $D308
}

// $D309 clear_rect_left_lower
// (body @ $D30E)

word clear_rect_left_lower(void) {
    return ppu_fill_rect_wrap(2, 20, 9, 26, 1);    // $D319
}

// $D31A clear_rect_left_lower_alt
// (body @ $D31F)

word clear_rect_left_lower_alt(void) {
    standard_delay();    // $D31F
    return clear_rect_left_lower();    // $D325
}

// $D326 message_display
// (body @ $D32B)

word message_display(word arg1) {
    if (!(ui_msg_oneshot_flag_7fc5)) goto L_D338;    // $D32E
    clear_rect_left_lower();    // $D331
    ui_msg_oneshot_flag_7fc5 = 0;    // $D335
L_D338:
    set_cursor(2, (ui_msg_col_shift_flag ? 20 : 22));    // $D347
    return redraw_window(arg1);    // $D350
}

// $D351 prompt_ab_window
// (body @ $D356)

word prompt_ab_window(word arg1) {
    redraw_window(arg1);    // $D357
L_D360:
    read_frame_timer(1);    // $D35C
    local11 = wait_button_edge();    // $D363
    if (!((wait_button_edge() != 64))) goto L_D378;    // $D367
    if ((local11 == 128)) goto L_D378;    // $D36F
    if ((local11 != 2)) goto L_D360;    // $D375
L_D378:
    read_frame_timer(0);    // $D379
    if ((local11 != 64)) goto L_D38E;    // $D381
    char_advance_width(60);    // $D386
    phi_val_d3a1 = 1;    // $D38B
    goto L_D3A1;    // $D38B
L_D38E:
    if ((local11 != 128)) goto L_D3A0;    // $D393
    char_advance_width(62);    // $D398
    phi_val_d3a1 = 0;    // $D39D
    goto L_D3A1;    // $D39D
L_D3A0:
    phi_val_d3a1 = 2;    // $D3A0
L_D3A1:
    local11 = phi_val_d3a1;    // $D3A1
    open_message_window();    // $D3A2
    return local11;    // $D3A6
}

// $D3A7 prompt_y_n
// (body @ $D3AC)

word prompt_y_n(void) {
    redraw_window(msg_y_n_f695);    // $D3AF
L_D3B8:
    read_frame_timer(1);    // $D3B4
    local11 = wait_button_edge();    // $D3BB
    if (!((wait_button_edge() != 64))) goto L_D3CA;    // $D3BF
    if ((local11 != 128)) goto L_D3B8;    // $D3C7
L_D3CA:
    read_frame_timer(0);    // $D3CB
    if ((local11 != 64)) goto L_D3E0;    // $D3D3
    char_advance_width(89);    // $D3D8
    phi_val_d3e7 = 1;    // $D3DD
    goto L_D3E7;    // $D3DD
L_D3E0:
    char_advance_width(78);    // $D3E2
    phi_val_d3e7 = 0;    // $D3E6
L_D3E7:
    local11 = phi_val_d3e7;    // $D3E7
    open_message_window();    // $D3E8
    return local11;    // $D3EC
}

// $D3ED cursor_nav_loop
// (body @ $D3F2)

word cursor_nav_loop(word arg1) {
    local4 = 0;    // $D3F3
    local6 = 0;    // $D3F5
    local5 = 1;    // $D3F7
L_D3F8:
    *(word*)(((local5 << 1) + &local6)) = 255;    // $D404
    local5 = (local5 + 1);    // $D407
    if ((local5 <= 5)) goto L_D3F8;    // $D40B
    draw_message(msg_fmt__d_f69e, local6);    // $D412
    ui_window_col = (ui_window_col - 1);    // $D41A
    read_frame_timer(1);    // $D41E
    wait_button_edge();    // $D422
    local2 = 0;    // $D426
L_D427:
    switch (poll_input()) {    // $D42A
        case 1: goto L_D459;    // $D42A
        case 2: goto L_D447;    // $D42A
        case 16: goto L_D469;    // $D42A
        case 32: goto L_D4AF;    // $D42A
        case 64: goto L_D4DB;    // $D42A
        case 128: goto L_D511;    // $D42A
        default: goto L_D460;    // $D42A
    }    // $D42A
L_D447:
    read_frame_timer(0);    // $D448
    if ((ui_input_prompt_active_flag != 1)) goto L_D457;    // $D451
    return -1;    // $D456
L_D457:
    return 0;    // $D458
L_D459:
    read_frame_timer(0);    // $D45A
    local2 = 1;    // $D45F
L_D460:
    if (!(local2)) goto L_D427;    // $D461
    local3 = 0;    // $D465
    phi_val_d573 = 0;    // $D466
    goto L_D573;    // $D466
L_D469:
    *(word*)(((local4 << 1) + &local6)) = (*(word*)(((local4 << 1) + &local6)) + 1);    // $D474
    if (!(((unsigned)(*(word*)(((local4 << 1) + &local6)) + 1) >= (unsigned)10))) goto L_D485;    // $D477
    *(word*)(((local4 << 1) + &local6)) = 0;    // $D484
L_D485:
    phi_d492_0 = 0xF6A1;    // $D48F
    phi_d492_1 = *(word*)(((local4 << 1) + &local6));    // $D48F
L_D492:
    draw_message(phi_d492_0, phi_d492_1);    // $D492
    ui_window_col = (ui_window_col - 1);    // $D49A
    read_frame_timer(0);    // $D49E
    delay_loop(2);    // $D4A3
    read_frame_timer(1);    // $D4A8
    goto L_D460;    // $D4AC
L_D4AF:
    *(word*)(((local4 << 1) + &local6)) = (*(word*)(((local4 << 1) + &local6)) - 1);    // $D4BA
    if (!(((unsigned)(*(word*)(((local4 << 1) + &local6)) - 1) >= (unsigned)10))) goto L_D4CB;    // $D4BD
    *(word*)(((local4 << 1) + &local6)) = 9;    // $D4CA
L_D4CB:
    phi_d492_0 = 0xF6A4;    // $D4D8
    phi_d492_1 = *(word*)(((local4 << 1) + &local6));    // $D4D8
    goto L_D492;    // $D4D8
L_D4DB:
    if (!(local4)) goto L_D460;    // $D4DC
    read_frame_timer(0);    // $D4E0
    redraw_window(0xF6A7);    // $D4E7
    ui_window_col = (ui_window_col - 2);    // $D4F1
    read_frame_timer(1);    // $D4F5
    local4 = (local4 - 1);    // $D4FF
    *(word*)(((((local4 - 1) + 1) << 1) + &local6)) = 255;    // $D508
L_D509:
    delay_loop(2);    // $D50A
    goto L_D460;    // $D50E
L_D511:
    if (!(((arg1 - 1) != local4))) goto L_D460;    // $D515
    if (local4) goto L_D528;    // $D519
    if (!(*(word*)(((local4 << 1) + &local6)))) goto L_D460;    // $D525
L_D528:
    read_frame_timer(0);    // $D529
    ui_window_col = (ui_window_col + 1);    // $D531
    local4 = (local4 + 1);    // $D53A
    *(word*)((((local4 + 1) << 1) + &local6)) = 0;    // $D540
    draw_message(0xF6A9, *(word*)(((local4 << 1) + &local6)));    // $D54E
    ui_window_col = (ui_window_col - 1);    // $D556
    read_frame_timer(1);    // $D55A
    goto L_D509;    // $D55E
L_D561:
    local3 = ((local3 * 10) + *(word*)(((local5 << 1) + &local6)));    // $D570
    phi_val_d573 = (local5 + 1);    // $D572
L_D573:
    local5 = phi_val_d573;    // $D573
    if ((*(word*)(((local5 << 1) + &local6)) != 255)) goto L_D561;    // $D581
    return local3;    // $D585
}

// $D586 count_div_iterations_d586
// (body @ $D58B)

word count_div_iterations_d586(word arg1) {
    phi_val_d596 = 0;    // $D58C
    goto L_D596;    // $D58C
L_D58F:
    arg1 = (arg1 / 10);    // $D593
    phi_val_d596 = (local11 + 1);    // $D595
L_D596:
    local11 = phi_val_d596;    // $D596
    if (arg1) goto L_D58F;    // $D598
    return local11;    // $D59C
}

// $D59D select_province_by_cursor
// (body @ $D5A2)

word select_province_by_cursor(word arg1, word arg2) {
    local11 = count_div_iterations_d586(arg2);    // $D5A7
    local9 = ui_window_col;    // $D5AB
    local8 = ui_cursor_row;    // $D5AF
L_D5B0:
    set_cursor(local9, local8);    // $D5B2
    phi_val_d5c2 = 0;    // $D5B7
    goto L_D5C2;    // $D5B7
L_D5BA:
    char_advance_width(32);    // $D5BC
    phi_val_d5c2 = (local10 + 1);    // $D5C1
L_D5C2:
    local10 = phi_val_d5c2;    // $D5C2
    if ((local10 < local11)) goto L_D5BA;    // $D5C6
    set_cursor(local9, local8);    // $D5CB
    local7 = cursor_nav_loop(local11);    // $D5D4
    if ((local7 <= 0)) goto L_D5E7;    // $D5D8
    if (!((local7 >= arg1))) goto L_D5B0;    // $D5DE
    if (!((local7 <= arg2))) goto L_D5B0;    // $D5E4
L_D5E7:
    return local7;    // $D5E8
}

// $D5E9 number_input
// (body @ $D5EE)

word number_input(word arg1, word arg2) {
    draw_message(msg_d_d_f6ac, arg1, arg2);    // $D5F3
    local11 = select_province_by_cursor(arg1, arg2);    // $D5FD
    if ((local11 <= 0)) goto L_D607;    // $D601
L_D607:
    open_message_window();    // $D604
    return local11;    // $D608
}

// $D609 ui_prompt_redraw
// (body @ $D60E)

word ui_prompt_redraw(void) {
    set_cursor(2, 26);    // $D611
    redraw_window(msg_hit_any_key_f6b7);    // $D618
    local11 = wait_button_edge();    // $D61F
    open_message_window();    // $D620
    reset_prompt_selection();    // $D623
    return local11;    // $D627
}

// $D628 count_6da2_set
// (body @ $D62D)

word count_6da2_set(void) {
    local10 = 0;    // $D62E
    local11 = 0;    // $D62F
    goto L_D64E;    // $D630
L_D633:
    if (fief_is_daimyo_capital[local10]) goto L_D648;    // $D639
    if (!((get_province_ai_state(local10) == 255))) goto L_D64B;    // $D645
L_D648:
    local11 = (local11 + 1);    // $D64A
L_D64B:
    local10 = (local10 + 1);    // $D64D
L_D64E:
    if (((unsigned)local10 < (unsigned)scenario_fief_count)) goto L_D633;    // $D653
    if ((local11 != 1)) goto L_D66B;    // $D659
    local11 = (local11 & (is_ai_count_ge_8() ? 0 : 1));    // $D66A
L_D66B:
    return ((local11 != 1) ? 0 : 1);    // $D676
}

// $D677 draw_current_year
// (body @ $D67C)

word draw_current_year(void) {
    return draw_message(0xF6C4, current_game_year);    // $D686
}

// $D687 draw_current_season
// (body @ $D68C)

word draw_current_season(void) {
    switch (current_season) {    // $D68F
        case 0: goto L_D69E;    // $D68F
        case 1: goto L_D6A6;    // $D68F
        case 2: goto L_D6AC;    // $D68F
        case 3: goto L_D6B2;    // $D68F
        default: goto L_D6A5;    // $D68F
    }    // $D68F
L_D69E:
    phi_d6a1_0 = 0xF6C7;    // $D69E
L_D6A1:
L_D6A5:
    return redraw_window(phi_d6a1_0);    // $D6A5
L_D6A6:
    phi_d6a1_0 = 0xF6CE;    // $D6A9
    goto L_D6A1;    // $D6A9
L_D6AC:
    phi_d6a1_0 = 0xF6D5;    // $D6AF
    goto L_D6A1;    // $D6AF
L_D6B2:
    phi_d6a1_0 = 0xF6DA;    // $D6B5
    goto L_D6A1;    // $D6B5
}

// $D6B8 math32_3arg
// (body @ $D6BD)

word math32_3arg(word arg1, word arg2, word arg3) {
    if (!(arg3)) goto L_D6DB;    // $D6BE
    // ext_op sign_extend16_to_32
    // ext_op push_a32_to_vm_stack
    // ext_op sign_extend16_to_32
    // ext_op push_a32_to_vm_stack
    // ext_op sign_extend16_to_32
    // ext_op pop_b32_from_vm_stack
    // ext_op umul32
    // ext_op pop_b32_from_vm_stack
    // ext_op sdiv32
    // ext_op ext_op_nop
    phi_ret_d6dd = arg1;    // $D6D8
    goto L_D6DD;    // $D6D8
L_D6DB:
    phi_ret_d6dd = -1;    // $D6DB
L_D6DD:
    return phi_ret_d6dd;    // $D6DD
}

// $D6DE math32_2arg
// (body @ $D6E3)

word math32_2arg(word arg1, word arg2) {
    if (arg1) goto L_D6ED;    // $D6E4
    if (arg2) goto L_D6ED;    // $D6E8
    return 0;    // $D6EC
L_D6ED:
    // ext_op clear_a_high16
    // ext_op push_a32_to_vm_stack
    // ext_op clear_a_high16
    // ext_op pop_b32_from_vm_stack
    // ext_op add32
    // ext_op push_a32_to_vm_stack
    // ext_op clear_a_high16
    // ext_op umul32
    // ext_op pop_b32_from_vm_stack
    // ext_op sdiv32
    // ext_op ext_op_nop
    return arg1;    // $D70C
}

// $D70D pct_op
// (body @ $D712)

word pct_op(word arg1, word arg2) {
    if ((arg2 != 100)) goto L_D71B;    // $D716
    return arg1;    // $D71A
L_D71B:
    return (((((arg2 % 10) * (arg1 / 10)) / 10) + (((arg1 % 10) * arg2) / 100)) + ((arg2 / 10) * (arg1 / 10)));    // $D73D
}

// $D73E delay_loop
// (body @ $D743)

word delay_loop(word arg1) {
    goto L_D751;    // $D743
L_D746:
    local11 = 240;    // $D749
L_D74A:
    local11 = (local11 - 1);    // $D74C
    if (local11) goto L_D74A;    // $D74E
L_D751:
    arg1 = (arg1 - 1);    // $D753
    if (((arg1 - 1) + 1)) goto L_D746;    // $D755
    return ((arg1 - 1) + 1);    // $D758
}

// $D759 standard_delay
// (body @ $D75E)

word standard_delay(void) {
    return delay_loop(delay_loop_count);    // $D765
}

// $D766 confirm_prompt
// (body @ $D76B)

word confirm_prompt(void) {
    standard_delay();    // $D76B
    return open_message_window();    // $D771
}

// $D772 fief_owner
// (body @ $D777)

word fief_owner(word arg1) {
    return fief_to_daimyo_map[arg1];    // $D77D
}

// $D77E selected_province_owner
// (body @ $D783)

word selected_province_owner(void) {
    return fief_owner(selected_province_idx);    // $D78A
}

// $D78B daimyo_name_width
// (body @ $D790)

word daimyo_name_width(word arg1) {
    redraw_window(msg_lord_f6e1);    // $D793
    local11 = ((fief_owner(arg1) * 9) + 0x77A8);    // $D7A2
    redraw_window(((fief_owner(arg1) * 9) + 0x77A8));    // $D7A4
    return char_advance_width(44);    // $D7AE
}

// $D7AF draw_daimyo_name
// (body @ $D7B4)

word draw_daimyo_name(word arg1) {
    redraw_window(msg_lord_f6e7);    // $D7B7
    local11 = ((fief_owner(arg1) * 9) + 0x77A8);    // $D7C6
    return redraw_window(((fief_owner(arg1) * 9) + 0x77A8));    // $D7CC
}

// $D7CD daimyo_record_addr
// (body @ $D7D2)

word daimyo_record_addr(word arg1) {
    return ((arg1 * 7) + 0x752F);    // $D7D9
}

// $D7DA fief_to_daimyo_record_addr
// (body @ $D7DF)

word fief_to_daimyo_record_addr(word arg1) {
    return daimyo_record_addr(fief_owner(arg1));    // $D7E9
}

// $D7EA selected_province_daimyo_record
// (body @ $D7EF)

word selected_province_daimyo_record(void) {
    return fief_to_daimyo_record_addr(selected_province_idx);    // $D7F6
}

// $D7F7 province_clear_fields_d7f7
// (body @ $D7FC)

word province_clear_fields_d7f7(word arg1) {
    local11 = ((arg1 * 26) + 0x7001);    // $D804
    phi_ret_d814 = *(word*)((local11 + 8));    // $D808
    if (phi_ret_d814) goto L_D814;    // $D808
    *(word*)((local11 + 14)) = 0;    // $D812
    *(word*)((local11 + 12)) = 0;    // $D813
    phi_ret_d814 = 0;    // $D813
L_D814:
    return phi_ret_d814;    // $D814
}

// $D815 province_clear_fields_d815
// (body @ $D81A)

word province_clear_fields_d815(word arg1) {
    local11 = ((arg1 * 26) + 0x7011);    // $D822
    phi_ret_d835 = *(word*)(local11);    // $D825
    if (phi_ret_d835) goto L_D835;    // $D825
    *(word*)((local11 + 6)) = 0;    // $D832
    *(word*)((local11 + 4)) = 0;    // $D833
    *(word*)((local11 + 2)) = 0;    // $D834
    phi_ret_d835 = 0;    // $D834
L_D835:
    return phi_ret_d835;    // $D835
}

// $D836 cap_fief_stats
// (body @ $D83B)

word cap_fief_stats(word fief) {
    fief_rec = ((fief * 26) + 0x7001);    // $D843
    rec_base = fief_rec;    // $D845
    phi_val_d863 = fief_rec;    // $D846
    goto L_D863;    // $D846
L_D849:
    *(word*)(field_ptr) = min_word(*(word*)(field_ptr), *(word*)((fief_rec + 24)));    // $D856
    if (!((*(word*)(field_ptr) < 0))) goto L_D861;    // $D85B
    *(word*)(field_ptr) = 0;    // $D860
L_D861:
    phi_val_d863 = (field_ptr + 2);    // $D862
L_D863:
    field_ptr = phi_val_d863;    // $D863
    if (((unsigned)field_ptr < (unsigned)(rec_base + 24))) goto L_D849;    // $D86B
    *(word*)((fief_rec + 10)) = min_word(*(word*)((fief_rec + 10)), 100);    // $D87B
    i = 0;    // $D87D
    daimyo_rec = fief_to_daimyo_record_addr(fief);    // $D883
    daimyo_byte_ptr = fief_to_daimyo_record_addr(fief);    // $D884
    goto L_D8A9;    // $D885
L_D888:
    if (!((*(byte*)(daimyo_byte_ptr) > 235))) goto L_D894;    // $D88E
    *(byte*)(daimyo_byte_ptr) = 0;    // $D893
L_D894:
    if (!((*(byte*)(daimyo_byte_ptr) > 210))) goto L_D8A1;    // $D89A
    *(byte*)(daimyo_byte_ptr) = -46;    // $D8A0
L_D8A1:
    daimyo_byte_ptr = (daimyo_byte_ptr + 1);    // $D8A3
    i = (i + 1);    // $D8A7
L_D8A9:
    if (((unsigned)i < (unsigned)6)) goto L_D888;    // $D8AC
    province_clear_fields_d815(fief);    // $D8B0
    return province_clear_fields_d7f7(fief);    // $D8B9
}

// $D8BA develop_gain
// (body @ $D8BF)

word develop_gain(word amount, word stat_ptr, word companion_ptr) {
    if ((amount >= 1)) goto L_D8C7;    // $D8C2
    return 0;    // $D8C6
L_D8C7:
    gain = math32_3arg(amount, (6 - const_two), (sqrt_int(((*(word*)(stat_ptr) + *(word*)(companion_ptr)) / 2)) + sqrt_int(amount)));    // $D8E9
    if (gain) goto L_D8F0;    // $D8EB
    return 1;    // $D8EF
L_D8F0:
    return gain;    // $D8F1
}

// $D8F2 record_grow_capped_d8f2
// (body @ $D8F7)

word record_grow_capped_d8f2(word arg1, word arg2) {
    local11 = develop_gain(arg2, (arg1 + 12), (arg1 + 8));    // $D902
    local10 = (arg1->header - arg1->loyalty);    // $D90D
    if (!((local11 > (arg1->header - arg1->loyalty)))) goto L_D917;    // $D912
    return local10;    // $D916
L_D917:
    return local11;    // $D918
}

// $D919 record_grow_capped_d919
// (body @ $D91E)

word record_grow_capped_d919(word arg1, word arg2) {
    local11 = develop_gain(arg2, (arg1 + 14), (arg1 + 4));    // $D929
    local10 = (arg1->header - arg1->wealth);    // $D934
    if (!((local11 > (arg1->header - arg1->wealth)))) goto L_D93E;    // $D939
    return local10;    // $D93D
L_D93E:
    return local11;    // $D93F
}

// $D940 record_apply_two_grows
// (body @ $D945)

word record_apply_two_grows(word arg1, word arg2) {
    arg1->loyalty = (arg1->loyalty + record_grow_capped_d8f2(arg1, arg2));    // $D952
    arg1->wealth = (arg1->wealth + record_grow_capped_d919(arg1, arg2));    // $D960
    return (arg1->wealth + record_grow_capped_d919(arg1, arg2));    // $D961
}

// $D962 set_6da1_bit7
// (body @ $D967)

word set_6da1_bit7(void) {
    ai_turn_flags = (ai_turn_flags | -128);    // $D96E
    return (ai_turn_flags | -128);    // $D971
}

// $D972 fief_owner_weakness
// (body @ $D977)

word fief_owner_weakness(word arg1) {
    return daimyo_weakness_flag[fief_owner(arg1)];    // $D981
}

// $D982 is_ai_count_ge_8
// (body @ $D987)

word is_ai_count_ge_8(void) {
    return ((unsigned)ai_player_count >= (unsigned)8);    // $D98C
}

// $D98D get_province_ai_state
// (body @ $D992)

word get_province_ai_state(word arg1) {
    return province_ai_state[arg1];    // $D998
}

// $D999 province_state_is_FF
// (body @ $D99E)

word province_state_is_FF(word arg1) {
    return (province_ai_state[arg1] == 255);    // $D9A8
}

// $D9A9 get_6da2_cur
// (body @ $D9AE)

word get_6da2_cur(void) {
    return fief_is_daimyo_capital[selected_province_idx];    // $D9B6
}

// $D9B7 is_enemy_owned
// (body @ $D9BC)

word is_enemy_owned(word arg1) {
    return (fief_owner(arg1) == selected_province_owner());    // $D9C7
}

// $D9C8 province_ai_state_addr
// (body @ $D9CD)

word province_ai_state_addr(word arg1) {
    return (arg1 + 0x6CF7);    // $D9D2
}

// $D9D3 draw_window_row_7985
// (body @ $D9D8)

word draw_window_row_7985(word arg1) {
    return redraw_window(((arg1 * 10) + 0x7985));    // $D9E4
}

// $D9E5 test_6f65_bit7
// (body @ $D9EA)

word test_6f65_bit7(word arg1) {
    return ((war_side_state_flag[arg1] & 128) != 0);    // $D9F6
}

// $D9F7 classify_7b79
// (body @ $D9FC)

word classify_7b79(word arg1) {
    if (!((*(byte*)((arg1 + 0x7B79)) == 6))) goto L_DA0D;    // $DA04
    goto L_DA21;    // $DA0A
L_DA0D:
L_DA21:
    local11 = ((*(byte*)((arg1 + 0x7B79)) == 7) ? msg_christns_f6f5 : msg_rioters_f6fe);    // $DA21
    return local11;    // $DA23
}

// $DA24 scaled_transfer_da24
// (body @ $DA29)

word scaled_transfer_da24(word arg1, word arg2, word arg3, word arg4, word arg5) {
    return min_word((pct_op(arg1, math32_2arg(arg4, arg3)) + pct_op((arg2 | 1), math32_2arg(arg3, arg4))), arg5);    // $DA4E
}

// $DA4F diplomacy_helper2
// (body @ $DA54)

word diplomacy_helper2(void) {
    dsel_da73 = ((unsigned)selected_province_idx < (unsigned)battle_defending_province);    // $DA73
    *(byte*)((((dsel_da73 ? (selected_province_idx * 54) : (battle_defending_province * 54)) + (dsel_da73 ? battle_defending_province : selected_province_idx)) + 0x6193)) = 70;    // $DA7B
    return 70;    // $DA7C
}

// $DA7D diplomacy_helper3
// (body @ $DA82)

word diplomacy_helper3(void) {
    local11 = selected_province_owner();    // $DA85
    local10 = fief_owner(battle_defending_province);    // $DA8D
    dsel_daa1 = ((unsigned)local11 < (unsigned)local10);    // $DAA1
    *(byte*)((((dsel_daa1 ? (local10 * 54) : (local11 * 54)) + (dsel_daa1 ? local11 : local10)) + 0x6193)) = 90;    // $DAA9
    return 90;    // $DAAA
}

// $DAAB load_daimyo_relation_row
// (body @ $DAB0)

word load_daimyo_relation_row(word arg1) {
    syscall16_sram_wrap(4, ((arg1 << 3) + ((scenario_fief_count == 17) ? relation_base_data_8300 : relation_base_data_8004)), deduped_owner_list, 8);    // $DACF
    return 0x6F4F;    // $DAD6
}

// $DAD7 combat_helper_dad7
// (body @ $DADC)

word combat_helper_dad7(void) {
    load_daimyo_relation_row(selected_province_idx);    // $DADF
    src = 0x6F4F;    // $DAE6
    dst = 0x6F4F;    // $DAE7
    goto L_DB04;    // $DAE8
L_DAEB:
    if (!((get_province_ai_state(*(byte*)(src)) != 255))) goto L_DB01;    // $DAF6
    dst = (dst + 1);    // $DAFB
    *(byte*)(((dst + 1) - 1)) = *(byte*)(src);    // $DB00
L_DB01:
    src = (src + 1);    // $DB03
L_DB04:
    if ((*(byte*)(src) != 255)) goto L_DAEB;    // $DB0A
    *(byte*)(dst) = -1;    // $DB10
    return -1;    // $DB11
}

// $DB12 defender_owner_is_keyed_daimyo
// (body @ $DB17)

word defender_owner_is_keyed_daimyo(void) {
    if ((scenario_fief_count != 17)) goto L_DB2A;    // $DB1D
    return (fief_owner(battle_defending_province) == 3);    // $DB29
L_DB2A:
    return (fief_owner(battle_defending_province) == 20);    // $DB34
}

// $DB35 ui_helper_db35
// (body @ $DB3A)

word ui_helper_db35(void) {
    ai_player_count = (ai_player_count + 1);    // $DB3E
    phi_ret_db4a = is_ai_count_ge_8();    // $DB44
    if (!(phi_ret_db4a)) goto L_DB4A;    // $DB44
    phi_ret_db4a = set_6da1_bit7();    // $DB47
L_DB4A:
    return phi_ret_db4a;    // $DB4A
}

// $DB4B draw_owner_name
// (body @ $DB50)

word draw_owner_name(word arg1) {
    phi_ret_db6d = (province_ai_state[arg1] != 255);    // $DB5A
    if (!(phi_ret_db6d)) goto L_DB6D;    // $DB5A
    phi_ret_db6d = redraw_window(((fief_owner(arg1) * 9) + 0x77A8));    // $DB69
L_DB6D:
    return phi_ret_db6d;    // $DB6D
}

// $DB6E draw_province_lord_name
// (body @ $DB73)

word draw_province_lord_name(word arg1) {
    if ((province_ai_state[arg1] == 255)) goto L_DB8F;    // $DB7D
    phi_db92_0 = ((fief_owner(arg1) * 9) + 0x77A8);    // $DB8C
    goto L_DB92;    // $DB8C
L_DB8F:
    phi_db92_0 = msg_no_lord;    // $DB8F
L_DB92:
    return redraw_window(phi_db92_0);    // $DB96
}

// $DB97 assign_unique_daimyo_face_code
// (body @ $DB9C)

word assign_unique_daimyo_face_code(word arg1) {
    *(byte*)((fief_to_daimyo_record_addr(arg1) + 6)) = 1;    // $DBA4
    local8 = 0;    // $DBA6
L_DBA7:
    local10 = ((((rng_mod(5) * 125) + (rng_mod(5) * 25)) + (rng_mod(5) * 5)) + rng_mod(5));    // $DBCC
    local9 = ((scenario_fief_count == 50) ? 53 : 17);    // $DBDD
    local11 = 0;    // $DBDF
    local8 = 1;    // $DBE1
    goto L_DBF6;    // $DBE2
L_DBE5:
    if (!((*(word*)(((local11 << 1) + 0x6EB1)) == local10))) goto L_DBF3;    // $DBEE
    local8 = 0;    // $DBF2
L_DBF3:
    local11 = (local11 + 1);    // $DBF5
L_DBF6:
    if (((unsigned)local11 < (unsigned)local9)) goto L_DBE5;    // $DBF9
    if (!(local8)) goto L_DBA7;    // $DBFD
    *(word*)(((fief_owner(arg1) << 1) + 0x6EB1)) = local10;    // $DC0C
    return local10;    // $DC0D
}

// $DC0E pool_push_pop
// (body @ $DC13)

word pool_push_pop(word arg1) {
    if (!(((unsigned)arg1 > (unsigned)49))) goto L_DC2A;    // $DC17
    daimyo_pool_sp_6e4a = (daimyo_pool_sp_6e4a - 1);    // $DC1E
    return *(byte*)((daimyo_pool_sp_6e4a + 0x6E4B));    // $DC29
L_DC2A:
    daimyo_pool_sp_6e4a = (daimyo_pool_sp_6e4a + 1);    // $DC2E
    daimyo_pool_sp_6e4a[daimyo_pool_sp_6e4a] = arg1;    // $DC3A
    return arg1;    // $DC3B
}

// $DC3C list_remove_matching
// (body @ $DC41)

word list_remove_matching(word arg1) {
    local10 = 0x6E7F;    // $DC44
    local11 = 0;    // $DC46
    goto L_DC5D;    // $DC47
L_DC4A:
    if (!((*(byte*)(local10) == arg1))) goto L_DC55;    // $DC4E
    *(byte*)(local10) = -1;    // $DC54
L_DC55:
    local10 = (local10 + 1);    // $DC57
    local11 = (local11 + 1);    // $DC5B
L_DC5D:
    if (((unsigned)local11 < (unsigned)scenario_fief_count)) goto L_DC4A;    // $DC62
    return ((unsigned)local11 < (unsigned)scenario_fief_count);    // $DC65
}

// $DC66 fief_to_mapid
// (body @ $DC6B)

word fief_to_mapid(word arg1) {
    if (!(((unsigned)arg1 > (unsigned)50))) goto L_DC74;    // $DC6F
    return arg1;    // $DC73
L_DC74:
    dsel_dc87 = (scenario_fief_count == 50);    // $DC87
    return (dsel_dc87 ? arg1 : province_to_mapid_table[arg1]);    // $DC87
}

// $DC88 read_map_cell
// (body @ $DC8D)

word read_map_cell(word arg1, word arg2) {
    syscall16_sram_wrap(4, ((((fief_to_mapid(battle_defending_province) * 55) + (arg2 * 11)) + arg1) + read_map_cell_data_a57e), &cell, 1);    // $DCAA
    return cell;    // $DCB1
}

// $DCB2 generate_daimyo_name
// (body @ $DCB7)

word generate_daimyo_name(word arg1) {
L_DCB7:
    local9 = &name_buf;    // $DCBA
    local11 = (rng_mod(11) << 1);    // $DCC1
    local10 = (rng_mod(11) << 1);    // $DCC8
    *(byte*)(local9) = msg_aiaoieueoikakikusasisusotatuto[local11];    // $DCD0
    local9 = (local9 + 1);    // $DCD3
    local11 = (local11 + 1);    // $DCD7
    *(byte*)((local9 + 1)) = *(byte*)(((local11 + 1) + msg_aiaoieueoikakikusasisusotatuto));    // $DCDD
    local9 = (local9 + 1);    // $DCE0
    *(byte*)((local9 + 1)) = msg_setenohomamimemoyarawagagizaze[local10];    // $DCE8
    local9 = (local9 + 1);    // $DCEB
    local10 = (local10 + 1);    // $DCEF
    *(byte*)((local9 + 1)) = *(byte*)(((local10 + 1) + msg_setenohomamimemoyarawagagizaze));    // $DCF5
    local9 = (local9 + 1);    // $DCF8
    *(byte*)((local9 + 1)) = 0;    // $DCFB
    local8 = 0;    // $DCFD
    phi_val_dd1c = 0;    // $DCFF
    goto L_DD1C;    // $DCFF
L_DD02:
    if (strcmp(&name_buf, ((local11 * 9) + 0x77A8))) goto L_DD1A;    // $DD12
    local8 = 1;    // $DD16
    goto L_DD25;    // $DD17
L_DD1A:
    phi_val_dd1c = (local11 + 1);    // $DD1B
L_DD1C:
    local11 = phi_val_dd1c;    // $DD1C
    if (((unsigned)local11 < (unsigned)scenario_fief_count)) goto L_DD02;    // $DD22
L_DD25:
    if (local8) goto L_DCB7;    // $DD26
    return strcpy(((arg1 * 9) + 0x77A8), &name_buf);    // $DD39
}

// $DD3A filter_province_list_by_owner
// (body @ $DD3F)

word filter_province_list_by_owner(word match_enemy, word out_list) {
    write_ptr = &buf;    // $DD42
    phi_val_dd67 = out_list;    // $DD44
    goto L_DD67;    // $DD44
L_DD47:
    if ((is_enemy_owned(*(byte*)(src_ptr)) ^ match_enemy)) goto L_DD65;    // $DD50
    if (province_state_is_FF(*(byte*)(src_ptr))) goto L_DD65;    // $DD5A
    write_ptr = (write_ptr + 1);    // $DD5F
    *(byte*)(((write_ptr + 1) - 1)) = *(byte*)(src_ptr);    // $DD64
L_DD65:
    phi_val_dd67 = (src_ptr + 1);    // $DD66
L_DD67:
    src_ptr = phi_val_dd67;    // $DD67
    if ((*(byte*)(src_ptr) != 255)) goto L_DD47;    // $DD6E
    *(byte*)(write_ptr) = -1;    // $DD74
    return syscall16_sram_wrap(0, &buf, out_list, 8);    // $DD80
}

// $DD81 init_new_daimyo_province_stats
// (body @ $DD86)

word init_new_daimyo_province_stats(word arg1) {
    *(byte*)(fief_to_daimyo_record_addr(arg1)) = (rng_mod(20) + 20);    // $DD94
    local10 = (fief_to_daimyo_record_addr(arg1) + 1);    // $DD9B
    phi_val_ddc8 = (fief_to_daimyo_record_addr(arg1) + 1);    // $DD9C
    goto L_DDC8;    // $DD9C
L_DD9F:
    *(byte*)(local11) = pct_op(*(byte*)(local11), (rng_mod(20) + 50));    // $DDB0
    *(byte*)(local11) = (*(byte*)(local11) + ((*(byte*)(local11) < 30) ? 30 : 0));    // $DDC5
    phi_val_ddc8 = (local11 + 1);    // $DDC7
L_DDC8:
    local11 = phi_val_ddc8;    // $DDC8
    if (((unsigned)local11 <= (unsigned)(local10 + 4))) goto L_DD9F;    // $DDCF
    local8 = ((arg1 * 26) + 0x7001);    // $DDDA
    phi_val_de45 = ((arg1 * 26) + 0x7001);    // $DDDB
    goto L_DE45;    // $DDDB
L_DDDE:
    if (!((((arg1 * 26) + 0x7017) == local9))) goto L_DE0A;    // $DDE8
    *(word*)(local9) = pct_op(*(word*)(local9), (rng_mod(31) + 50));    // $DDFC
    if (!((*(word*)(local9) < 50))) goto L_DE3B;    // $DE02
    phi_push_de3c = 50;    // $DE07
    goto L_DE3C;    // $DE07
L_DE0A:
    if (!(fief_is_daimyo_capital[arg1])) goto L_DE1F;    // $DE11
    phi_push_de27 = (rng_mod(20) + 50);    // $DE1C
    goto L_DE27;    // $DE1C
L_DE1F:
    phi_push_de27 = (rng_mod(30) + 30);    // $DE25
L_DE27:
    *(word*)(local9) = pct_op(*(word*)(local9), phi_push_de27);    // $DE2F
    if (!((*(word*)(local9) < 10))) goto L_DE3B;    // $DE34
    phi_push_de3c = 10;    // $DE38
    goto L_DE3C;    // $DE38
L_DE3B:
    phi_push_de3c = 0;    // $DE3B
L_DE3C:
    *(word*)(local9) = (*(word*)(local9) + phi_push_de3c);    // $DE42
    phi_val_de45 = (local9 + 2);    // $DE44
L_DE45:
    local9 = phi_val_de45;    // $DE45
    if (((unsigned)local9 < (unsigned)(local8 + 24))) goto L_DDDE;    // $DE4D
    *(word*)(((arg1 * 26) + 0x700D)) = (*(word*)(((arg1 * 26) + 0x700D)) + 50);    // $DE5E
    *(word*)(((arg1 * 26) + 0x7013)) = (*(word*)(((arg1 * 26) + 0x7013)) + 50);    // $DE6D
    fief_tax_rate[arg1] = 20;    // $DE76
    return 20;    // $DE77
}

// $DE78 select_message_string_de78
// (body @ $DE7D)

word select_message_string_de78(word arg1) {
    if (!((ai_turn_flags & 32))) goto L_DE8A;    // $DE83
    return msg_rebels_f72e;    // $DE89
L_DE8A:
    if (!((ai_turn_flags & 16))) goto L_DE97;    // $DE90
    return 0x796A;    // $DE96
L_DE97:
    switch (arg1) {    // $DE98
        case 7: goto L_DEAD;    // $DE98
        case 13: goto L_DEB3;    // $DE98
        case 23: goto L_DEAD;    // $DE98
        case 30: goto L_DEB3;    // $DE98
        default: goto L_DEB9;    // $DE98
    }    // $DE98
L_DEAD:
    phi_val_deb0 = 0xF720;    // $DEAD
L_DEB0:
    local11 = phi_val_deb0;    // $DEB0
    return local11;    // $DEB2
L_DEB3:
    phi_val_deb0 = 0xF728;    // $DEB6
    goto L_DEB0;    // $DEB6
L_DEB9:
    phi_val_deb0 = classify_7b79(arg1);    // $DEBE
    goto L_DEB0;    // $DEBE
}

// $DEC1 reassign_fiefs_to_conqueror
// (body @ $DEC6)

word reassign_fiefs_to_conqueror(void) {
    local8 = ((battle_winner_province_sel == battle_defending_province) ? selected_province_idx : battle_defending_province);    // $DED9
    local10 = fief_owner(((battle_winner_province_sel == battle_defending_province) ? selected_province_idx : battle_defending_province));    // $DEDF
    local9 = fief_owner(battle_winner_province_sel);    // $DEE7
    pool_push_pop(fief_owner(battle_winner_province_sel));    // $DEE9
    list_remove_matching(local9);    // $DEEE
    phi_val_df33 = 0;    // $DEF3
    goto L_DF33;    // $DEF3
L_DEF6:
    if (!((fief_owner(local11) == local9))) goto L_DF31;    // $DEFD
    if (province_state_is_FF(local11)) goto L_DF31;    // $DF05
    fief_to_daimyo_map[local11] = local10;    // $DF0F
    fief_is_daimyo_capital[local11] = 0;    // $DF17
    province_ai_state[local11] = (get_province_ai_state(local8) ? 5 : 0);    // $DF2B
L_DF31:
    find_record_9e3c(local11);    // $DF2D
    phi_val_df33 = (local11 + 1);    // $DF32
L_DF33:
    local11 = phi_val_df33;    // $DF33
    if (((unsigned)local11 < (unsigned)scenario_fief_count)) goto L_DEF6;    // $DF39
    return ((unsigned)local11 < (unsigned)scenario_fief_count);    // $DF3C
}

// $DF3D daimyo_stat_transfer
// (body @ $DF42)

word daimyo_stat_transfer(word arg1, word arg2) {
    local11 = fief_to_daimyo_record_addr(arg1);    // $DF47
    *(byte*)((local11 + 2)) = (*(byte*)((local11 + 2)) + 1);    // $DF4D
    *(byte*)((local11 + 4)) = (*(byte*)((local11 + 4)) + 1);    // $DF53
    *(byte*)((local11 + 5)) = (*(byte*)((local11 + 5)) + 1);    // $DF59
    local11 = fief_to_daimyo_record_addr(arg2);    // $DF5F
    *(byte*)((local11 + 2)) = (*(byte*)((local11 + 2)) - 1);    // $DF65
    *(byte*)((local11 + 4)) = (*(byte*)((local11 + 4)) - 1);    // $DF6B
    *(byte*)((local11 + 5)) = (*(byte*)((local11 + 5)) - 1);    // $DF71
    return (*(byte*)((local11 + 5)) - 1);    // $DF72
}

// $DF73 transfer_force_triplet
// (body @ $DF78)

word transfer_force_triplet(void) {
    local9 = ((selected_province_idx * 26) + 0x7013);    // $DF82
    local10 = ((battle_defending_province * 26) + 0x7013);    // $DF8D
    local11 = *(word*)((local10 + 6));    // $DF91
    local8 = 0;    // $DF93
L_DF94:
    *(word*)(local10) = scaled_transfer_da24(*(word*)(local10), *(word*)(local9), war_attacker_men, war_defender_men, local11);    // $DFA6
    local8 = (local8 + 1);    // $DFA9
    local10 = (local10 + 2);    // $DFAD
    local9 = (local9 + 2);    // $DFB2
    if (((unsigned)local8 < (unsigned)3)) goto L_DF94;    // $DFB8
    return ((unsigned)local8 < (unsigned)3);    // $DFBB
}

// $DFBC clamp_field_6d2d_to_30
// (body @ $DFC1)

word clamp_field_6d2d_to_30(void) {
    local11 = battle_defending_province;    // $DFC4
    phi_val_dfec = 0;    // $DFC6
    goto L_DFEC;    // $DFC6
L_DFC9:
    if (!(defender_owner_is_keyed_daimyo())) goto L_DFE8;    // $DFCC
    if ((fief_tax_rate[battle_defending_province] <= 30)) goto L_DFE8;    // $DFDA
    fief_tax_rate[battle_defending_province] = 30;    // $DFE7
L_DFE8:
    phi_val_dfec = (battle_defending_province + 1);    // $DFEB
L_DFEC:
    battle_defending_province = phi_val_dfec;    // $DFEC
    if (((unsigned)battle_defending_province < (unsigned)scenario_fief_count)) goto L_DFC9;    // $DFF6
    battle_defending_province = local11;    // $DFFA
    return local11;    // $DFFD
}

// $DFFE cap_arms_at_index
// (body @ $E003)

word cap_arms_at_index(word arg1, word arg2) {
    local11 = ((arg2->arms / 50) + 20);    // $E00C
    phi_ret_e03b = ((unsigned)*(byte*)(((arg1 * 5) + 0x76AB)) > (unsigned)local11);    // $E017
    if (!(phi_ret_e03b)) goto L_E03B;    // $E017
    *(byte*)(((arg1 * 5) + 0x76A9)) = (*(byte*)(((arg1 * 5) + 0x76A9)) + (*(byte*)(((arg1 * 5) + 0x76AB)) - local11));    // $E030
    *(byte*)(((arg1 * 5) + 0x76AB)) = local11;    // $E03A
    phi_ret_e03b = local11;    // $E03A
L_E03B:
    return phi_ret_e03b;    // $E03B
}

// $E03C apply_conquest_outcome
// (body @ $E041)

word apply_conquest_outcome(void) {
    cap_fief_stats(battle_defending_province);    // $E044
    local6 = ((battle_defending_province * 26) + 0x7001);    // $E052
    local8 = (selected_province_idx == 50);    // $E059
    local9 = (battle_winner_province_sel == battle_defending_province);    // $E061
    if (!(local9)) goto L_E080;    // $E063
L_E080:
    syscall16_sram_wrap(4, ((selected_province_idx * 5) + 0x76A9), ((battle_defending_province * 5) + 0x76A9), 5);    // $E07C
    if (local8) goto L_E0A6;    // $E081
    transfer_force_triplet();    // $E084
    cap_arms_at_index(battle_defending_province, local6);    // $E08B
    if (!(local9)) goto L_E09C;    // $E090
    phi_e0a2_0 = selected_province_idx;    // $E099
    phi_e0a2_1 = battle_defending_province;    // $E099
    goto L_E0A2;    // $E099
L_E09C:
    phi_e0a2_0 = battle_defending_province;    // $E09F
    phi_e0a2_1 = selected_province_idx;    // $E09F
L_E0A2:
L_E0A6:
    daimyo_stat_transfer(phi_e0a2_0, phi_e0a2_1);    // $E0A2
    if (!(((ai_turn_flags & 32) || !(local8)))) goto L_E0B7;    // $E0B0
    phi_val_e0b8 = 0;    // $E0B4
    goto L_E0B8;    // $E0B4
L_E0B7:
    phi_val_e0b8 = 1;    // $E0B7
L_E0B8:
    local7 = phi_val_e0b8;    // $E0B8
    if (!(local7)) goto L_E0CB;    // $E0BA
    if (local9) goto L_E0CB;    // $E0BE
    war_attacker_men = 0;    // $E0C2
    war_attacker_rice = 0;    // $E0C5
    war_attacker_gold = 0;    // $E0C8
L_E0CB:
    *(word*)(local6) = (war_attacker_gold + war_defender_gold);    // $E0D3
    *(word*)((local6 + 6)) = (war_attacker_rice + war_defender_rice);    // $E0DE
    *(word*)((local6 + 16)) = (war_attacker_men + war_defender_men);    // $E0EA
    if (!(local7)) goto L_E106;    // $E0EC
    *(word*)((local6 + 8)) = (*(word*)((local6 + 8)) - pct_op(*(word*)((local6 + 8)), (rng_mod(10) + 10)));    // $E105
L_E106:
    local10 = (battle_defending_province + 0x6E15);    // $E10D
    if (local8) goto L_E120;    // $E10F
    if (!(test_6f65_bit7(local9))) goto L_E120;    // $E117
    reassign_fiefs_to_conqueror();    // $E11A
    goto L_E19C;    // $E11D
L_E120:
    if (!(local9)) goto L_E19C;    // $E121
    if (!(local8)) goto L_E178;    // $E125
    if (!(fief_is_daimyo_capital[battle_defending_province])) goto L_E16E;    // $E130
    pool_push_pop(*(byte*)(local10));    // $E136
    list_remove_matching(*(byte*)(local10));    // $E13D
    phi_val_e165 = 0;    // $E142
    goto L_E165;    // $E142
L_E145:
    if (!((fief_owner(local11) == *(byte*)(local10)))) goto L_E163;    // $E14F
    if ((local11 == battle_defending_province)) goto L_E163;    // $E157
    *(byte*)(province_ai_state_addr(local11)) = -1;    // $E162
L_E163:
    phi_val_e165 = (local11 + 1);    // $E164
L_E165:
    local11 = phi_val_e165;    // $E165
    if (((unsigned)local11 < (unsigned)scenario_fief_count)) goto L_E145;    // $E16B
L_E16E:
    install_new_daimyo(battle_defending_province);    // $E171
    goto L_E19C;    // $E175
L_E178:
    *(byte*)(local10) = selected_province_owner();    // $E17C
    *(byte*)(province_ai_state_addr(battle_defending_province)) = (get_province_ai_state(selected_province_idx) ? 5 : 0);    // $E194
L_E19C:
    find_record_9e3c(battle_defending_province);    // $E198
    if (local8) goto L_E1C7;    // $E19D
    if (!(local9)) goto L_E1C7;    // $E1A1
    fief_is_daimyo_capital[battle_defending_province] = (war_side_state_flag >> 7);    // $E1B1
    fief_is_daimyo_capital[selected_province_idx] = (fief_is_daimyo_capital[selected_province_idx] ^ fief_is_daimyo_capital[battle_defending_province]);    // $E1C6
L_E1C7:
    ai_turn_flags = (ai_turn_flags & -113);    // $E1CE
    clamp_field_6d2d_to_30();    // $E1D1
    cap_fief_stats(battle_defending_province);    // $E1D7
    phi_ret_e1e6 = local8;    // $E1DC
    if (phi_ret_e1e6) goto L_E1E6;    // $E1DC
    phi_ret_e1e6 = cap_fief_stats(selected_province_idx);    // $E1E2
L_E1E6:
    return phi_ret_e1e6;    // $E1E6
}

// $E1E7 clear_fief_pair_6193
// (body @ $E1EC)

word clear_fief_pair_6193(word arg1) {
    call_bank10_entry(29);    // $E1EE
    phi_val_e211 = 0;    // $E1F3
    goto L_E211;    // $E1F3
L_E1F6:
    *(byte*)((((local11 * 54) + arg1) + 0x6193)) = 0;    // $E20D
    *(byte*)((((arg1 * 54) + local11) + 0x6193)) = 0;    // $E20E
    phi_val_e211 = (local11 + 1);    // $E210
L_E211:
    local11 = phi_val_e211;    // $E211
    if (((unsigned)local11 < (unsigned)scenario_fief_count)) goto L_E1F6;    // $E217
    return ((unsigned)local11 < (unsigned)scenario_fief_count);    // $E21A
}

// $E21B install_new_daimyo
// (body @ $E220)

word install_new_daimyo(word arg1) {
    fief_to_daimyo_map[arg1] = pool_push_pop(255);    // $E22D
    generate_daimyo_name(fief_owner(arg1));    // $E234
    message_display(((fief_owner(arg1) * 9) + 0x77A8));    // $E244
    draw_message(msg_is_now_fief_2d_s_daimyo, (arg1 + 1));    // $E24E
    province_ai_state[arg1] = 0;    // $E259
    fief_is_daimyo_capital[arg1] = 1;    // $E261
    init_new_daimyo_province_stats(arg1);    // $E263
    assign_unique_daimyo_face_code(arg1);    // $E268
    find_record_9e3c(arg1);    // $E26D
    return confirm_prompt();    // $E274
}

// $E275 prompt_helper_e275
// (body @ $E27A)

word prompt_helper_e275(word arg1) {
    clear_fief_pair_6193(arg1);    // $E27B
    message_display(((fief_owner(arg1) * 9) + 0x77A8));    // $E28B
    redraw_window(msg_was_killed);    // $E292
    if (!(get_province_ai_state(arg1))) goto L_E2AB;    // $E29B
L_E2AB:
    draw_message(msg_in_fief_2d_in_the_year_d, (arg1 + 1), current_game_year);    // $E2A7
    return confirm_prompt();    // $E2AE
}

// $E2AF copy_arms_record_5
// (body @ $E2B4)

word copy_arms_record_5(word arg1, word arg2) {
    local10 = 0;    // $E2B5
    local11 = ((arg1 * 5) + 0x76A9);    // $E2BD
    goto L_E2CF;    // $E2BE
L_E2C1:
    local11 = (local11 + 1);    // $E2C3
    arg2 = (arg2 + 1);    // $E2C8
    *(byte*)(((local11 + 1) - 1)) = *(byte*)(((arg2 + 1) - 1));    // $E2CB
    local10 = (local10 + 1);    // $E2CE
L_E2CF:
    if (((unsigned)local10 < (unsigned)5)) goto L_E2C1;    // $E2D2
    return ((unsigned)local10 < (unsigned)5);    // $E2D5
}

// $E2D6 draw_daimyo_name_menu
// (body @ $E2DB)

word draw_daimyo_name_menu(word arg1) {
    open_message_window();    // $E2DB
    message_display(msg_lord_f777);    // $E2E1
    redraw_window(((fief_owner(battle_defending_province) * 9) + 0x77A8));    // $E2F3
    redraw_window(draw_daimyo_name_menu_data_f77d);    // $E2FA
    redraw_window(((selected_province_owner() * 9) + 0x77A8));    // $E308
    return draw_message(msg_wants_a_s, arg1);    // $E314
}

// $E315 marry_helper_e315
// (body @ $E31A)

word marry_helper_e315(void) {
    if (!(get_province_ai_state(battle_defending_province))) goto L_E361;    // $E321
    local9 = ui_input_mode;    // $E327
    ui_input_mode = 2;    // $E329
    draw_daimyo_name_menu(msg_marriage_pact);    // $E32F
    redraw_window(msg_accept);    // $E336
    if (!(prompt_y_n())) goto L_E359;    // $E33D
    message_display(msg_demand_gold);    // $E343
    local11 = number_input(1, 0x270F);    // $E34F
    if (number_input(1, 0x270F)) goto L_E35B;    // $E350
    open_message_window();    // $E353
    goto L_E35B;    // $E356
L_E359:
    local11 = 0;    // $E35A
L_E35B:
    ui_input_mode = local9;    // $E35C
    return local11;    // $E360
L_E361:
    if (rng_mod(const_two)) goto L_E3A2;    // $E368
    if (!(fief_owner_weakness(selected_province_idx))) goto L_E37D;    // $E372
    if (rng_mod(3)) goto L_E3A2;    // $E37A
L_E37D:
    local10 = *(word*)(((selected_province_idx * 26) + 0x7001));    // $E388
    if (!((*(word*)(((selected_province_idx * 26) + 0x7001)) > 200))) goto L_E3A2;    // $E38D
    return (pct_op(local10, (rng_mod(30) + 50)) + 200);    // $E3A1
L_E3A2:
    return 0;    // $E3A3
}

// $E3A4 diplomacy_helper
// (body @ $E3A9)

word diplomacy_helper(void) {
    if (!(get_province_ai_state(battle_defending_province))) goto L_E3DE;    // $E3B0
    local9 = ui_input_mode;    // $E3B6
    ui_input_mode = 2;    // $E3B8
    draw_daimyo_name_menu(msg_pact);    // $E3BE
    redraw_window(msg_demand_gold);    // $E3C5
    local11 = number_input(1, 0x270F);    // $E3D1
    if (number_input(1, 0x270F)) goto L_E3D8;    // $E3D2
L_E3D8:
    open_message_window();    // $E3D5
    ui_input_mode = local9;    // $E3D9
    return local11;    // $E3DD
L_E3DE:
    if (!(fief_owner_weakness(selected_province_idx))) goto L_E3F0;    // $E3E5
    if (rng_mod(3)) goto L_E423;    // $E3ED
L_E3F0:
    local10 = *(word*)(((selected_province_idx * 26) + 0x7001));    // $E3FB
    if (rng_mod(const_two)) goto L_E421;    // $E403
    phi_ret_e422 = ((pct_op(local10, 50) + pct_op(local10, rng_mod(50))) + 20);    // $E41E
    goto L_E422;    // $E41E
L_E421:
    phi_ret_e422 = 0;    // $E421
L_E422:
    return phi_ret_e422;    // $E422
L_E423:
    return 0;    // $E424
}

// $E425 find_fiefs_of_owner
// (body @ $E42A)

word find_fiefs_of_owner(word arg1) {
    arg1 = fief_owner(arg1);    // $E42F
    list_remove_matching(arg1);    // $E431
    phi_val_e44a = 0;    // $E436
    goto L_E44A;    // $E436
L_E439:
    if (!((fief_owner(local11) == arg1))) goto L_E448;    // $E440
L_E448:
    neutralize_fief(local11);    // $E444
    phi_val_e44a = (local11 + 1);    // $E449
L_E44A:
    local11 = phi_val_e44a;    // $E44A
    if (((unsigned)local11 < (unsigned)scenario_fief_count)) goto L_E439;    // $E450
    return ((unsigned)local11 < (unsigned)scenario_fief_count);    // $E453
}

// $E454 neutralize_fief
// (body @ $E459)

word neutralize_fief(word arg1) {
    phi_ret_e4a1 = (province_ai_state[arg1] != 255);    // $E463
    if (!(phi_ret_e4a1)) goto L_E4A1;    // $E463
    message_display(msg_fief_f7b2);    // $E469
    draw_message(msg_d_lost_its_leader, (arg1 + 1));    // $E473
    confirm_prompt();    // $E477
    province_ai_state[arg1] = -1;    // $E482
    fief_is_daimyo_capital[arg1] = 0;    // $E48A
    fief_tax_rate[arg1] = 20;    // $E493
    copy_arms_record_5(arg1, 0x77A3);    // $E498
    phi_ret_e4a1 = find_record_9e3c(arg1);    // $E49D
L_E4A1:
    return phi_ret_e4a1;    // $E4A1
}

// $E4A2 build_owned_fief_list_6f89
// (body @ $E4A7)

word build_owned_fief_list_6f89(void) {
    saved_fief = selected_province_idx;    // $E4AA
    write_ptr = 0x6F89;    // $E4AE
    phi_val_e4c6 = 0;    // $E4B0
    goto L_E4C6;    // $E4B0
L_E4B3:
    if (!(get_6da2_cur())) goto L_E4C2;    // $E4B6
    write_ptr = (write_ptr + 1);    // $E4BB
    *(byte*)(((write_ptr + 1) - 1)) = selected_province_idx;    // $E4C1
L_E4C2:
    phi_val_e4c6 = (selected_province_idx + 1);    // $E4C5
L_E4C6:
    selected_province_idx = phi_val_e4c6;    // $E4C6
    if (((unsigned)selected_province_idx < (unsigned)scenario_fief_count)) goto L_E4B3;    // $E4D0
    *(byte*)(write_ptr) = -1;    // $E4D6
    selected_province_idx = saved_fief;    // $E4D8
    return saved_fief;    // $E4DB
}

// $E4DC marry_helper_e4dc
// (body @ $E4E1)

word marry_helper_e4dc(word arg1) {
    build_owned_fief_list_6f89();    // $E4E1
    local10 = 0x6F89;    // $E4E7
    phi_val_e501 = 0x6F89;    // $E4E8
    goto L_E501;    // $E4E8
L_E4EB:
    if (!((fief_owner(*(byte*)(local11)) != arg1))) goto L_E4FF;    // $E4F4
    local10 = (local10 + 1);    // $E4F9
    *(byte*)(((local10 + 1) - 1)) = *(byte*)(local11);    // $E4FE
L_E4FF:
    phi_val_e501 = (local11 + 1);    // $E500
L_E501:
    local11 = phi_val_e501;    // $E501
    if ((*(byte*)(local11) != 255)) goto L_E4EB;    // $E508
    *(byte*)(local10) = -1;    // $E50E
    return -1;    // $E50F
}

// $E510 build_eligible_province_list
// (body @ $E515)

word build_eligible_province_list(word arg1) {
    local9 = 0x6F89;    // $E518
    local10 = 0;    // $E51A
    phi_val_e545 = 0;    // $E51C
    goto L_E545;    // $E51C
L_E51F:
    if (province_state_is_FF(local11)) goto L_E543;    // $E524
    if ((is_enemy_owned(local11) ^ arg1)) goto L_E543;    // $E52E
    if ((selected_province_idx == local11)) goto L_E543;    // $E536
    local9 = (local9 + 1);    // $E53B
    *(byte*)(((local9 + 1) - 1)) = local11;    // $E53F
    local10 = (local10 + 1);    // $E542
L_E543:
    phi_val_e545 = (local11 + 1);    // $E544
L_E545:
    local11 = phi_val_e545;    // $E545
    if (((unsigned)local11 < (unsigned)scenario_fief_count)) goto L_E51F;    // $E54B
    *(byte*)(local9) = -1;    // $E551
    return local10;    // $E553
}

// $E554 find_record_9e3c
// (body @ $E559)

word find_record_9e3c(word arg1) {
    phi_ret_e594 = ((unsigned)selected_record_idx_9e3c <= (unsigned)8);    // $E55E
    if (!(phi_ret_e594)) goto L_E594;    // $E55E
    local11 = ui_window_col;    // $E564
    local10 = ui_cursor_row;    // $E568
    syscall16_sram_wrap(4, ((selected_record_idx_9e3c * 34) + find_record_data_9e3c), &record_buf, 34);    // $E57B
    rec_cursor = &record_buf;    // $E582
L_E584:
    if ((*(byte*)(rec_cursor) != 255)) goto L_E595;    // $E58B
L_E58E:
    phi_ret_e594 = set_cursor(local11, local10);    // $E590
L_E594:
    return phi_ret_e594;    // $E594
L_E595:
    rec_cursor = (rec_cursor + 1);    // $E598
    ui_window_col = *(byte*)(((rec_cursor + 1) - 1));    // $E59C
    rec_cursor = (rec_cursor + 1);    // $E5A2
    ui_cursor_row = *(byte*)(((rec_cursor + 1) - 1));    // $E5A6
    rec_cursor = (rec_cursor + 1);    // $E5AC
    if (!((*(byte*)(((rec_cursor + 1) - 1)) == arg1))) goto L_E584;    // $E5B2
    ppu_copy_rect_wrap(ui_window_col, ui_cursor_row, min_word((ui_window_col + 8), 29), ui_cursor_row, ((((selected_record_idx_9e3c * 0x01C0) + ((ui_cursor_row + -4) * 28)) + ui_window_col) + find_record_data_8d5a), 4);    // $E5E6
    draw_province_lord_name(arg1);    // $E5EB
    goto L_E58E;    // $E5EF
}

// $E5F2 map_helper_e5f2
// (body @ $E5F7)

word map_helper_e5f2(word arg1) {
    phi_ret_e693 = (arg1 != selected_record_idx_9e3c);    // $E5FC
    if (!(phi_ret_e693)) goto L_E693;    // $E5FC
    palette_swap(1);    // $E600
    ppu_fill_rect_wrap(30, 4, 31, 19, 1);    // $E60C
    ppu_copy_rect_wrap(2, 4, 29, 19, ((arg1 * 0x01C0) + strategic_map_section_tilemaps), 4);    // $E621
    ppu_upload_block_wrap(4, ((arg1 << 5) + strategic_map_section_attributes), 0x23C8, 2);    // $E632
    selected_record_idx_9e3c = arg1;    // $E637
    local11 = ui_window_col;    // $E63D
    local10 = ui_cursor_row;    // $E641
    syscall16_sram_wrap(4, ((arg1 * 34) + find_record_data_9e3c), &record_buf, 34);    // $E652
    cursor = &record_buf;    // $E659
    goto L_E67E;    // $E65B
L_E65E:
    cursor = (cursor + 1);    // $E661
    ui_window_col = *(byte*)(((cursor + 1) - 1));    // $E665
    cursor = (cursor + 1);    // $E66B
    ui_cursor_row = *(byte*)(((cursor + 1) - 1));    // $E66F
    cursor = (cursor + 1);    // $E675
L_E67E:
    draw_province_lord_name(*(byte*)(((cursor + 1) - 1)));    // $E67A
    if ((*(byte*)(cursor) != 255)) goto L_E65E;    // $E685
    set_cursor(local11, local10);    // $E68A
    phi_ret_e693 = palette_swap(0);    // $E68F
L_E693:
    return phi_ret_e693;    // $E693
}

// $E694 dispatch_map_helper_e694
// (body @ $E699)

word dispatch_map_helper_e694(void) {
    return map_helper_e5f2(*(byte*)((selected_province_idx_latch_7fdd + ((scenario_fief_count == 50) ? province_to_map_section_50 : province_to_map_section_17))));    // $E6B8
}

// $E6B9 unpack_composite_face_record
// (body @ $E6BE)

word unpack_composite_face_record(word dst_buf) {
    face_code = *(word*)(((active_province_idx_copy << 1) + 0x6EB1));    // $E6C7
    part_nose = ((unsigned)face_code / (unsigned)5);    // $E6CB
    part_face = ((unsigned)face_code % (unsigned)5);    // $E6CF
    part_eyes = ((unsigned)part_nose / (unsigned)5);    // $E6D3
    part_nose = ((unsigned)part_nose % (unsigned)5);    // $E6D7
    part_hair = ((unsigned)part_eyes / (unsigned)5);    // $E6DB
    part_eyes = ((unsigned)part_eyes % (unsigned)5);    // $E6DF
    ppu_upload_block_wrap(8, ((part_face * 192) + unpack_record_to_sram_data_a604), 0x15B0, 12);    // $E6EF
    ppu_upload_block_wrap(8, ((part_nose * 96) + 0xA9C4), 0x1670, 6);    // $E701
    ppu_upload_block_wrap(8, ((part_eyes * 96) + unpack_record_to_sram_data_aba4), 0x16D0, 6);    // $E713
    ppu_upload_block_wrap(8, ((part_hair * 192) + unpack_record_to_sram_data_ad84), 0x1730, 12);    // $E726
    syscall16_sram_wrap(9, ((part_face * 12) + unpack_record_to_sram_data_ae34), dst_buf, 12);    // $E735
    syscall16_sram_wrap(9, ((part_nose * 6) + unpack_record_to_sram_data_ae70), (dst_buf + 12), 6);    // $E746
    syscall16_sram_wrap(9, ((part_eyes * 6) + unpack_record_to_sram_data_ae8e), (dst_buf + 18), 6);    // $E758
    return syscall16_sram_wrap(9, ((part_hair * 12) + unpack_record_to_sram_data_aeac), (dst_buf + 24), 12);    // $E76E
}

// $E76F draw_daimyo_portrait
// (body @ $E774)

word draw_daimyo_portrait(word col, word row) {
    pal_idx = 0;    // $E775
L_E777:
    palette_write_wrap(pal_idx, *(word*)(((pal_idx << 1) + marry_helper_data_f7cc)));    // $E782
    pal_idx = (pal_idx + 1);    // $E789
    if (((unsigned)pal_idx < (unsigned)4)) goto L_E777;    // $E78F
    if (((unsigned)active_province_idx_copy >= (unsigned)53)) goto L_E7A7;    // $E798
    if (*(byte*)((daimyo_record_addr(active_province_idx_copy) + 6))) goto L_E7EE;    // $E7A4
L_E7A7:
    descriptor_ptr = (((fief_to_mapid(active_province_idx_copy) << 1) << 1) + msg_ng_to_pieces);    // $E7B4
    syscall16_sram_wrap(8, descriptor_ptr, &descriptor_buf, 4);    // $E7BE
    descriptor_ptr = &descriptor_buf;    // $E7C5
    ppu_upload_block_wrap(*(byte*)(descriptor_ptr), *(word*)((descriptor_ptr + 2)), 0x15B0, *(byte*)((descriptor_ptr + 1)));    // $E7D8
    phi_push_e7fa = ((fief_to_mapid(active_province_idx_copy) * 36) + jumptab_b144);    // $E7EB
    goto L_E7FA;    // $E7EB
L_E7EE:
    unpack_composite_face_record(&face_buf);    // $E7F2
    phi_push_e7fa = &face_buf;    // $E7F7
L_E7FA:
    ppu_copy_rect_wrap(col, row, (col + 5), (row + 5), phi_push_e7fa, 8);    // $E803
    ui_pending_flag_7fc7 = 1;    // $E808
    return 1;    // $E80B
}

// $E80C trigger_cutscene
// (body @ $E811)

word trigger_cutscene(word arg1) {
    phi_ret_e822 = (ai_turn_flags & 4);    // $E816
    if (!(phi_ret_e822)) goto L_E822;    // $E816
    cutscene_id = arg1;    // $E81A
    phi_ret_e822 = call_bank_wrap(14);    // $E81E
L_E822:
    return phi_ret_e822;    // $E822
}

