// ============================================================
// source/3-c-basic/bank_10.raw.c  —  GENERATED by `python -m na1dream.cli.decompile_all`  (BASIC: bytecode -> direct goto-infused C, the intermediary form the structure engine folds; the CFG-equivalence reference for bank_10.c)
// 1 bytecode subroutines from bank 10 of Nobunaga's Ambition (USA).nes
// Deterministic (fixed ROM -> identical C). DO NOT hand-edit — regenerate via the tool.
// Pipeline: vm-disasm.py (execution-validated lengths) -> vm_decompile.py (opcode-keyed) — NO structuring: the direct goto/label form.
// ============================================================

// $8003 play_audio_by_id
// (body @ $8008)

word play_audio_by_id(void) {
    phi_ret_808e = (audio_wait_gate == 1);    // $800D
    if (!(phi_ret_808e)) goto L_808E;    // $800D
    if (!(((unsigned)sound_request_id > (unsigned)64))) goto L_801A;    // $8016
    return ((unsigned)sound_request_id > (unsigned)64);    // $8019
L_801A:
    if (!(((unsigned)sound_request_id < (unsigned)27))) goto L_8070;    // $8020
    local11 = (sound_request_id * 3);    // $8028
    syscall_audio_load_voice(1, 10, *(word*)(((local11 << 1) + 0x8617)));    // $8034
    syscall_audio_load_voice(2, 10, *(word*)((((local11 + 1) << 1) + 0x8617)));    // $8044
    syscall_audio_load_voice(3, 10, *(word*)((((local11 + 2) << 1) + 0x8617)));    // $8054
    syscall_audio_control(1, 1);    // $805B
    syscall_audio_control(2, 1);    // $8062
    phi_ret_808e = syscall_audio_control(3, 1);    // $806D
    goto L_808E;    // $806D
L_8070:
    local9 = *(word*)(((sound_request_id << 1) + 0x8617));    // $8079
    local10 = (*(byte*)(local9) & 4);    // $807E
    syscall_audio_load_voice(local10, 10, local9);    // $8083
    phi_ret_808e = syscall_audio_control(local10, 1);    // $808A
L_808E:
    return phi_ret_808e;    // $808E
}

