// ============================================================
// decompiled/bank_00.c  —  GENERATED by tools/decompile-all.py
// 98 bytecode subroutines from bank 0 of Nobunaga's Ambition (USA).nes
// Deterministic (fixed ROM -> identical C). DO NOT hand-edit — regenerate via the tool.
// Pipeline: vm-disasm.py (v2, execution-validated lengths) -> vm_decompile.py (opcode-keyed).
// ============================================================

// $8003 display_fullscreen_graphic_sequence
// (body @ $8008)

word display_fullscreen_graphic_sequence(word arg1, word arg2, word arg3, word arg4) {
    if (count_6da2_set()) {    // $8015
    local11 = 0;    // $8051
L_8052:
    local11 = 0xB7CA;    // $8059
    local11 = (local11 + 1);    // $8060
    if (((unsigned)local11 >= (unsigned)8)) goto L_8052;    // $8064
    if (mem_6F4D) goto L_80B8;    // $8093
L_8099:
L_80A3:
    if (syscall_dispatch(0, 6)) goto L_80A3;    // $80A9
    if (!(syscall_dispatch(1, 6))) goto L_80C5;    // $80B2
    goto L_80A3;    // $80B5
L_80B8:
    if (!(syscall_dispatch(2, 1, 10))) goto L_8099;    // $80BF
    goto L_80B8;    // $80C2
L_80C5:
    if (syscall_dispatch(0, 6)) goto L_80D7;    // $80CB
    if (!(syscall_dispatch(1, 6))) goto L_80C5;    // $80D4
L_80D7:
    local11 = 0;    // $8103
L_8104:
    local11 = 0xB7D2;    // $810B
    local11 = (local11 + 1);    // $8112
    if (((unsigned)local11 >= (unsigned)4)) goto L_8104;    // $8116
    } else {
    local9 = 0;    // $8130
L_8131:
    local11 = 0;    // $8132
L_8133:
    local11 = 4;    // $8133
    if (!(((local11 & 15) == 12))) goto L_814C;    // $8144
    local11 = local11;    // $814B
L_814C:
    local11 = (local11 + 1);    // $814E
    if (((unsigned)local11 >= (unsigned)64)) goto L_8133;    // $8153
    local9 = (local9 + 1);    // $8158
    if (((unsigned)local9 >= (unsigned)6)) goto L_8131;    // $815C
    if (!(mem_6F4D)) goto L_816F;    // $8162
L_8165:
    if (syscall_dispatch(2, 1, 10)) goto L_8165;    // $816C
L_816F:
    local11 = 0;    // $819B
L_819C:
    local11 = 0xB7D6;    // $81A3
    local11 = (local11 + 1);    // $81AA
    if (((unsigned)local11 >= (unsigned)4)) goto L_819C;    // $81AE
    }
L_81B1:
L_81C5:
    if (syscall_dispatch(0, 6)) goto L_81C5;    // $81CB
    if (syscall_dispatch(1, 6)) goto L_81C5;    // $81D4
L_81D7:
    if (syscall_dispatch(0, 6)) goto L_81E9;    // $81DD
    if (!(syscall_dispatch(1, 6))) goto L_81D7;    // $81E6
L_81E9:
    if (ui_helper_d3a7()) goto L_821D;    // $8210
L_821A:
    goto L_821A;    // $821A
L_821D:
    return message_display(0xB83E);    // $821D
    }
}

// $821E verify_sram_save_integrity
// (body @ $8223)

word verify_sram_save_integrity(word arg1, word arg2, word arg3, word arg4) {
    goto L_8235;    // $8223
L_8226:
L_8235:
    if (!(!(ui_helper_d3a7()))) return 0;    // $823F
    if (strcmp(0xB88B, 0x7FED)) goto L_8226;    // $8253
    local8 = syscall_dispatch(0x00FF, 0x6001, 0, 1, 22);    // $8269
    local11 = 0x6100;    // $826D
L_826E:
    local11 = ?;    // $8271
    local8 = (local8 + syscall_dispatch(/*stack underflow*/ regA, 0x0100, 0, 1, 22));    // $827D
    local11 = (local11 + 0x0100);    // $8284
    if (((unsigned)local11 >= (unsigned)0x7000)) goto L_826E;    // $828A
    local8 = (local8 + syscall_dispatch(0x00FF, province_table_live, 0, 1, 22));    // $829E
    local11 = 0x7100;    // $82A2
L_82A3:
    local11 = syscall_dispatch(0x00FF, province_table_live, 0, 1, 22);    // $82A6
    local8 = (local8 + syscall_dispatch(/*stack underflow*/ regA, 0x0100, 0, 1, 22));    // $82B2
    local11 = (local11 + 0x0100);    // $82B9
    if (((unsigned)local11 >= (unsigned)0x7F00)) goto L_82A3;    // $82BF
    local8 = (local8 + syscall_dispatch(0x81EB, ui_transient_state, 0, 1, 22));    // $82D3
    if ((mem_7FEB == local8)) {    // $82DE
    local9 = 0;    // $8322
L_8323:
    local9 = 0xB852;    // $832A
    local9 = (local9 + 1);    // $8331
    if (((unsigned)local9 >= (unsigned)8)) goto L_8323;    // $8335
    return 0;    // $8342
    }
L_8343:
    goto L_8235;    // $8374
}

// $8377 transfer_arms_field_pct
// (body @ $837C)

word transfer_arms_field_pct(word arg1, word arg2, word arg3, word arg4) {
    arg3 = ?;    // $837C
    *(byte*)(fp - 1) = pct_op(/*via arg3*/ ?, *(byte*)(arg2));    // $8384
    *(byte*)(arg1) = (*(byte*)(arg1) + *(byte*)(fp - 1));    // $838F
    *(byte*)(arg2) = (*(byte*)(arg2) - *(byte*)(fp - 1));    // $8398
    return (*(byte*)(arg2) - *(byte*)(fp - 1));    // $8399
}

// $839A init_daimyo_arms_record
// (body @ $839F)

word init_daimyo_arms_record(word arg1, word arg2, word arg3, word arg4) {
    local11 = ((arg1 * 5) + 0x76A9);    // $83A6
    local11 = 0x76A9;    // $83AC
    local11 = 0x76A9;    // $83BD
    return transfer_arms_field_pct((rng_mod(20) + 20), (local11 + 3), (local11 + 1));    // $83E1
}

// $83E2 apply_scenario_starting_stat_boosts
// (body @ $83E7)

word apply_scenario_starting_stat_boosts(word arg1, word arg2, word arg3, word arg4) {
    local11 = 0;    // $83F2
    local9 = 0;    // $83F3
    goto L_85B4;    // $83F4
L_83F7:
    local11 = ?;    // $83F7
    if (get_province_ai_state(/*stack underflow*/ regA)) goto L_8593;    // $83FC
    local11 = ?;    // $83FF
    *(word*)(fp - 40) = ((ui_helper_d772(/*stack underflow*/ regA) * 7) + 0x7530);    // $840A
    goto L_8423;    // $840D
L_8410:
    *(word*)(fp - 40) = (*(word*)(fp - 40) + 1);    // $8419
    *(byte*)(((*(word*)(fp - 40) + 1) - 1)) = (*(byte*)(((*(word*)(fp - 40) + 1) - 1)) + (const_two * 5));    // $8420
L_8423:
    local10 = (local10 + 1);    // $8423
    if (((unsigned)local10 >= (unsigned)5)) goto L_8410;    // $8427
    local8 = ((local11 * 26) + 0x7001);    // $8432
    local8 = (local8 + 2);    // $843B
    *(word*)(((local8 + 2) + -2)) = (*(word*)(((local8 + 2) + -2)) + (const_two * 10));    // $8442
    local10 = 0;    // $8444
L_8445:
    local8 = (local8 + 2);    // $844D
    *(word*)((local8 + 2)) = (*(word*)((local8 + 2)) + (const_two * 5));    // $8452
    local10 = (local10 + 1);    // $8455
    if (((unsigned)local10 >= (unsigned)10)) goto L_8445;    // $8459
    if ((scenario_fief_count != 50)) goto L_8507;    // $8462
    if ((local11 == 5)) goto L_84B5;    // $8468
    if ((local11 == 9)) goto L_84B5;    // $846E
    if ((local11 == 13)) goto L_84B5;    // $8474
    if ((local11 == 14)) goto L_84B5;    // $847A
    if ((local11 == 19)) goto L_84B5;    // $8481
    if ((local11 == 23)) goto L_84B5;    // $8488
    if ((local11 == 26)) goto L_84B5;    // $848F
    if ((local11 == 21)) goto L_84B5;    // $8496
    if ((local11 == 38)) goto L_84B5;    // $849D
    if ((local11 == 42)) goto L_84B5;    // $84A4
    if ((local11 == 49)) goto L_84B5;    // $84AB
    if ((local11 == 24)) {    // $84B2
L_84B5:
    if (rng_mod(2)) {    // $84BA
    *(word*)(((local9 << 1) + (fp - 38))) = local11;    // $84C7
    local9 = (local9 + 1);    // $84CA
    *(word*)(((local11 * 26) + 0x7001)) = (*(word*)(((local11 * 26) + 0x7001)) * 2);    // $84D8
    *(word*)(((local11 * 26) + 0x7007)) = (*(word*)(((local11 * 26) + 0x7007)) * 4);    // $84E6
    *(word*)(((local11 * 26) + 0x700D)) = (*(word*)(((local11 * 26) + 0x700D)) * 2);    // $84F4
    *(word*)(((local11 * 26) + 0x7013)) = (*(word*)(((local11 * 26) + 0x7013)) * 2);    // $8502
    goto L_8581;    // $8504
L_8507:
    if ((local11 == 1)) goto L_8532;    // $850A
    if ((local11 == 2)) goto L_8532;    // $8510
    if ((local11 == 4)) goto L_8532;    // $8516
    if ((local11 == 7)) goto L_8532;    // $851C
    if ((local11 == 10)) goto L_8532;    // $8522
    if ((local11 == 15)) goto L_8532;    // $8528
    if ((local11 == 16)) {    // $852F
L_8532:
    if (rng_mod(2)) {    // $8537
    *(word*)(((local9 << 1) + (fp - 38))) = local11;    // $8544
    local9 = (local9 + 1);    // $8547
    *(word*)(((local11 * 26) + 0x7001)) = (*(word*)(((local11 * 26) + 0x7001)) * 2);    // $8555
    *(word*)(((local11 * 26) + 0x7007)) = (*(word*)(((local11 * 26) + 0x7007)) * 3);    // $8563
    *(word*)(((local11 * 26) + 0x700D)) = (*(word*)(((local11 * 26) + 0x700D)) * 2);    // $8571
    *(word*)(((local11 * 26) + 0x7013)) = (*(word*)(((local11 * 26) + 0x7013)) * 2);    // $857F
L_8581:
    *(word*)(((local11 * 26) + 0x7011)) = (*(word*)(((local11 * 26) + 0x7011)) * 2);    // $858D
    }
    }
    }
    }
L_858E:
    local11 = 2;    // $858E
L_8593:
    local8 = ((local11 * 26) + 0x7019);    // $859B
    local8 = 0x7019;    // $859C
    *(word*)(0x7019) = pct_op((rng_mod(20) + 80), (*(word*)(local8) + 1000));    // $85B0
    local11 = (local11 + 1);    // $85B3
L_85B4:
    if (((unsigned)local11 >= (unsigned)scenario_fief_count)) goto L_83F7;    // $85B9
    goto L_85F4;    // $85BD
L_85C0:
    goto L_85EB;    // $85C1
L_85C4:
    if ((selected_province_idx != battle_defending_province)) {    // $85E3
    }
L_85E9:
L_85EB:
    local10 = (local10 + 1);    // $85EB
    if (((unsigned)local10 >= (unsigned)local9)) goto L_85C4;    // $85EF
L_85F4:
    local11 = (local11 + 1);    // $85F4
    if (((unsigned)local11 >= (unsigned)local9)) goto L_85C0;    // $85F8
    return ((unsigned)local11 >= (unsigned)local9);    // $85FB
}

// $85FC prompt_roll_stat_value
// (body @ $8601)

word prompt_roll_stat_value(word arg1, word arg2, word arg3, word arg4) {
    local11 = mem_7FCD;    // $8604
L_8605:
    if (poll_input()) goto L_8605;    // $8608
    goto L_8612;    // $860B
L_860E:
L_8612:
    local10 = (rng_mod(50) + 60);    // $861A
    if (!(poll_input())) goto L_860E;    // $8626
    return local10;    // $862A
}

// $862B prompt_select_scenario_size
// (body @ $8630)

word prompt_select_scenario_size(word arg1, word arg2, word arg3, word arg4) {
L_8630:
    local10 = ui_helper_d351(0xB8C8);    // $863E
    if ((local10 == 2)) goto L_8630;    // $8642
    if ((local10 == 1)) {    // $8648
    } else {
    }
L_865E:
    local11 = 0x8004;    // $865E
    local11 = 0x6001;    // $866B
    return mem_6E7D;    // $867E
    }
}

// $867F display_prompt_message_b900
// (body @ $8684)

word display_prompt_message_b900(word arg1, word arg2, word arg3, word arg4) {
    arg1 = ?;    // $868B
    return ui_helper_d134(/*via arg1*/ ?, 0xB900);    // $8693
}

// $8694 prompt_select_player_daimyo
// (body @ $8699)

word prompt_select_player_daimyo(word arg1, word arg2, word arg3, word arg4) {
    if ((scenario_fief_count == 50)) {    // $869F
    } else {
    }
L_86A7:
    local11 = 0;    // $86B1
L_86B2:
    arg1 = 50;    // $86B2
    goto L_86F1;    // $86B7
L_86BA:
    if ((local10 == 1)) {    // $86C5
    if ((scenario_fief_count == 50)) {    // $86CE
    local11 = (local11 + 1);    // $86D3
    if (!(((unsigned)(local11 + 1) < (unsigned)9))) goto L_86DB;    // $86D6
    local11 = 0;    // $86DA
L_86DB:
    local11 = 9;    // $86DB
    } else {
    local11 = (local11 + 1);    // $86E1
    if (!(((unsigned)(local11 + 1) < (unsigned)4))) goto L_86E9;    // $86E4
    local11 = 0;    // $86E8
L_86E9:
    }
L_86ED:
L_86F1:
    local10 = number_input(scenario_fief_count, 1);    // $86F9
    if ((number_input(scenario_fief_count, 1) >= 0)) goto L_86BA;    // $86FC
    local10 = (local10 - 1);    // $8701
    if (!((*(byte*)(((local10 - 1) + 0x6CF7)) != 5))) goto L_8734;    // $8709
    if (ui_helper_d3a7()) {    // $872C
    local11 = 0;    // $8730
    goto L_873E;    // $8731
L_8734:
    }
L_873E:
    if ((local11 != 9)) goto L_86B2;    // $8741
    province_ai_state[local10] = 0;    // $874F
    *(byte*)((arg1 + 0x7FD4)) = ui_helper_d77e();    // $8761
    return ui_helper_d77e();    // $8762
    }
    }
    }
}

// $8763 daimyo_creation_stat_roll_screen
// (body @ $8768)

word daimyo_creation_stat_roll_screen(word arg1, word arg2, word arg3, word arg4) {
    local11 = ui_helper_d7ea();    // $87E2
    local11 = (local11 + 1);    // $87E5
    local9 = 0;    // $8831
L_8832:
    local9 = (local9 + 1);    // $8855
    if ((local9 < 6)) goto L_8832;    // $8859
L_8861:
    local9 = 0;    // $8862
    local11 = ((selected_province_idx * 7) + 0x7530);    // $886C
    local10 = 0;    // $886E
L_886F:
    local11 = 0x7530;    // $8878
    *(byte*)(0x7530) = prompt_roll_stat_value();    // $887C
    local11 = (local11 + 1);    // $887F
    local9 = (local9 + *(byte*)(((local11 + 1) - 1)));    // $8885
    local10 = (local10 + 1);    // $8888
    if (((unsigned)local10 <= (unsigned)5)) goto L_886F;    // $888C
    local9 = 5;    // $8896
    if (!(ui_helper_d3a7())) goto L_8861;    // $88A8
    return ui_helper_d3a7();    // $88AB
}

// $88AC render_boot_title_screens
// (body @ $88B1)

word render_boot_title_screens(word arg1, word arg2, word arg3, word arg4) {
    local11 = 0;    // $88E2
L_88E3:
    local11 = 0xB862;    // $88EA
    local11 = (local11 + 1);    // $88F1
    if (((unsigned)local11 >= (unsigned)32)) goto L_88E3;    // $88F6
L_8908:
    if (syscall_dispatch(0, 6)) goto L_8908;    // $890E
    if (syscall_dispatch(1, 6)) goto L_8908;    // $8917
L_891A:
    if (syscall_dispatch(0, 6)) goto L_892C;    // $8920
    if (!(syscall_dispatch(1, 6))) goto L_891A;    // $8929
L_892C:
    local11 = 0;    // $8987
L_8988:
    local11 = 0xB85A;    // $898F
    local11 = (local11 + 1);    // $8996
    if (((unsigned)local11 >= (unsigned)8)) goto L_8988;    // $899A
    return marry_helper_cc35(0);    // $89A2
}

// $89A3 init_new_game_state
// (body @ $89A8)

word init_new_game_state(word arg1, word arg2, word arg3, word arg4) {
L_89C1:
    if (!(!(verify_sram_save_integrity()))) return syscall_dispatch(0, 0, 10);    // $89CC
    local11 = 0;    // $89D8
L_89D9:
    *(byte*)((local11 + 0x7FD5)) = -1;    // $89E1
    local11 = (local11 + 1);    // $89E4
    if (((unsigned)local11 >= (unsigned)8)) goto L_89D9;    // $89E8
    goto L_89FC;    // $89EF
L_89F2:
    *(byte*)((local11 + 0x6F1B)) = local11;    // $89F9
L_89FC:
    local11 = (local11 + 1);    // $89FC
    if (((unsigned)local11 >= (unsigned)scenario_fief_count)) goto L_89F2;    // $8A02
    goto L_8A13;    // $8A06
L_8A09:
    province_ai_state[local11] = 0;    // $8A10
L_8A13:
    local11 = (local11 + 1);    // $8A13
    if (((unsigned)local11 >= (unsigned)(scenario_fief_count + 4))) goto L_8A09;    // $8A1C
L_8A1F:
    if (!(mem_6D61)) goto L_8A1F;    // $8A2F
    local11 = 0;    // $8A33
L_8A34:
    *(word*)(((local11 << 1) + 0x6E0B)) = (rng_mod(10) + 8);    // $8A41
    local11 = (local11 + 1);    // $8A44
    if (((unsigned)local11 >= (unsigned)5)) goto L_8A34;    // $8A48
    local11 = 0;    // $8A72
L_8A73:
    local11 = 0xB852;    // $8A7A
    local11 = (local11 + 1);    // $8A81
    if (((unsigned)local11 >= (unsigned)8)) goto L_8A73;    // $8A85
    goto L_8ABC;    // $8A8E
L_8A91:
    if (((local11 & 1) == 1)) {    // $8AA7
    } else {
    }
L_8AAF:
    local11 = 1;    // $8AB2
L_8ABC:
    local11 = (local11 + 1);    // $8ABC
    if (((unsigned)local11 <= (unsigned)mem_6D61)) goto L_8A91;    // $8AC2
L_8AC9:
    if (!(const_two)) goto L_8AC9;    // $8AD9
    if (ui_helper_d3a7()) goto L_8B44;    // $8AE6
    local11 = 0;    // $8B18
L_8B19:
    if (((unsigned)local11 >= (unsigned)8)) {    // $8B1C
    } else {
    }
L_8B2A:
    local11 = 0xB862;    // $8B2D
    local11 = (local11 + 1);    // $8B34
    if (((unsigned)local11 >= (unsigned)32)) goto L_8B19;    // $8B39
    goto L_89C1;    // $8B41
L_8B44:
    return palette_write_wrap(48, 11);    // $8B6F
    }
    }
}

// $8B70 select_msg_by_state_7b79
// (body @ $8B75)

word select_msg_by_state_7b79(word arg1, word arg2, word arg3, word arg4) {
    if ((*(byte*)((arg1 + 0x7B79)) == 6)) {    // $8B7D
    } else {
    if (!((*(byte*)((arg1 + 0x7B79)) == 7))) goto L_8B97;    // $8B8E
    goto L_8B9A;    // $8B94
L_8B97:
    }
L_8B9A:
    local11 = 0xBA3A;    // $8B9A
    return local11;    // $8B9C
    }
}

// $8B9D select_message_string_by_flags_and_arg
// (body @ $8BA2)

word select_message_string_by_flags_and_arg(word arg1, word arg2, word arg3, word arg4) {
    if (!(!((mem_6DA1 & 32)))) return 0xBA55;    // $8BA8
    if (!(!((mem_6DA1 & 16)))) return 0x796A;    // $8BB5
    switch (arg1) {    // $8BBD
        case 7: goto L_8BD2;    // $8BBD
        case 13: goto L_8BD8;    // $8BBD
        case 23: goto L_8BD2;    // $8BBD
        case 30: goto L_8BD8;    // $8BBD
        default: goto L_8BDE;    // $8BBD
    }    // $8BBD
L_8BD2:
L_8BD5:
    local11 = 0xBA43;    // $8BD5
    return local11;    // $8BD7
L_8BD8:
    goto L_8BD5;    // $8BDB
L_8BDE:
    arg1 = 16;    // $8BDE
    goto L_8BD5;    // $8BE3
}

// $8BE6 find_first_enemy_owned_fief
// (body @ $8BEB)

word find_first_enemy_owned_fief(word arg1, word arg2, word arg3, word arg4) {
    goto L_8C03;    // $8BF1
L_8BF4:
    if (!(!(is_enemy_owned(*(byte*)(local11))))) return *(byte*)(local11);    // $8BFB
L_8C03:
    local11 = (local11 + 1);    // $8C03
    if ((*(byte*)(local11) != 0x00FF)) goto L_8BF4;    // $8C0A
    return (*(byte*)(local11) != 0x00FF);    // $8C0D
}

// $8C0E is_selected_province_ai_state_5
// (body @ $8C13)

word is_selected_province_ai_state_5(word arg1, word arg2, word arg3, word arg4) {
    return (province_ai_state[selected_province_idx] == 5);    // $8C1D
}

// $8C1E cur_flag_and_selected_ai_state5
// (body @ $8C23)

word cur_flag_and_selected_ai_state5(word arg1, word arg2, word arg3, word arg4) {
    if (!(get_6da2_cur())) goto L_8C2F;    // $8C26
    if (is_selected_province_ai_state_5()) goto L_8C33;    // $8C2C
L_8C2F:
    goto L_8C34;    // $8C30
L_8C33:
L_8C34:
    return 0;    // $8C34
}

// $8C35 relations_matrix_cell_addr
// (body @ $8C3A)

word relations_matrix_cell_addr(word arg1, word arg2, word arg3, word arg4) {
    return (((arg1 * 54) + arg2) + 0x6193);    // $8C44
}

// $8C45 set_6da1_bit7_if_no_ai_state5_province_found
// (body @ $8C4A)

word set_6da1_bit7_if_no_ai_state5_province_found(word arg1, word arg2, word arg3, word arg4) {
    local11 = 0;    // $8C4B
    goto L_8C68;    // $8C4F
L_8C52:
    if (cur_flag_and_selected_ai_state5()) {    // $8C5E
    local11 = 0;    // $8C62
    } else {
L_8C68:
    local10 = (local10 - 1);    // $8C68
    if (local10) goto L_8C52;    // $8C6A
    }
L_8C6D:
    if (local11) goto L_8C74;    // $8C6E
L_8C74:
    return set_6da1_bit7();    // $8C74
    }
}

// $8C75 resolve_ownerless_province_succession
// (body @ $8C7A)

word resolve_ownerless_province_succession(word arg1, word arg2, word arg3, word arg4) {
    local7 = 0;    // $8C7B
    local8 = 0;    // $8C7D
    if ((!(((unsigned)arg1 < (unsigned)2)))) return install_new_daimyo(battle_defending_province);    // $8C81
    local11 = 0;    // $8C8D
    local9 = 0x6F4F;    // $8C91
    goto L_8D36;    // $8C92
L_8C95:
    if (!(get_province_ai_state(selected_province_idx))) goto L_8D0A;    // $8CA7
    if (rest_turns_remaining[ui_helper_d77e()]) goto L_8D22;    // $8CB2
    if ((*(word*)(((selected_province_idx * 26) + 0x7001)) > 0)) {    // $8CC2
    if (ui_helper_d3a7()) {    // $8CE8
    local8 = number_input(*(word*)(((selected_province_idx * 26) + 0x7001)), 1);    // $8D03
    goto L_8D22;    // $8D07
L_8D0A:
    local6 = *(word*)(((selected_province_idx * 26) + 0x7001));    // $8D15
    if ((local6 > local8)) {    // $8D19
    local6 = local8;    // $8D1C
    local8 = rng_mod(/*stack underflow*/ regA);    // $8D21
    }
    }
    }
L_8D22:
    if ((local7 < local8)) {    // $8D25
    local7 = local8;    // $8D29
    local10 = selected_province_idx;    // $8D2D
    }
L_8D2E:
    local9 = (local9 + 1);    // $8D30
    local11 = (local11 + 1);    // $8D34
L_8D36:
    if ((*(byte*)(local9) != 0x00FF)) goto L_8C95;    // $8D3C
    if (local7) goto L_8D4D;    // $8D40
    goto L_8DE0;    // $8D4A
L_8D4D:
    local10 = 0x6CF7;    // $8D55
    if (get_province_ai_state((battle_defending_province + 0x6CF7))) {    // $8D5A
    } else {
    }
L_8D62:
    *(byte*)(0x6CF7) = 0;    // $8D62
    *(byte*)((battle_defending_province + 0x6DA2)) = 0;    // $8D6C
    local10 = 0x6E15;    // $8D75
    *(byte*)(0x6E15) = ui_helper_d772((battle_defending_province + 0x6E15));    // $8D7A
    local8 = 0x6E15;    // $8D7B
    *(word*)(((local10 * 26) + 0x7001)) = (*(word*)(((local10 * 26) + 0x7001)) - 0x7001);    // $8D88
    local10 = 0x7001;    // $8D89
    if (get_province_ai_state(/*stack underflow*/ regA)) {    // $8D8E
    local10 = 0x7001;    // $8D98
    } else {
    local10 = 0x7001;    // $8DBF
    }
L_8DD6:
L_8DE0:
    return confirm_prompt();    // $8DE0
    }
    }
}

// $8DE1 dedup_owners_to_6f4f
// (body @ $8DE6)

word dedup_owners_to_6f4f(word arg1, word arg2, word arg3, word arg4) {
    arg1 = (arg1 + 1);    // $8DE8
    *(byte*)(fp - 14) = *(byte*)(((arg1 + 1) - 1));    // $8DEB
    local10 = 0;    // $8DEF
    goto L_8E33;    // $8DF0
L_8DF3:
    local9 = 0;    // $8DF4
    goto L_8E17;    // $8DF6
L_8DF9:
    if ((ui_helper_d772(*(byte*)((local11 + &local5))) == ui_helper_d772(*(byte*)(arg1)))) {    // $8E10
    local9 = 0;    // $8E14
    }
L_8E15:
L_8E17:
    local11 = (local11 + 1);    // $8E17
    if (((unsigned)local11 >= (unsigned)local10)) goto L_8DF9;    // $8E1B
    if (local9) goto L_8E30;    // $8E1F
    local10 = (local10 + 1);    // $8E28
    *(byte*)((((local10 + 1) - 1) + &local5)) = *(byte*)(arg1);    // $8E2F
L_8E30:
    arg1 = (arg1 + 1);    // $8E32
L_8E33:
    if ((*(byte*)(arg1) != 0x00FF)) goto L_8DF3;    // $8E39
    goto L_8E51;    // $8E3D
L_8E40:
    *(byte*)((local11 + 0x6F4F)) = *(byte*)((local11 + &local5));    // $8E4E
L_8E51:
    local11 = (local11 + 1);    // $8E51
    if (((unsigned)local11 >= (unsigned)local10)) goto L_8E40;    // $8E55
    *(byte*)((local11 + 0x6F4F)) = -1;    // $8E60
    return local10;    // $8E62
}

// $8E63 process_fiefs_with_state_ff
// (body @ $8E68)

word process_fiefs_with_state_ff(word arg1, word arg2, word arg3, word arg4) {
    goto L_8E8F;    // $8E69
L_8E6C:
    local11 = ?;    // $8E6C
    if (province_state_is_FF(/*stack underflow*/ regA)) {    // $8E71
    }
L_8E8D:
L_8E8F:
    local11 = (local11 + 1);    // $8E8F
    if (((unsigned)local11 >= (unsigned)scenario_fief_count)) goto L_8E6C;    // $8E95
    return ((unsigned)local11 >= (unsigned)scenario_fief_count);    // $8E98
}

// $8E99 append_candidate_entry_6f67
// (body @ $8E9E)

word append_candidate_entry_6f67(word arg1, word arg2, word arg3, word arg4) {
    *(byte*)(((arg2 << 1) + 0x6F67)) = arg1;    // $8EA6
    *(byte*)(((arg2 << 1) + 0x6F68)) = arg3;    // $8EAF
    *(byte*)((((arg2 + 1) << 1) + 0x6F67)) = -1;    // $8EBA
    return -1;    // $8EBB
}

// $8EBC compare_greater_with_coinflip_tiebreak
// (body @ $8EC1)

word compare_greater_with_coinflip_tiebreak(word arg1, word arg2, word arg3, word arg4) {
    if (((arg1 == arg2))) return (rng_mod(2) == 0);    // $8EC4
    return (arg2 < arg1);    // $8ED2
}

// $8ED3 display_two_message_prompt_then_compare
// (body @ $8ED8)

word display_two_message_prompt_then_compare(word arg1, word arg2, word arg3, word arg4) {
    arg3 = ?;    // $8ED8
    local11 = select_message_string_de78(/*via arg3*/ ?);    // $8EDD
    arg3 = ?;    // $8EDE
    local10 = select_message_string_by_flags_and_arg(/*via arg3*/ ?);    // $8EE3
    local11 = ?;    // $8EEB
    arg1 = ?;    // $8EF6
    local10 = ?;    // $8EF7
    arg2 = ?;    // $8EF8
    arg2 = ?;    // $8F03
    arg1 = ?;    // $8F04
    return compare_greater_with_coinflip_tiebreak(/*via arg2*/ ?, /*via arg2*/ ?);    // $8F09
}

// $8F0A ai_resolve_province_takeover_attempt
// (body @ $8F0F)

word ai_resolve_province_takeover_attempt(word arg1, word arg2, word arg3, word arg4) {
    arg1 = ?;    // $8F0F
    local10 = select_message_string_de78(/*via arg1*/ ?);    // $8F14
    local11 = ((arg1 * 26) + 0x7001);    // $8F23
    local9 = (((sqrt_int(*(word*)((local11 + 8))) + sqrt_int(*(word*)((local11 + 14)))) + rng_mod(20)) + 10);    // $8F41
    local8 = *(word*)((local11 + 16));    // $8F46
    arg1 = rng_mod(20);    // $8F47
    local8 = rng_mod(20);    // $8F48
    local9 = rng_mod(20);    // $8F49
    if (!(display_two_message_prompt_then_compare(/*via arg1*/ rng_mod(20), /*via arg1*/ rng_mod(20), /*via arg1*/ rng_mod(20)))) goto L_8F96;    // $8F4E
    local10 = rng_mod(20);    // $8F58
    if (*(byte*)((arg1 + 0x6DA2))) {    // $8F69
    arg1 = 0x6DA2;    // $8F6C
    local5 = ui_helper_d772(/*via arg1*/ 0x6DA2);    // $8F71
    arg1 = 0x6DA2;    // $8F72
    local5 = 0x6DA2;    // $8F77
    local5 = 0x6DA2;    // $8F7C
    arg1 = 0x6DA2;    // $8F81
    arg1 = 0x6DA2;    // $8F86
    } else {
    arg1 = 0x6DA2;    // $8F8E
    goto L_8FD2;    // $8F93
L_8F96:
    *(word*)((local11 + 16)) = (*(word*)((local11 + 16)) - pct_op((rng_mod(50) + 10), *(word*)((local11 + 16))));    // $8FB6
    *(word*)((local11 + 8)) = (*(word*)((local11 + 8)) - pct_op((rng_mod(50) + 10), *(word*)((local11 + 8))));    // $8FCE
    }
L_8FD2:
    return confirm_prompt();    // $8FD2
    }
}

// $8FD3 append_candidate_zero_priority
// (body @ $8FD8)

word append_candidate_zero_priority(word arg1, word arg2, word arg3, word arg4) {
    arg2 = ?;    // $8FD9
    arg1 = ?;    // $8FDA
    return append_candidate_entry_6f67(/*via arg2*/ ?, /*via arg2*/ ?, 0);    // $8FDF
}

// $8FE0 stat_above_threshold_and_gap_predicate
// (body @ $8FE5)

word stat_above_threshold_and_gap_predicate(word arg1, word arg2, word arg3, word arg4) {
    if ((arg2 <= 25)) goto L_8FF6;    // $8FE9
    if ((!(((arg2 - arg1) <= 5)))) return 0;    // $8FF1
    return 0;    // $8FF7
}

// $8FF8 collect_high_loyalty_provinces_to_candidate_list
// (body @ $8FFD)

word collect_high_loyalty_provinces_to_candidate_list(word arg1, word arg2, word arg3, word arg4) {
    local11 = 0x7BAD;    // $9000
    local9 = 0;    // $9002
    goto L_90B6;    // $9003
L_9006:
    if (!(cur_flag_and_selected_ai_state5())) goto L_9097;    // $9009
    local5 = ((selected_province_idx * 26) + 0x7001);    // $9016
    local8 = ((selected_province_idx * 26) + 0x7001);    // $9017
    local7 = (local5 + 12);    // $901A
    local6 = *(word*)(local7);    // $901D
    if (*(word*)(local8)) {    // $9020
    if (rest_turns_remaining[ui_helper_d77e()]) goto L_908A;    // $902B
    if (!(ui_helper_d3a7())) goto L_908A;    // $9046
    local5 = 0x6D67;    // $904C
    local5 = 0x6D67;    // $9051
    *(word*)(0x6D67) = 0;    // $9053
    local6 = 0x6D67;    // $905E
    if (stat_above_threshold_and_gap_predicate(/*stack underflow*/ regA, *(word*)(local7))) goto L_907D;    // $9063
    local9 = (local9 + 1);    // $9072
    return append_candidate_zero_priority(((local9 + 1) - 1), selected_province_idx);    // $907C
L_907D:
    } else {
    local9 = (local9 + 1);    // $908C
    return append_candidate_zero_priority(((local9 + 1) - 1), selected_province_idx);    // $9096
L_9097:
    *(word*)(((selected_province_idx * 26) + 0x700D)) = (*(word*)(((selected_province_idx * 26) + 0x700D)) + (rng_mod(30) + 50));    // $90B5
    }
L_90B6:
    local11 = (local11 + 1);    // $90B8
    if ((selected_province_idx != 0x00FF)) goto L_9006;    // $90C2
    return (selected_province_idx != 0x00FF);    // $90C5
    }
}

// $90C6 reset_byte_if_ge_100
// (body @ $90CB)

word reset_byte_if_ge_100(word arg1, word arg2, word arg3, word arg4) {
    if ((*(byte*)(arg1) <= 100)) {    // $90D0
    arg1 = 100;    // $90D3
    *(byte*)(100) = 0;    // $90D5
    }
L_90D6:
    return 0;    // $90D6
}

// $90D7 saturating_sub_byte_then_reset_if_ge_100
// (body @ $90DC)

word saturating_sub_byte_then_reset_if_ge_100(word arg1, word arg2, word arg3, word arg4) {
    arg2 = ?;    // $90DC
    arg1 = ?;    // $90DD
    arg1 = ?;    // $90E2
    return reset_byte_if_ge_100(/*via arg1*/ ?);    // $90E7
}

// $90E8 normalize_relations_matrix_lower
// (body @ $90ED)

word normalize_relations_matrix_lower(word arg1, word arg2, word arg3, word arg4) {
    goto L_9114;    // $90EE
L_90F1:
    goto L_9109;    // $90F2
L_90F5:
    if (((unsigned)local11 >= (unsigned)local10)) {    // $90F8
    arg1 = local10;    // $90FB
    local10 = local10;    // $90FC
    local11 = local10;    // $90FD
    }
L_9107:
L_9109:
    local10 = (local10 + 1);    // $9109
    if (((unsigned)local10 >= (unsigned)scenario_fief_count)) goto L_90F5;    // $910F
L_9114:
    local11 = (local11 + 1);    // $9114
    if (((unsigned)local11 >= (unsigned)scenario_fief_count)) goto L_90F1;    // $911A
    return ((unsigned)local11 >= (unsigned)scenario_fief_count);    // $911D
}

// $911E normalize_relations_matrix_upper
// (body @ $9123)

word normalize_relations_matrix_upper(word arg1, word arg2, word arg3, word arg4) {
    goto L_914A;    // $9124
L_9127:
    goto L_913F;    // $9128
L_912B:
    if (((unsigned)local11 >= (unsigned)local10)) {    // $912E
    arg1 = local10;    // $9131
    local11 = local10;    // $9132
    local10 = local10;    // $9133
    }
L_913D:
L_913F:
    local10 = (local10 + 1);    // $913F
    if (((unsigned)local10 >= (unsigned)scenario_fief_count)) goto L_912B;    // $9145
L_914A:
    local11 = (local11 + 1);    // $914A
    if (((unsigned)local11 >= (unsigned)scenario_fief_count)) goto L_9127;    // $9150
    return ((unsigned)local11 >= (unsigned)scenario_fief_count);    // $9153
}

// $9154 check_daimyo_natural_death
// (body @ $9159)

word check_daimyo_natural_death(word arg1, word arg2, word arg3, word arg4) {
    arg1 = ?;    // $9159
    local11 = daimyo_record_addr(/*via arg1*/ ?);    // $915E
    if (!(*(byte*)((local11 + 1)))) return 0;    // $9162
    if ((!((*(byte*)(local11) >= 70)))) return 0;    // $916C
    if ((!((rng_mod(0x012C) >= ((*(byte*)(local11) + -10) - (*(byte*)((local11 + 1)) / 4)))))) return (daimyo_weakness_flag[arg1] + 1);    // $9187
    return 0;    // $9193
}

// $9194 check_and_process_daimyo_natural_death
// (body @ $9199)

word check_and_process_daimyo_natural_death(word arg1, word arg2, word arg3, word arg4) {
    if (!(*(byte*)((arg1 + 0x6DA2)))) goto L_91FC;    // $919F
    arg1 = 0x6DA2;    // $91A2
    local11 = ui_helper_d772(/*via arg1*/ 0x6DA2);    // $91A7
    local11 = 0x6DA2;    // $91A8
    local10 = check_daimyo_natural_death(/*stack underflow*/ regA);    // $91AD
    if (!(check_daimyo_natural_death(/*stack underflow*/ regA))) goto L_91FC;    // $91AE
    if ((local10 != 1)) goto L_91BE;    // $91B4
    if (!(!(config_block))) return config_block;    // $91BA
    local11 = 1;    // $91BE
    local11 = 1;    // $91C3
    arg1 = 1;    // $91C8
    if (get_province_ai_state(/*via arg1*/ 1)) {    // $91CD
    }
L_91D3:
    arg1 = 0xBBA5;    // $91EF
    arg1 = 0xBBA5;    // $91F7
L_91FC:
    return find_fiefs_of_owner(/*via arg1*/ 0xBBA5);    // $91FC
}

// $91FD clamp_value_to_range
// (body @ $9202)

word clamp_value_to_range(word arg1, word arg2, word arg3, word arg4) {
    if ((!((arg1 <= arg2)))) return arg1;    // $9205
    if ((!((arg2 <= arg3)))) return arg3;    // $920D
    return arg2;    // $9213
}

// $9214 calc_year_scaled_random_value
// (body @ $9219)

word calc_year_scaled_random_value(word arg1, word arg2, word arg3, word arg4) {
    return (((((mem_6D9F - 1560) / 2) + 2) * 10) + rng_mod(51));    // $922D
}

// $922E roll_small_or_large_random
// (body @ $9233)

word roll_small_or_large_random(word arg1, word arg2, word arg3, word arg4) {
    if (!(!(rng_mod(2)))) return (rng_mod(6) + 5);    // $9238
    return (rng_mod(10) + 30);    // $9249
}

// $924A roll_period_rate_table_6e0b
// (body @ $924F)

word roll_period_rate_table_6e0b(word arg1, word arg2, word arg3, word arg4) {
    if (rng_mod(5)) {    // $925D
    } else {
    }
L_9279:
    return mem_6E13;    // $92A8
    }
}

// $92A9 repay_province_debt_from_gold
// (body @ $92AE)

word repay_province_debt_from_gold(word arg1, word arg2, word arg3, word arg4) {
    if (!(arg1->debt)) return 0;    // $92B1
    arg2 = ?;    // $92C2
    arg2 = min_word(/*via arg2*/ ?, min_word(arg1->debt, *(word*)(arg1)));    // $92C7
    arg2 = ?;    // $92C8
    *(word*)(arg1) = (*(word*)(arg1) - ?);    // $92CE
    arg2 = ?;    // $92CF
    arg1->debt = (arg1->debt - ?);    // $92D6
    return 0;    // $92D8
}

// $92D9 deduct_b_from_a_void_b_if_overdrawn
// (body @ $92DE)

word deduct_b_from_a_void_b_if_overdrawn(word arg1, word arg2, word arg3, word arg4) {
    if ((*(word*)(arg1) >= 0)) goto L_92F5;    // $92E2
    *(word*)(arg1) = (*(word*)(arg1) - *(word*)(arg2));    // $92ED
    if ((*(word*)(arg1) < 0)) {    // $92F2
L_92F5:
    arg2 = 0;    // $92F5
    *(word*)(0) = 0;    // $92F7
    }
L_92F8:
    return 0;    // $92F8
}

// $92F9 random_ravage_province_field
// (body @ $92FE)

word random_ravage_province_field(word arg1, word arg2, word arg3, word arg4) {
    if (rng_mod(2)) goto L_930D;    // $9303
    if ((*(word*)(arg1) >= 0)) {    // $930A
L_930D:
    return 0;    // $930E
    }
L_930F:
    arg1 = 0;    // $930F
    *(word*)(0) = pct_op((rng_mod(30) + 40), *(word*)(arg1));    // $9320
    return 0;    // $9322
}

// (body @ $9328)

word sub_9323(word arg1, word arg2, word arg3, word arg4) {
    return random_ravage_province_field(((battle_defending_province * 26) + 0x700B));    // $9337
}

// (body @ $933D)

word sub_9338(word arg1, word arg2, word arg3, word arg4) {
    if (random_ravage_province_field(((battle_defending_province * 26) + 0x7009))) {    // $934C
    *(word*)(((selected_province_idx * 26) + 0x700F)) = (*(word*)(((selected_province_idx * 26) + 0x700F)) + (rng_mod(100) + 100));    // $9366
    return 0;    // $9368
    }
L_9369:
    return 0;    // $936A
}

// (body @ $9370)

word sub_936B(word arg1, word arg2, word arg3, word arg4) {
    return random_ravage_province_field(((battle_defending_province * 26) + 0x7005));    // $937F
}

// (body @ $9385)

word sub_9380(word arg1, word arg2, word arg3, word arg4) {
    return random_ravage_province_field(((battle_defending_province * 26) + 0x700F));    // $9394
}

// (body @ $939A)

word sub_9395(word arg1, word arg2, word arg3, word arg4) {
    return random_ravage_province_field(((battle_defending_province * 26) + 0x7013));    // $93A9
}

// (body @ $93AF)

word sub_93AA(word arg1, word arg2, word arg3, word arg4) {
    return random_ravage_province_field(((battle_defending_province * 26) + 0x700D));    // $93BE
}

// (body @ $93C4)

word sub_93BF(word arg1, word arg2, word arg3, word arg4) {
    if (sub_9323()) goto L_944E;    // $93F0
    if (sub_936B()) goto L_944E;    // $93F6
    if (sub_93AA()) goto L_944E;    // $93FC
    if (sub_9395()) goto L_944E;    // $9402
    if (sub_9380()) goto L_944E;    // $9408
    if (sub_9338()) goto L_944E;    // $940E
    if (rng_mod(2)) {    // $9416
    local11 = ((battle_defending_province * 26) + 0x7001);    // $9423
    local10 = fief_to_daimyo_record_addr(battle_defending_province);    // $942B
    if ((*(word*)((local11 + 10)) >= 0)) {    // $9431
L_944E:
    return 0;    // $9452
    }
L_9453:
    *(word*)((local11 + 10)) = pct_op((rng_mod(30) + 60), *(word*)((local11 + 10)));    // $9467
    goto L_944E;    // $9468
    }
L_946B:
    return 0;    // $946C
}

// (body @ $9472)

word sub_946D(word arg1, word arg2, word arg3, word arg4) {
    arg1 = ?;    // $9472
    return *(byte*)((fief_to_daimyo_record_addr(/*via arg1*/ ?) + 4));    // $9479
}

// (body @ $947F)

word sub_947A(word arg1, word arg2, word arg3, word arg4) {
    local9 = 0;    // $9487
    local10 = 0;    // $9489
    local11 = 0x6F89;    // $948D
    goto L_94A4;    // $948E
L_9491:
    local10 = (local10 + sub_946D(*(byte*)(local11)));    // $949B
    local11 = (local11 + 1);    // $949E
    local9 = (local9 + 1);    // $94A2
L_94A4:
    if ((*(byte*)(local11) != 0x00FF)) goto L_9491;    // $94AA
    return ((unsigned)local10 / (unsigned)local9);    // $94B0
}

// (body @ $94B6)

word sub_94B1(word arg1, word arg2, word arg3, word arg4) {
    switch (arg1) {    // $94B7
        case 1: goto L_94C4;    // $94B7
        case 2: goto L_94E9;    // $94B7
        default: goto L_94CE;    // $94B7
    }    // $94B7
L_94C4:
L_94C7:
L_94CE:
    local11 = 0;    // $94CF
    goto L_951D;    // $94D0
L_94D3:
    local10 = ?;    // $94D3
    if (!(get_province_ai_state(/*stack underflow*/ regA))) goto L_951D;    // $94D8
    switch (arg1) {    // $94DC
        case 1: goto L_94EF;    // $94DC
        case 2: goto L_9504;    // $94DC
        default: goto L_951D;    // $94DC
    }    // $94DC
L_94E9:
    goto L_94C7;    // $94EC
L_94EF:
    local10 = ?;    // $94F6
    goto L_9516;    // $9501
L_9504:
    local10 = ?;    // $950B
L_9516:
L_951D:
    local11 = (local11 + 1);    // $951F
    local10 = *(byte*)((((local11 + 1) - 1) + 0x7BAD));    // $9526
    if ((*(byte*)((((local11 + 1) - 1) + 0x7BAD)) != 0x00FF)) goto L_94D3;    // $952B
    return (*(byte*)((((local11 + 1) - 1) + 0x7BAD)) != 0x00FF);    // $952E
}

// (body @ $9534)

word sub_952F(word arg1, word arg2, word arg3, word arg4) {
    local11 = 0;    // $9535
    goto L_9546;    // $9537
L_953A:
    local11 = (local11 + *(byte*)((local10 + 0x6D2D)));    // $9543
L_9546:
    local10 = (local10 + 1);    // $9546
    if (((unsigned)local10 >= (unsigned)scenario_fief_count)) goto L_953A;    // $954C
    local11 = ((unsigned)local11 / (unsigned)scenario_fief_count);    // $9555
    return local11;    // $9557
}

// (body @ $955D)

word sub_9558(word arg1, word arg2, word arg3, word arg4) {
    local8 = 0;    // $955E
    local11 = 0;    // $9560
    local10 = 0;    // $9562
    goto L_9585;    // $9563
L_9566:
    local9 = *(word*)(((local8 * 26) + 0x700F));    // $956F
    local11 = (local11 + ((unsigned)local9 / (unsigned)scenario_fief_count));    // $9578
    local10 = (local10 + ((unsigned)local9 % (unsigned)scenario_fief_count));    // $9581
    local8 = (local8 + 1);    // $9584
L_9585:
    if (((unsigned)local8 >= (unsigned)scenario_fief_count)) goto L_9566;    // $958A
    return (((unsigned)local10 / (unsigned)scenario_fief_count) + local11);    // $9594
}

// (body @ $959A)

word sub_9595(word arg1, word arg2, word arg3, word arg4) {
    local11 = ((arg1 * 26) + 0x7001);    // $95B3
    arg1 = 0x7001;    // $95BB
    local10 = pct_op((((((min_word(*(word*)((local11 + 18)), 100) * 3) / 10) + ((min_word(*(byte*)((fief_to_daimyo_record_addr(rng_mod(31)) + 4)), 0x00C8) * 3) / 20)) + ((min_word(*(byte*)((fief_to_daimyo_record_addr(rng_mod(31)) + 4)), 0x00C8) * 3) / 20)) + 10), *(word*)((local11 + 16)));    // $95EE
    local9 = (*(word*)((local11 + 16)) - local10);    // $95F5
    local9 = local10;    // $95F6
    local10 = local10;    // $95F7
    if (((local10 == local9))) return (rng_mod(2) == 0);    // $9605
    return (local10 < local9);    // $9613
}

// (body @ $9619)

word sub_9614(word arg1, word arg2, word arg3, word arg4) {
    arg2 = ?;    // $961A
    arg1 = ?;    // $961B
    return append_candidate_entry_6f67(/*via arg2*/ ?, /*via arg2*/ ?, 1);    // $9620
}

// (body @ $9626)

word sub_9621(word arg1, word arg2, word arg3, word arg4) {
    goto L_9659;    // $9632
L_9635:
    local11 = ?;    // $9635
    if ((ui_helper_d772(/*stack underflow*/ regA) == 24)) {    // $963D
    if (*(byte*)((local11 + 0x6DA2))) goto L_9657;    // $9646
    fief_to_daimyo_map[local11] = 50;    // $9651
    local11 = 0x6E15;    // $9652
    }
L_9657:
L_9659:
    local11 = (local11 + 1);    // $9659
    if (((unsigned)local11 >= (unsigned)scenario_fief_count)) goto L_9635;    // $965F
    province_ai_state[selected_province_idx] = 0;    // $966B
    local10 = mem_6F4D;    // $966F
    *(byte*)(fp - 5) = mem_6DA1;    // $9673
    mem_6DA1 = (mem_6DA1 | 0);    // $9680
    mem_6DA1 = *(byte*)(fp - 5);    // $969F
    mem_6F65 = 0;    // $96A3
    return mem_6F7D;    // $96AF
}

// (body @ $96B5)

word sub_96B0(word arg1, word arg2, word arg3, word arg4) {
    local10 = 0;    // $96B6
    if ((scenario_fief_count == 50)) {    // $96BD
    if ((arg1 == 30)) {    // $96C4
    arg1 = 30;    // $96C7
    if ((ui_helper_d772(/*via arg1*/ 30) == 24)) {    // $96CF
    if ((*(byte*)(fief_to_daimyo_record_addr(30)) <= 40)) {    // $96DC
    local8 = selected_province_idx;    // $96E2
    if (cur_flag_and_selected_ai_state5()) {    // $96EB
    if ((mem_6DA1 & 2)) goto L_976E;    // $96F3
    goto L_9734;    // $9708
L_970B:
    if ((mem_6F81 > 0x270F)) {    // $9729
    }
L_9732:
L_9734:
    local11 = (local11 + 1);    // $9734
    if ((*(byte*)(local11) != 0x00FF)) goto L_970B;    // $973B
    if ((mem_6F81 > *(word*)(((selected_province_idx * 26) + 0x7011)))) {    // $974F
    if (((unsigned)ui_helper_e510(1) < (unsigned)3)) {    // $9759
    mem_6DA1 = (mem_6DA1 | 0);    // $9762
    local10 = 0;    // $976D
    }
    }
    }
L_976E:
    if (local10) goto L_9776;    // $976F
    }
    }
    }
    }
L_9776:
    return local10;    // $9777
}

// (body @ $977D)

word sub_9778(word arg1, word arg2, word arg3, word arg4) {
    local7 = 0;    // $977E
    goto L_986E;    // $9782
L_9785:
    if (sub_96B0(*(byte*)(local11))) goto L_9878;    // $978C
    if (cur_flag_and_selected_ai_state5()) {    // $979D
    local7 = (local7 + 1);    // $97A2
    } else {
    if (!(sub_9595(*(byte*)(local11)))) goto L_9819;    // $97B6
    local10 = (*(byte*)(local11) + 0x6E15);    // $97C9
    if (!(*(byte*)((*(byte*)(local11) + 0x6DA2)))) goto L_97FC;    // $97D1
    *(byte*)((*(byte*)(local11) + 0x6DA2)) = 0;    // $97F1
    goto L_9806;    // $97F9
L_97FC:
    *(byte*)((*(byte*)(local11) + 0x6E7F)) = *(byte*)(local10);    // $9805
L_9806:
    *(byte*)((*(byte*)(local11) + 0x6CF7)) = 0;    // $9815
    goto L_9869;    // $9816
L_9819:
    local5 = ((*(byte*)(local11) * 26) + 0x7001);    // $9829
    *(word*)((local5 + 18)) = (*(word*)((local5 + 18)) + ((pct_op((rng_mod(10) + 30), *(word*)((local5 + 18))) + rng_mod(30)) + 30));    // $984E
    *(word*)((local5 + 16)) = (*(word*)((local5 + 16)) - pct_op((rng_mod(20) + 10), *(word*)((local5 + 16))));    // $9868
L_9869:
    }
L_986C:
L_986E:
    local11 = (local11 + 1);    // $986E
    if ((*(byte*)(local11) != 0x00FF)) goto L_9785;    // $9875
L_9878:
    return (*(byte*)(local11) != 0x00FF);    // $9878
    }
}

// (body @ $987E)

word sub_9879(word arg1, word arg2, word arg3, word arg4) {
    goto L_9898;    // $9881
L_9884:
    if ((*(byte*)(local11) == *(byte*)(fp + 11))) {    // $988C
    local11 = *(byte*)(fp + 11);    // $988F
    *(byte*)(*(byte*)(fp + 11)) = -56;    // $9892
    } else {
L_9898:
    local11 = (local11 + 1);    // $9898
    if ((*(byte*)(local11) != 0x00FF)) goto L_9884;    // $989F
    }
L_98A2:
    return (*(byte*)(local11) != 0x00FF);    // $98A2
    }
}

// (body @ $98A8)

word sub_98A3(word arg1, word arg2, word arg3, word arg4) {
    fief_to_daimyo_map[arg4] = arg1;    // $98AF
    *(byte*)((arg4 + 0x6DA2)) = arg2;    // $98B7
    province_ai_state[arg4] = arg3;    // $98BF
    arg4 = 0x6CF7;    // $98C0
    return find_record_9e3c(/*via arg4*/ 0x6CF7);    // $98C5
}

// (body @ $98CB)

word sub_98C6(word arg1, word arg2, word arg3, word arg4) {
    local10 = (fp - 54);    // $98D9
    local11 = 0x6F4F;    // $98DD
    *(word*)(fp - 56) = 0;    // $98DF
    goto L_9906;    // $98E1
L_98E4:
    if ((*(byte*)(local11) == 0x00FF)) goto L_990D;    // $98EA
    local10 = (local10 + 1);    // $98EF
    *(byte*)(((local10 + 1) - 1)) = *(byte*)(local11);    // $98F4
    local11 = (local11 + 1);    // $98FE
    *(word*)(fp - 56) = (*(word*)(fp - 56) + 1);    // $9903
L_9906:
    if (((unsigned)*(word*)(fp - 56) >= (unsigned)arg1)) goto L_98E4;    // $990A
L_990D:
    if (((unsigned)*(word*)(fp - 56) >= (unsigned)arg1)) {    // $9911
    goto L_992A;    // $9918
L_991B:
    local10 = (local10 + 1);    // $991D
    *(byte*)(((local10 + 1) - 1)) = *(byte*)(arg2);    // $9922
    arg2 = *(word*)(fp - 56);    // $9923
    *(byte*)(*(word*)(fp - 56)) = -56;    // $9926
L_992A:
    *(word*)(fp - 58) = (*(word*)(fp - 58) - 1);    // $992A
    goto L_9944;    // $992C
L_992F:
    if ((*(byte*)(arg2) != 0x00C8)) goto L_991B;    // $9935
    arg2 = (arg2 + 1);    // $993A
L_993B:
    if ((*(byte*)(arg2) != 0x00FF)) goto L_992F;    // $9941
L_9944:
    if (((unsigned)*(word*)(fp - 58) > (unsigned)0)) goto L_993B;    // $9948
    }
L_994B:
    local10 = 0;    // $994B
    *(byte*)(0) = -1;    // $994E
    goto L_9969;    // $9952
L_9955:
L_9969:
    local10 = (local10 + 1);    // $9969
    if ((*(byte*)(local10) != 0x00FF)) goto L_9955;    // $9970
    return (*(byte*)(local10) != 0x00FF);    // $9973
}

// (body @ $9979)

word sub_9974(word arg1, word arg2, word arg3, word arg4) {
    local11 = 0;    // $997A
    goto L_99A6;    // $997B
L_997E:
    if ((*(byte*)(arg2) == 0x00FF)) goto L_99AA;    // $9984
    if ((*(byte*)(arg2) != 0x00C8)) {    // $998D
    local11 = 0x00C8;    // $9994
    arg3 = 0x00C8;    // $9995
    arg2 = 0x00C8;    // $999A
    *(byte*)(0x00C8) = -56;    // $999D
    local11 = 0;    // $999F
    arg1 = (arg1 - 1);    // $99A2
    }
L_99A3:
    arg2 = (arg2 + 1);    // $99A5
L_99A6:
    if (arg1) goto L_997E;    // $99A7
L_99AA:
    return arg1;    // $99AA
}

// (body @ $99B0)

word sub_99AB(word arg1, word arg2, word arg3, word arg4) {
    if ((mem_6F57 == selected_province_idx)) {    // $99BF
    province_ai_state[selected_province_idx] = 0;    // $99CB
    goto L_99F8;    // $99DA
L_99DD:
    local11 = 0x6CF7;    // $99DD
    if (!((ui_helper_d772(/*stack underflow*/ regA) == 50))) goto L_99F6;    // $99E5
    fief_to_daimyo_map[local11] = 24;    // $99F0
    local11 = 0x6E15;    // $99F1
L_99F6:
L_99F8:
    local11 = (local11 + 1);    // $99F8
    if (((unsigned)local11 >= (unsigned)scenario_fief_count)) goto L_99DD;    // $99FE
    } else {
    province_ai_state[selected_province_idx] = 0;    // $9A0D
    local10 = (ui_helper_e510(1) + 1);    // $9A19
    local11 = ((unsigned)local10 / (unsigned)3);    // $9A1D
    local11 = 3;    // $9A2D
    mem_6E33 = 51;    // $9A44
    mem_6DC0 = 0;    // $9A48
    mem_6D15 = 0;    // $9A4C
    local8 = 0;    // $9A56
L_9A57:
    if (!((*(byte*)((local8 + 0x7FD5)) == 24))) goto L_9A6C;    // $9A60
    *(byte*)((local8 + 0x7FD5)) = 51;    // $9A6B
L_9A6C:
    local8 = (local8 + 1);    // $9A6E
    if (((unsigned)local8 >= (unsigned)8)) goto L_9A57;    // $9A72
    }
L_9A9E:
    return map_helper_e5f2(6);    // $9AAB
    }
}

// (body @ $9AB1)

word sub_9AAC(word arg1, word arg2, word arg3, word arg4) {
    local11 = diplomacy_helper();    // $9AB4
    if (diplomacy_helper()) {    // $9AB5
    local11 = ?;    // $9AC2
    if (ui_helper_d3a7()) {    // $9AD2
    local11 = ?;    // $9ADA
    *(word*)(((selected_province_idx * 26) + 0x7001)) = (*(word*)(((selected_province_idx * 26) + 0x7001)) + 0x7001);    // $9AE9
    local11 = 0x7001;    // $9AF4
    *(word*)(((battle_defending_province * 26) + 0x7001)) = (*(word*)(((battle_defending_province * 26) + 0x7001)) - 0x7001);    // $9B03
    } else {
    }
L_9B0E:
L_9B11:
    return confirm_prompt();    // $9B11
    }
    }
}

// (body @ $9B17)

word sub_9B12(word arg1, word arg2, word arg3, word arg4) {
    goto L_9B71;    // $9B18
L_9B1B:
    if (!(*(byte*)((selected_province_idx + 0x6DA2)))) goto L_9B6D;    // $9B23
    if (get_province_ai_state(selected_province_idx)) goto L_9B6D;    // $9B2D
    goto L_9B63;    // $9B36
L_9B39:
    if (cur_flag_and_selected_ai_state5()) {    // $9B47
    if (rest_turns_remaining[ui_helper_d77e()]) goto L_9B5B;    // $9B52
    } else {
L_9B63:
    local11 = (local11 + 1);    // $9B63
    if ((*(byte*)(local11) != 0x00FF)) goto L_9B39;    // $9B6A
L_9B6D:
L_9B71:
    if (((unsigned)selected_province_idx >= (unsigned)scenario_fief_count)) goto L_9B1B;    // $9B7B
    }
L_9B7E:
    return ((unsigned)selected_province_idx >= (unsigned)scenario_fief_count);    // $9B7E
    }
}

// (body @ $9B84)

word sub_9B7F(word arg1, word arg2, word arg3, word arg4) {
    local11 = marry_helper_e315();    // $9B87
    if (marry_helper_e315()) {    // $9B88
    local11 = ?;    // $9B9A
    if (ui_helper_d3a7()) {    // $9BA5
    local11 = ?;    // $9BAD
    *(word*)(((selected_province_idx * 26) + 0x7001)) = (*(word*)(((selected_province_idx * 26) + 0x7001)) + 0x7001);    // $9BBC
    local11 = 0x7001;    // $9BC7
    *(word*)(((battle_defending_province * 26) + 0x7001)) = (*(word*)(((battle_defending_province * 26) + 0x7001)) - 0x7001);    // $9BD6
    } else {
    }
L_9BE1:
L_9BE4:
    return confirm_prompt();    // $9BE4
    }
    }
}

// (body @ $9BEA)

word sub_9BE5(word arg1, word arg2, word arg3, word arg4) {
    goto L_9C18;    // $9BEB
L_9BEE:
    local10 = rng_mod(scenario_fief_count);    // $9BF5
    local10 = ?;    // $9BF6
    if (get_province_ai_state(/*stack underflow*/ regA)) goto L_9C16;    // $9BFB
    if (rest_turns_remaining[ui_helper_d77e()]) goto L_9C16;    // $9C09
    goto L_9C21;    // $9C13
L_9C16:
L_9C18:
    local11 = (local11 + 1);    // $9C18
    if (((unsigned)local11 >= (unsigned)scenario_fief_count)) goto L_9BEE;    // $9C1E
L_9C21:
    return ((unsigned)local11 >= (unsigned)scenario_fief_count);    // $9C21
}

// (body @ $9C27)

word sub_9C22(word arg1, word arg2, word arg3, word arg4) {
    local10 = 0;    // $9C28
    if (rng_mod(2)) {    // $9C2E
    goto L_9C7A;    // $9C32
L_9C35:
    if ((rng_mod(20) < 3)) {    // $9C3D
    local11 = 3;    // $9C40
    if (get_province_ai_state(/*stack underflow*/ regA)) goto L_9C78;    // $9C45
    local10 = (local10 + 1);    // $9C50
    if (!(((unsigned)((local10 + 1) - 1) >= (unsigned)(-mem_6E09)))) goto L_9C78;    // $9C54
    } else {
L_9C7A:
    local11 = (local11 + 1);    // $9C7A
    if (((unsigned)local11 >= (unsigned)scenario_fief_count)) goto L_9C35;    // $9C80
    }
L_9C83:
    return ((unsigned)local11 >= (unsigned)scenario_fief_count);    // $9C83
    }
    }
}

// (body @ $9C89)

word sub_9C84(word arg1, word arg2, word arg3, word arg4) {
    if (!(rng_mod(2))) goto L_9CA6;    // $9C8E
    switch (rng_mod(4)) {    // $9C96
        case 0: goto L_9CA3;    // $9C96
        case 1: goto L_9CA7;    // $9C96
        default: goto L_9CAD;    // $9C96
    }    // $9C96
L_9CA3:
L_9CA6:
    return sub_9BE5();    // $9CA6
L_9CA7:
    goto L_9CA6;    // $9CAA
L_9CAD:
    goto L_9CA6;    // $9CB0
}

// (body @ $9CB8)

word sub_9CB3(word arg1, word arg2, word arg3, word arg4) {
    goto L_9CF5;    // $9CC1
L_9CC4:
    local10 = ((*(byte*)(local11) * 26) + 0x7001);    // $9CCD
    *(word*)((local10 + 14)) = (*(word*)((local10 + 14)) - (rng_mod(4) + 1));    // $9CDB
    *(word*)((local10 + 8)) = pct_op(pct_op(90, *(word*)((local10 + 10))), *(word*)((local10 + 8)));    // $9CF2
L_9CF5:
    local11 = (local11 + 1);    // $9CF5
    if ((*(byte*)(local11) != 0x00FF)) goto L_9CC4;    // $9CFC
    return (*(byte*)(local11) != 0x00FF);    // $9CFF
}

// (body @ $9D05)

word sub_9D00(word arg1, word arg2, word arg3, word arg4) {
    goto L_9D7B;    // $9D0E
L_9D11:
    local10 = ((*(byte*)(local11) * 26) + 0x7001);    // $9D1A
    *(word*)((local10 + 16)) = pct_op((rng_mod(50) + 50), *(word*)((local10 + 16)));    // $9D31
    *(word*)((local10 + 8)) = pct_op((rng_mod(50) + 50), *(word*)((local10 + 8)));    // $9D46
    if (*(byte*)((*(byte*)(local11) + 0x6DA2))) {    // $9D4E
    local9 = fief_to_daimyo_record_addr(*(byte*)(local11));    // $9D5F
    *(byte*)((ui_helper_d772(*(byte*)(local11)) + 0x6DD4)) = (*(byte*)((local9 + 1)) >= 50);    // $9D78
    }
L_9D79:
L_9D7B:
    local11 = (local11 + 1);    // $9D7B
    if ((*(byte*)(local11) != 0x00FF)) goto L_9D11;    // $9D82
    return (*(byte*)(local11) != 0x00FF);    // $9D85
}

// (body @ $9D8B)

word sub_9D86(word arg1, word arg2, word arg3, word arg4) {
    if ((arg1 > 50)) {    // $9D8F
    arg1 = 50;    // $9D94
    }
L_9D95:
    return ((arg1 * arg1) < rng_mod(0x07E9));    // $9DA2
}

// (body @ $9DA8)

word sub_9DA3(word arg1, word arg2, word arg3, word arg4) {
    if (sub_9D86(*(word*)(((arg1 * 26) + 0x700D)))) goto L_9DE9;    // $9DBA
    if (sub_9D86((100 - *(byte*)((arg1 + 0x6D2D))))) goto L_9DE9;    // $9DCD
    arg1 = *(byte*)((arg1 + 0x6D2D));    // $9DD0
    if (sub_9D86(*(byte*)((fief_to_daimyo_record_addr(/*via arg1*/ *(byte*)((arg1 + 0x6D2D))) + 4)))) goto L_9DE9;    // $9DDC
    if (rng_mod(0x03E8)) goto L_9E1B;    // $9DE6
L_9DE9:
    if (!((*(word*)(((arg1 * 26) + 0x7009)) > 0))) goto L_9E1B;    // $9DF4
    if (!((*(word*)(((arg1 * 26) + 0x7011)) > 2))) goto L_9E1B;    // $9E02
    if (tax_helper_db12()) goto L_9E1B;    // $9E08
    arg1 = 2;    // $9E0B
    if (province_state_is_FF(/*via arg1*/ 2)) goto L_9E1B;    // $9E10
    if (rng_mod(4)) {    // $9E18
L_9E1B:
    } else {
    }
L_9E20:
    return 0;    // $9E20
    }
}

// (body @ $9E26)

word sub_9E21(word arg1, word arg2, word arg3, word arg4) {
    if (sub_9D86(*(word*)(((arg1 * 26) + 0x7013)))) goto L_9E60;    // $9E38
    arg1 = 0x7013;    // $9E3B
    if (sub_9D86(*(byte*)((fief_to_daimyo_record_addr(/*via arg1*/ 0x7013) + 4)))) goto L_9E60;    // $9E47
    if (tax_helper_db12()) {    // $9E4D
    } else {
    }
L_9E58:
    if (rng_mod(0x03E8)) goto L_9E76;    // $9E5D
L_9E60:
    if (!((*(word*)(((arg1 * 26) + 0x7011)) > 2))) goto L_9E76;    // $9E6B
    arg1 = 2;    // $9E6E
    if (province_state_is_FF(/*via arg1*/ 2)) {    // $9E73
L_9E76:
    } else {
    }
L_9E7B:
    return 0;    // $9E7B
    }
    }
}

// (body @ $9E81)

word sub_9E7C(word arg1, word arg2, word arg3, word arg4) {
    arg2 = ?;    // $9E81
    if (!(!(province_state_is_FF(/*via arg2*/ ?)))) return 0;    // $9E86
    if ((arg1 == 1)) {    // $9E8E
    arg2 = 1;    // $9E91
    return sub_9DA3(/*via arg2*/ 1);    // $9E96
    }
L_9E97:
    arg2 = 1;    // $9E97
    return sub_9E21(/*via arg2*/ 1);    // $9E9C
}

// (body @ $9EA2)

word sub_9E9D(word arg1, word arg2, word arg3, word arg4) {
    local9 = 0;    // $9EA3
    local11 = 0x7BAD;    // $9EA7
    goto L_9ECA;    // $9EA9
L_9EAC:
    arg1 = 0x6F1B;    // $9EB3
    if (sub_9E7C(/*via arg1*/ 0x6F1B, *(byte*)((local10 + 0x6F1B)))) {    // $9EB8
    local11 = 0x6F1B;    // $9EBB
    *(byte*)(0x6F1B) = *(byte*)((local10 + 0x6F1B));    // $9EC2
    local11 = (local11 + 1);    // $9EC5
    local9 = 0;    // $9EC7
    }
L_9EC8:
L_9ECA:
    local10 = (local10 + 1);    // $9ECA
    if (((unsigned)local10 >= (unsigned)scenario_fief_count)) goto L_9EAC;    // $9ED0
    local11 = scenario_fief_count;    // $9ED3
    *(byte*)(scenario_fief_count) = -1;    // $9ED6
    return local9;    // $9ED8
}

// (body @ $9EDE)

word sub_9ED9(word arg1, word arg2, word arg3, word arg4) {
    local11 = 0;    // $9EDF
    local10 = rng_mod(2);    // $9EE5
    goto L_9F00;    // $9EE7
L_9EEA:
    if (sub_9E9D((local10 + 1))) {    // $9EF1
    local11 = 0;    // $9EF5
    } else {
    local10 = (local10 ^ 0);    // $9EFD
L_9F00:
    local9 = (local9 + 1);    // $9F00
    if (((unsigned)local9 >= (unsigned)2)) goto L_9EEA;    // $9F04
    }
L_9F07:
    if ((local11 == 1)) {    // $9F0A
L_9F10:
    return sub_9C84();    // $9F10
    }
L_9F11:
    switch (local10) {    // $9F12
        case 0: goto L_9F1F;    // $9F12
        case 1: goto L_9F3B;    // $9F12
        default: goto L_9F10;    // $9F12
    }    // $9F12
L_9F1F:
    goto L_9F10;    // $9F38
L_9F3B:
    goto L_9F10;    // $9F54
    }
}

// (body @ $9F5C)

word sub_9F57(word arg1, word arg2, word arg3, word arg4) {
    arg1 = ?;    // $9F5C
    local11 = (sub_946D(/*via arg1*/ ?) / 10);    // $9F63
    if (rng_mod(2)) {    // $9F69
    arg2->wealth = (arg2->wealth + (rng_mod(10) + local11));    // $9F7A
    arg2->loyalty = (arg2->loyalty + (rng_mod(40) + local11));    // $9F8A
    }
L_9F8B:
    return (arg2->loyalty + (rng_mod(40) + local11));    // $9F8B
}

// (body @ $9F91)

word sub_9F8C(word arg1, word arg2, word arg3, word arg4) {
    if ((mem_6D9F != 0x0618)) {    // $9F98
    local11 = 0;    // $9FA6
    local9 = daimyo_record_addr(0);    // $9FAC
    goto L_9FC4;    // $9FAD
L_9FB0:
    *(byte*)(local9) = (*(byte*)(local9) + 1);    // $9FB4
    *(byte*)((local9 + 1)) = (*(byte*)((local9 + 1)) - 1);    // $9FBA
    local11 = (local11 + 1);    // $9FBD
    local9 = (local9 + 7);    // $9FC1
L_9FC4:
    if (((unsigned)local11 >= (unsigned)(scenario_fief_count + 3))) goto L_9FB0;    // $9FCC
    goto L_A02B;    // $9FD0
L_9FD3:
    local11 = (scenario_fief_count + 3);    // $9FD3
    if (get_province_ai_state(/*stack underflow*/ regA)) goto L_9FE9;    // $9FD8
    local11 = 0x7001;    // $9FE4
L_9FE9:
    local10 = ((local11 * 26) + 0x700D);    // $9FF1
    local11 = 0x700D;    // $9FF2
    if (!(get_province_ai_state(/*stack underflow*/ regA))) goto L_A029;    // $9FF7
    if ((const_two == 1)) goto L_A029;    // $9FFF
    local8 = rng_mod(const_two);    // $A009
    local8 = 1;    // $A00A
    local10 = (local10 + 2);    // $A00D
    *(word*)(((local10 + 2) + -2)) = (*(word*)(((local10 + 2) + -2)) - 1);    // $A014
    local8 = 1;    // $A015
    local10 = (local10 + 2);    // $A018
    *(word*)(((local10 + 2) + -2)) = (*(word*)(((local10 + 2) + -2)) - 1);    // $A01F
    local8 = 1;    // $A020
    local10 = (local10 + 2);    // $A023
    *(word*)((local10 + 2)) = (*(word*)((local10 + 2)) - 1);    // $A028
L_A029:
L_A02B:
    local11 = (local11 + 1);    // $A02B
    if (((unsigned)local11 >= (unsigned)scenario_fief_count)) goto L_9FD3;    // $A031
    } else {
    if (!(get_province_ai_state(24))) goto L_A04E;    // $A03D
    if ((scenario_fief_count != 50)) goto L_A04E;    // $A046
L_A04E:
    if (!(get_province_ai_state(16))) goto L_A065;    // $A054
    if ((scenario_fief_count != 17)) goto L_A065;    // $A05D
    }
L_A065:
    return mem_71A1;    // $A065
    }
}

// (body @ $A06B)

word sub_A066(word arg1, word arg2, word arg3, word arg4) {
    goto L_A09F;    // $A071
L_A074:
    local9 = ((local11 << 3) + 0x6003);    // $A07B
    local8 = ((local11 * 26) + 0x7009);    // $A084
    local10 = 0;    // $A086
L_A087:
    local9 = (local9 + 2);    // $A089
    local8 = (local8 + 2);    // $A08F
    *(word*)(((local9 + 2) + -2)) = *(word*)(((local8 + 2) + -2));    // $A093
    local10 = (local10 + 1);    // $A096
    if (((unsigned)local10 >= (unsigned)4)) goto L_A087;    // $A09A
L_A09F:
    local11 = (local11 + 1);    // $A09F
    if (((unsigned)local11 >= (unsigned)scenario_fief_count)) goto L_A074;    // $A0A5
    return ((unsigned)local11 >= (unsigned)scenario_fief_count);    // $A0A8
}

// (body @ $A0AE)

word sub_A0A9(word arg1, word arg2, word arg3, word arg4) {
    local11 = ((arg1 * 26) + 0x7001);    // $A0B6
    local10 = *(word*)((local11 + 8));    // $A0BA
    if ((*(word*)(((arg1 << 3) + 0x6003)) <= *(word*)((local11 + 8)))) {    // $A0C6
    *(word*)(((arg1 << 3) + 0x6003)) = local10;    // $A0D2
    }
L_A0D3:
    local10 = *(word*)((local11 + 10));    // $A0D6
    if ((*(word*)(((arg1 << 3) + 0x6005)) <= *(word*)((local11 + 10)))) {    // $A0E2
    *(word*)(((arg1 << 3) + 0x6005)) = local10;    // $A0EE
    }
L_A0EF:
    local10 = *(word*)((local11 + 12));    // $A0F2
    if ((*(word*)(((arg1 << 3) + 0x6007)) <= *(word*)((local11 + 12)))) {    // $A0FE
    *(word*)(((arg1 << 3) + 0x6007)) = local10;    // $A10A
    }
L_A10B:
    local10 = *(word*)((local11 + 14));    // $A10E
    if ((*(word*)(((arg1 << 3) + 0x6009)) <= *(word*)((local11 + 14)))) {    // $A11A
    *(word*)(((arg1 << 3) + 0x6009)) = local10;    // $A126
    }
L_A127:
    return local10;    // $A127
}

// (body @ $A12D)

word sub_A128(word arg1, word arg2, word arg3, word arg4) {
    arg1 = ?;    // $A12D
    local11 = (sub_946D(/*via arg1*/ ?) / 10);    // $A134
    *(word*)(arg2) = (*(word*)(arg2) + (rng_mod(10) + local11));    // $A142
    if (rng_mod(2)) {    // $A148
    arg2->output = (arg2->output + (rng_mod(10) + local11));    // $A159
    }
L_A15A:
    return (arg2->output + (rng_mod(10) + local11));    // $A15A
}

// (body @ $A160)

word sub_A15B(word arg1, word arg2, word arg3, word arg4) {
    local11 = (arg1->men / 2);    // $A166
    local10 = min_word(arg1->rice, *(word*)(arg1));    // $A172
    if ((min_word(arg1->rice, *(word*)(arg1)) < local11)) {    // $A175
    local11 = local10;    // $A179
    arg1->men = (local10 << 1);    // $A180
    }
L_A181:
    local11 = local11;    // $A181
    *(word*)(arg1) = (*(word*)(arg1) - local11);    // $A187
    local11 = local11;    // $A188
    arg1->rice = (arg1->rice - local11);    // $A18F
    return (arg1->rice - local11);    // $A190
}

// (body @ $A196)

word sub_A191(word arg1, word arg2, word arg3, word arg4) {
    arg1 = 0x6D2D;    // $A19D
    return pct_op(/*stack underflow*/ regA, (sub_946D(*(byte*)((arg1 + 0x6D2D))) / 2));    // $A1A9
}

// (body @ $A1AF)

word sub_A1AA(word arg1, word arg2, word arg3, word arg4) {
    return (pct_op(*(byte*)((arg1 + 0x6D2D)), *(word*)(((arg1 << 3) + 0x6009))) + pct_op(*(byte*)((arg1 + 0x6D2D)), pct_op(40, *(word*)(((arg1 << 3) + 0x6007)))));    // $A1E1
}

// (body @ $A1E7)

word sub_A1E2(word arg1, word arg2, word arg3, word arg4) {
    arg1 = ?;    // $A1E7
    arg1 = 0x6D2D;    // $A203
    local11 = ((sub_A1AA(pct_op(*(byte*)((arg1 + 0x6D2D)), arg2->town)) + rng_mod((sub_A191(/*via arg1*/ ?) + 1))) + rng_mod((sub_A191(/*via arg1*/ ?) + 1)));    // $A20C
    if ((local11 > arg2->header)) {    // $A215
    local11 = arg2->header;    // $A21C
    }
L_A21D:
    return local11;    // $A21E
}

// (body @ $A224)

word sub_A21F(word arg1, word arg2, word arg3, word arg4) {
    arg1 = ?;    // $A224
    arg1 = 0x6003;    // $A253
    local11 = ((sub_A1AA(pct_op(*(byte*)((arg1 + 0x6D2D)), pct_op(*(word*)(((arg1 << 3) + 0x6005)), *(word*)(((arg1 << 3) + 0x6003))))) + rng_mod((sub_A191(/*via arg1*/ ?) + 1))) + rng_mod((sub_A191(/*via arg1*/ ?) + 1)));    // $A25C
    if ((local11 > arg2->header)) {    // $A265
    local11 = arg2->header;    // $A26C
    }
L_A26D:
    return local11;    // $A26E
}

// (body @ $A274)

word sub_A26F(word arg1, word arg2, word arg3, word arg4) {
    goto L_A2D5;    // $A27A
L_A27D:
    local10 = ?;    // $A27D
    local11 = ((local10 * 26) + 0x7001);    // $A28A
    local10 = 0x7001;    // $A28B
    if (get_province_ai_state(/*stack underflow*/ regA)) goto L_A299;    // $A290
    local11 = 0x7001;    // $A293
    local10 = 0x7001;    // $A294
L_A299:
    if (*(word*)((local11 + 12))) {    // $A29C
    local9 = *(byte*)((local10 + 0x6D2D));    // $A2A5
    local11 = 0x6D2D;    // $A2A6
    local10 = 0x6D2D;    // $A2A7
    *(word*)(local11) = (*(word*)(local11) + sub_A1E2(/*stack underflow*/ regA, /*stack underflow*/ regA));    // $A2B2
    local11 = sub_A1E2(/*stack underflow*/ regA, /*stack underflow*/ regA);    // $A2B3
    local10 = sub_A1E2(/*stack underflow*/ regA, /*stack underflow*/ regA);    // $A2B4
    *(word*)((local11 + 6)) = (*(word*)((local11 + 6)) + sub_A21F(/*stack underflow*/ regA, /*stack underflow*/ regA));    // $A2C0
    }
L_A2C1:
    local11 = sub_A21F(/*stack underflow*/ regA, /*stack underflow*/ regA);    // $A2C4
    local11 = sub_A21F(/*stack underflow*/ regA, /*stack underflow*/ regA);    // $A2C9
    local10 = sub_A21F(/*stack underflow*/ regA, /*stack underflow*/ regA);    // $A2CE
L_A2D5:
    local10 = (local10 + 1);    // $A2D5
    if (((unsigned)local10 >= (unsigned)scenario_fief_count)) goto L_A27D;    // $A2DB
    return ((unsigned)local10 >= (unsigned)scenario_fief_count);    // $A2DE
}

// (body @ $A2E4)

word sub_A2DF(word arg1, word arg2, word arg3, word arg4) {
    return (rng_mod(100) < 3);    // $A2EC
}

// (body @ $A2F2)

word sub_A2ED(word arg1, word arg2, word arg3, word arg4) {
    arg1 = ?;    // $A2F2
    local11 = (daimyo_record_addr(/*via arg1*/ ?) + 3);    // $A2F8
    *(byte*)(local11) = (*(byte*)(local11) + rng_mod(11));    // $A304
    *(byte*)(local11) = (*(byte*)(local11) - 5);    // $A30B
    return (*(byte*)(local11) - 5);    // $A30C
}

// (body @ $A312)

word sub_A30D(word arg1, word arg2, word arg3, word arg4) {
    goto L_A349;    // $A313
L_A316:
    local11 = ?;    // $A316
    if (((unsigned)*(byte*)((local11 + 0x6D2D)) < (unsigned)(90 - const_two))) {    // $A32A
    *(word*)(((local11 * 26) + 0x700D)) = pct_op(90, *(word*)(((local11 * 26) + 0x700D)));    // $A346
    }
L_A347:
L_A349:
    local11 = (local11 + 1);    // $A349
    if (((unsigned)local11 >= (unsigned)scenario_fief_count)) goto L_A316;    // $A34F
    mem_6F67 = -1;    // $A369
    switch (config_block) {    // $A36F
        case 0: goto L_A37E;    // $A36F
        case 1: goto L_A385;    // $A36F
        case 2: goto L_A38B;    // $A36F
        case 3: goto L_A391;    // $A36F
        default: goto L_A381;    // $A36F
    }    // $A36F
L_A37E:
L_A381:
    goto L_A3A0;    // $A382
L_A385:
    goto L_A381;    // $A388
L_A38B:
    goto L_A381;    // $A38E
L_A391:
    goto L_A381;    // $A396
L_A399:
    local11 = scenario_fief_count;    // $A399
L_A3A0:
    local11 = (local11 + 1);    // $A3A0
    if (((unsigned)local11 >= (unsigned)scenario_fief_count)) goto L_A399;    // $A3A6
    return ((unsigned)local11 >= (unsigned)scenario_fief_count);    // $A3A9
}

// (body @ $A3AF)

word sub_A3AA(word arg1, word arg2, word arg3, word arg4) {
    local9 = mem_6F61;    // $A3B2
    local9 = ?;    // $A3B9
    local10 = syscall_dispatch(/*stack underflow*/ regA, 0x00FF, 0x6001, 0, 22);    // $A3C1
    local11 = 0x6100;    // $A3C5
L_A3C6:
    local11 = ?;    // $A3C9
    local9 = ?;    // $A3CA
    local10 = (local10 + syscall_dispatch(/*stack underflow*/ regA, /*stack underflow*/ regA, 0x0100, 0, 22));    // $A3D5
    local11 = (local11 + 0x0100);    // $A3DC
    if (((unsigned)local11 >= (unsigned)0x7000)) goto L_A3C6;    // $A3E2
    local9 = 0x7000;    // $A3EB
    local10 = (local10 + syscall_dispatch(/*stack underflow*/ regA, 0x00FF, province_table_live, 0, 22));    // $A3F6
    local11 = 0x7100;    // $A3FA
L_A3FB:
    local11 = syscall_dispatch(/*stack underflow*/ regA, 0x00FF, province_table_live, 0, 22);    // $A3FE
    local9 = syscall_dispatch(/*stack underflow*/ regA, 0x00FF, province_table_live, 0, 22);    // $A3FF
    local10 = (local10 + syscall_dispatch(/*stack underflow*/ regA, /*stack underflow*/ regA, 0x0100, 0, 22));    // $A40A
    local11 = (local11 + 0x0100);    // $A411
    if (((unsigned)local11 >= (unsigned)0x7F00)) goto L_A3FB;    // $A417
    local9 = 0x7F00;    // $A420
    local10 = (local10 + syscall_dispatch(/*stack underflow*/ regA, 0x81EB, ui_transient_state, 0, 22));    // $A42B
    return confirm_prompt();    // $A454
}

// (body @ $A45A)

word sub_A455(word arg1, word arg2, word arg3, word arg4) {
    if ((mem_6E48 == 1)) {    // $A466
    } else {
    if (!(mem_6F61)) goto L_A47F;    // $A479
L_A47F:
    if (config_block) goto L_A498;    // $A48B
L_A498:
    goto L_A4AE;    // $A49C
L_A49F:
    local9 = 3;    // $A49F
    daimyo_weakness_flag[local9] = 0;    // $A4AB
L_A4AE:
    local9 = (local9 + 1);    // $A4AE
    if (((unsigned)local9 >= (unsigned)scenario_fief_count)) goto L_A49F;    // $A4B4
    if (!(!((mem_6DA1 & 0x0080)))) return (mem_6DA1 & 0x0080);    // $A4BE
    if ((config_block != 1)) goto L_A4DE;    // $A4CB
    if (!(rng_mod(2))) goto L_A4DE;    // $A4D3
    local11 = 0x9CB3;    // $A4DD
L_A4DE:
    if (mem_6F7B) goto L_A4FE;    // $A4E1
    if (rng_mod(4)) goto L_A4F6;    // $A4E9
    goto L_A4FD;    // $A4F3
L_A4F6:
L_A4FD:
    local11 = 0x9ED9;    // $A4FD
L_A4FE:
    local9 = 0;    // $A4FF
    local8 = 0;    // $A501
    goto L_A534;    // $A502
L_A505:
    local9 = 1;    // $A505
    if (province_state_is_FF(/*stack underflow*/ regA)) goto L_A531;    // $A50A
    if ((mem_6F7B == 3)) goto L_A520;    // $A512
    goto L_A523;    // $A51D
L_A520:
L_A523:
    if (!(sub_A2DF())) goto L_A531;    // $A523
    local8 = (local8 + 1);    // $A528
    *(byte*)((((local8 + 1) - 1) + 0x7BAD)) = local9;    // $A530
L_A531:
    local9 = (local9 + 1);    // $A533
L_A534:
    if (((unsigned)local9 >= (unsigned)scenario_fief_count)) goto L_A505;    // $A539
    *(byte*)((local8 + 0x7BAD)) = -1;    // $A544
    if (!(local8)) goto L_A55B;    // $A546
    if (((mem_6E48 == 1))) return (mem_6E48 == 1);    // $A557
    goto L_A5CB;    // $A55C
L_A55F:
    local9 = 1;    // $A55F
    local10 = daimyo_record_addr(/*stack underflow*/ regA);    // $A564
    if ((*(byte*)((local10 + 1)) > 99)) goto L_A5C9;    // $A56B
    local9 = 99;    // $A56E
    if (rest_turns_remaining[ui_helper_d772(/*stack underflow*/ regA)]) goto L_A5C9;    // $A578
    daimyo_weakness_flag[local9] = ((rng_mod(0x0190) < (100 - *(byte*)((local10 + 1)))) | daimyo_weakness_flag[local9]);    // $A59C
    local9 = daimyo_weakness_flag[local9];    // $A5A1
    if (!(war_helper_d972(/*stack underflow*/ regA))) goto L_A5C9;    // $A5A6
    if (!(cur_flag_and_selected_ai_state5())) goto L_A5C9;    // $A5AC
    local9 = daimyo_weakness_flag[local9];    // $A5AF
L_A5C9:
L_A5CB:
    local9 = (local9 + 1);    // $A5CB
    if (((unsigned)local9 >= (unsigned)scenario_fief_count)) goto L_A55F;    // $A5D1
    }
L_A5D4:
    return ((unsigned)local9 >= (unsigned)scenario_fief_count);    // $A5D4
    }
}

// (body @ $A5DA)

word sub_A5D5(word arg1, word arg2, word arg3, word arg4) {
    return rng_mod(((const_two + 1) * 10));    // $A5E5
}

// (body @ $A5EB)

word sub_A5E6(word arg1, word arg2, word arg3, word arg4) {
    local5 = ((battle_defending_province * 26) + 0x7001);    // $A5F5
    local10 = (((battle_defending_province * 26) + 0x7001) + 8);    // $A5F7
    local9 = (local5 + 16);    // $A5FB
    if (arg1) {    // $A5FD
    if (!((*(word*)(local10) >= 0))) goto L_A616;    // $A604
    local10 = 0;    // $A607
    *(word*)(2) = (*(word*)(local9) / 2);    // $A60C
    *(word*)(local9) = (*(word*)(local9) - *(word*)(local10));    // $A615
L_A616:
    if (!((*(word*)(local9) >= 0))) goto L_A62C;    // $A61A
    local9 = 0;    // $A61D
    *(word*)(2) = (*(word*)(local10) / 2);    // $A622
    *(word*)(local10) = (*(word*)(local10) - *(word*)(local9));    // $A62B
L_A62C:
    if (!((*(byte*)((fief_to_daimyo_record_addr(battle_defending_province) + 4)) < (rng_mod(const_two) + 70)))) goto L_A661;    // $A641
    local11 = pct_op(rng_mod(50), *(word*)(local9));    // $A652
    *(word*)(local10) = (*(word*)(local10) + pct_op(rng_mod(50), *(word*)(local9)));    // $A659
    local11 = pct_op(rng_mod(50), *(word*)(local9));    // $A65A
    *(word*)(local9) = (*(word*)(local9) - pct_op(rng_mod(50), *(word*)(local9)));    // $A660
L_A661:
L_A666:
    local9 = (local5 + 6);    // $A668
    *(word*)(local9) = (*(word*)(local9) - mem_6F7F);    // $A682
    } else {
    if (!((*(word*)(local9) > 20))) goto L_A6AB;    // $A68B
    *(word*)(local9) = (*(word*)(local9) - mem_6F81);    // $A6A7
    goto L_A666;    // $A6A8
L_A6AB:
    }
L_A6B8:
    if (arg1) {    // $A6BD
    } else {
    }
L_A6C7:
    mem_6DA1 = (mem_6DA1 | 32);    // $A6CC
    mem_6F65 = 0;    // $A6D0
    local8 = 0x7515;    // $A6D6
    local7 = local5;    // $A6D8
    local6 = 0;    // $A6DA
    goto L_A6FE;    // $A6DB
L_A6DE:
    local8 = 32;    // $A6DE
    *(word*)(32) = pct_op((rng_mod(20) + 40), *(word*)(local7));    // $A6EF
    local8 = (local8 + 2);    // $A6F2
    local7 = (local7 + 2);    // $A6F7
    local6 = (local6 + 1);    // $A6FC
L_A6FE:
    if (((unsigned)local6 >= (unsigned)8)) goto L_A6DE;    // $A701
    local8 = (local8 + 2);    // $A706
    *(word*)(((local8 + 2) + -2)) = mem_6F81;    // $A70D
    local8 = (local8 + 2);    // $A710
    *(word*)(((local8 + 2) + -2)) = (*(word*)((local5 + 24)) - *(word*)((local5 + 18)));    // $A71F
    local8 = (local8 + 2);    // $A722
    *(word*)(((local8 + 2) + -2)) = sub_A5D5();    // $A729
    local8 = *(word*)((local5 + 18));    // $A72A
    *(word*)(*(word*)((local5 + 18))) = sub_A5D5();    // $A72E
    return selected_province_idx;    // $A741
    }
    }
}

// (body @ $A747)

word sub_A742(word arg1, word arg2, word arg3, word arg4) {
    goto L_A76E;    // $A748
L_A74B:
    local11 = ?;    // $A74B
L_A76E:
    local11 = (local11 + 1);    // $A76E
    if (((unsigned)local11 >= (unsigned)scenario_fief_count)) goto L_A74B;    // $A774
    return ((unsigned)local11 >= (unsigned)scenario_fief_count);    // $A777
}

// $A778 vm_bootstrap
// (body @ $A77D)

word vm_bootstrap(word arg1, word arg2, word arg3, word arg4) {
L_A77D:
L_A785:
    if ((mem_6E48 == 1)) {    // $A791
    mem_6F67 = -1;    // $A796
    if ((mem_6DA1 & 0x0080)) goto L_A7AD;    // $A7A5
L_A7AD:
    }
L_A7B0:
    if ((mem_6DA1 & 0x0080)) goto L_A843;    // $A7B7
    if ((battle_defending_province != 0x00FF)) {    // $A7C4
    if ((mem_6F68 == 1)) {    // $A7CC
    }
L_A7D9:
    if (mem_6F68) {    // $A7DC
    } else {
    }
L_A7E4:
    if ((mem_6DA1 & 0x0080)) goto L_A7FD;    // $A7F5
L_A7FD:
    if (mem_6F79) goto L_A785;    // $A800
L_A806:
    if ((mem_6DA1 & 0x0080)) goto L_A843;    // $A812
    if (!(mem_6F79)) goto L_A839;    // $A818
    if ((mem_6DA1 & 0x0080)) goto L_A82F;    // $A827
L_A82F:
    goto L_A806;    // $A833
    goto L_A806;    // $A836
L_A839:
    if (!((mem_6DA1 & 0x0080))) goto L_A785;    // $A840
L_A843:
    goto L_A77D;    // $A846
    }
    }
}

