// ============================================================
// decompiled/bank_15.c  —  GENERATED by tools/decompile-all.py
// 135 bytecode subroutines from bank 15 of Nobunaga's Ambition (USA).nes
// Deterministic (fixed ROM -> identical C). DO NOT hand-edit — regenerate via the tool.
// Pipeline: vm-disasm.py (v2, execution-validated lengths) -> vm_decompile.py (opcode-keyed).
// ============================================================

// (body @ $CA08)

word sub_CA03(word arg1, word arg2, word arg3, word arg4) {
    return sub_CBB1(10);    // $CA11
}

// (body @ $CA17)

word sub_CA12(word arg1, word arg2, word arg3, word arg4) {
    arg1 = ?;    // $CA17
    // TODO: op_A0_A3_byte $000D
    if ((*(byte*)(arg1) < ?)) {    // $CA20
    } else {
    // TODO: op_A0_A3_byte $000D
    }
L_CA2F:
    *(byte*)(0) = (*(byte*)(arg1) - 0);    // $CA2F
    return (*(byte*)(arg1) - 0);    // $CA30
    }
}

// (body @ $CA36)

word sub_CA31(word arg1, word arg2, word arg3, word arg4) {
    local11 = (*(word*)(arg1) - arg2);    // $CA3A
    // TODO: setB_imm4_50
    if (((*(word*)(arg1) - arg2) < arg2)) {    // $CA3D
    local11 = 0;    // $CA41
    }
L_CA42:
    arg1 = arg2;    // $CA42
    *(word*)(arg2) = local11;    // $CA44
    return local11;    // $CA45
}

// (body @ $CA4B)

word sub_CA46(word arg1, word arg2, word arg3, word arg4) {
    // TODO: op_8D_sbyte +17
    return syscall_dispatch(/*stack underflow*/ regA);    // $CA51
}

// (body @ $CA57)

word sub_CA52(word arg1, word arg2, word arg3, word arg4) {
    if ((!((arg1 >= 1)))) return 0;    // $CA5A
    return (rng_next_wrapper() % arg1);    // $CA64
}

// (body @ $CA6A)

word sub_CA65(word arg1, word arg2, word arg3, word arg4) {
    if (!(((unsigned)48 <= (unsigned)arg1))) goto L_CA78;    // $CA6E
    if (((unsigned)arg1 <= (unsigned)57)) goto L_CA7C;    // $CA75
L_CA78:
    goto L_CA7D;    // $CA79
L_CA7C:
L_CA7D:
    return 0;    // $CA7D
}

// (body @ $CA83)

word sub_CA7E(word arg1, word arg2, word arg3, word arg4) {
    local11 = 0;    // $CA84
    goto L_CA90;    // $CA85
L_CA88:
    arg1 = (arg1 + 1);    // $CA8A
    local11 = (local11 + 1);    // $CA8E
L_CA90:
    if (*(byte*)(arg1)) goto L_CA88;    // $CA92
    return local11;    // $CA96
}

// (body @ $CA9C)

word sub_CA97(word arg1, word arg2, word arg3, word arg4) {
    goto L_CAAB;    // $CA9C
L_CA9F:
    arg1 = (arg1 + 1);    // $CAA1
    // TODO: op_A0_A3_byte $000F
    *(byte*)(((arg1 + 1) - 1)) = ((arg1 + 1) - 1);    // $CAA7
    arg2 = (arg2 - 1);    // $CAAA
L_CAAB:
    if (arg2) goto L_CA9F;    // $CAAC
    return arg2;    // $CAAF
}

// (body @ $CAB5)

word sub_CAB0(word arg1, word arg2, word arg3, word arg4) {
    goto L_CAC7;    // $CAB5
L_CAB8:
    if (!(*(byte*)(arg1))) return 0;    // $CABA
    arg1 = (arg1 + 1);    // $CAC1
    arg2 = (arg2 + 1);    // $CAC5
L_CAC7:
    if ((*(byte*)(arg1) == *(byte*)(arg2))) goto L_CAB8;    // $CACE
    return (*(byte*)(arg1) - *(byte*)(arg2));    // $CAD8
}

// (body @ $CADE)

word sub_CAD9(word arg1, word arg2, word arg3, word arg4) {
    local11 = arg1;    // $CADF
L_CAE0:
    arg1 = (arg1 + 1);    // $CAE2
    arg2 = (arg2 + 1);    // $CAE7
    *(byte*)(((arg1 + 1) - 1)) = *(byte*)(((arg2 + 1) - 1));    // $CAEA
    if (*(byte*)(((arg2 + 1) - 1))) goto L_CAE0;    // $CAEB
    return local11;    // $CAEF
}

// (body @ $CAF5)

word sub_CAF0(word arg1, word arg2, word arg3, word arg4) {
    goto L_CB0B;    // $CAF5
L_CAF8:
    // TODO: op_A0_A3_byte $000D
    if ((!((*(byte*)(arg1) != ?)))) return arg1;    // $CB00
    arg1 = (arg1 + 1);    // $CB07
    arg3 = (arg3 - 1);    // $CB0A
L_CB0B:
    if (arg3) goto L_CAF8;    // $CB0C
    return 0;    // $CB10
}

// (body @ $CB16)

word sub_CB11(word arg1, word arg2, word arg3, word arg4) {
    // TODO: op_A0_A3_byte $000B
    // TODO: cmp_sge
    if (!(97)) goto L_CB2A;    // $CB1E
    // TODO: op_A0_A3_byte $000B
    // TODO: cmp_sge
    if (97) goto L_CB2E;    // $CB27
L_CB2A:
    goto L_CB2F;    // $CB2B
L_CB2E:
L_CB2F:
    return 0;    // $CB2F
}

// (body @ $CB35)

word sub_CB30(word arg1, word arg2, word arg3, word arg4) {
    // TODO: op_A0_A3_byte $000B
    if (sub_CB11(?)) {    // $CB3D
    // TODO: op_A0_A3_byte $000B
    } else {
    // TODO: op_A0_A3_byte $000B
    }
L_CB4B:
    return (sub_CB11(?) + -32);    // $CB4B
    }
}

// (body @ $CB51)

word sub_CB4C(word arg1, word arg2, word arg3, word arg4) {
    // TODO: setB_imm4_50
    if ((arg1 < ?)) {    // $CB54
    // TODO: op_CB
    } else {
    }
L_CB5D:
    return arg1;    // $CB5D
    }
}

// (body @ $CB63)

word sub_CB5E(word arg1, word arg2, word arg3, word arg4) {
    if ((arg1 < arg2)) {    // $CB66
    } else {
    }
L_CB6E:
    return arg2;    // $CB6E
    }
}

// (body @ $CB74)

word sub_CB6F(word arg1, word arg2, word arg3, word arg4) {
    if ((arg1 > arg2)) {    // $CB77
    } else {
    }
L_CB7F:
    return arg2;    // $CB7F
    }
}

// (body @ $CB85)

word sub_CB80(word arg1, word arg2, word arg3, word arg4) {
    // TODO: op_A0_A3_byte $FFFF
    arg1 = ?;    // $CB8A
    *(byte*)(?) = *(byte*)(arg2);    // $CB8D
    arg2 = ?;    // $CB8E
    // TODO: op_A0_A3_byte $FFFF
    *(byte*)(?) = *(byte*)(arg2);    // $CB92
    return *(byte*)(arg2);    // $CB93
}

// (body @ $CB99)

word sub_CB94(word arg1, word arg2, word arg3, word arg4) {
    local11 = *(word*)(arg1);    // $CB9B
    arg1 = ?;    // $CB9C
    *(word*)(?) = *(word*)(arg2);    // $CB9F
    arg2 = ?;    // $CBA0
    *(word*)(?) = local11;    // $CBA2
    return local11;    // $CBA3
}

// (body @ $CBA9)

word sub_CBA4(word arg1, word arg2, word arg3, word arg4) {
    arg1 = ?;    // $CBA9
    // TODO: op_8D_sbyte +21
    return syscall_dispatch(/*via arg1*/ ?, /*via arg1*/ ?);    // $CBB0
}

// (body @ $CBB6)

word sub_CBB1(word arg1, word arg2, word arg3, word arg4) {
    arg1 = ?;    // $CBB6
    return syscall_dispatch(/*via arg1*/ ?, 7);    // $CBBC
}

// (body @ $CBC2)

word sub_CBBD(word arg1, word arg2, word arg3, word arg4) {
    arg4 = ?;    // $CBC2
    arg3 = ?;    // $CBC3
    arg2 = ?;    // $CBC4
    arg1 = ?;    // $CBC5
    // TODO: op_8D_sbyte +16
    return syscall_dispatch(/*via arg4*/ ?, /*via arg4*/ ?, /*via arg4*/ ?, /*via arg4*/ ?, /*via arg4*/ ?);    // $CBCC
}

// (body @ $CC3A)

word sub_CC35(word arg1, word arg2, word arg3, word arg4) {
    arg1 = ?;    // $CC3A
    // TODO: op_8D_sbyte +18
    return syscall_dispatch(/*via arg1*/ ?, /*via arg1*/ ?);    // $CC41
}

// (body @ $CC47)

word sub_CC42(word arg1, word arg2, word arg3, word arg4) {
    // TODO: op_87_byte $13
    arg4 = ?;    // $CC49
    arg3 = ?;    // $CC4A
    arg2 = ?;    // $CC4B
    arg1 = ?;    // $CC4C
    return syscall_dispatch(/*via arg4*/ ?, /*via arg4*/ ?, /*via arg4*/ ?, /*via arg4*/ ?, /*via arg4*/ ?, 0, 12);    // $CC53
}

// (body @ $CC59)

word sub_CC54(word arg1, word arg2, word arg3, word arg4) {
    // TODO: op_87_byte $15
    // TODO: op_87_byte $13
    arg4 = ?;    // $CC5D
    arg3 = ?;    // $CC5E
    arg2 = ?;    // $CC5F
    arg1 = ?;    // $CC60
    // TODO: op_8D_sbyte +20
    return syscall_dispatch(/*via arg4*/ ?, /*via arg4*/ ?, /*via arg4*/ ?, /*via arg4*/ ?, /*via arg4*/ ?, /*via arg4*/ ?, /*via arg4*/ ?, 0);    // $CC68
}

// (body @ $CC6E)

word sub_CC69(word arg1, word arg2, word arg3, word arg4) {
    // TODO: op_8D_sbyte +18
    // TODO: op_8D_sbyte +29
    // TODO: op_8D_sbyte +22
    return sub_CC42(/*stack underflow*/ regA, /*stack underflow*/ regA, /*stack underflow*/ regA, 1, 7);    // $CC7A
}

// (body @ $CC80)

word sub_CC7B(word arg1, word arg2, word arg3, word arg4) {
    return mem_7FCF;    // $CC88
}

// (body @ $CC8E)

word sub_CC89(word arg1, word arg2, word arg3, word arg4) {
    // TODO: op_8D_sbyte +25
    // TODO: op_8D_sbyte +19
    if (mem_7FD1) {    // $CC96
    } else {
    }
L_CCA0:
    if (mem_7FD1) {    // $CCA9
    } else {
    }
L_CCB3:
    return ui_helper_cc7b(22, 2);    // $CCB9
    }
    }
}

// (body @ $CCBF)

word sub_CCBA(word arg1, word arg2, word arg3, word arg4) {
    // TODO: op_8D_sbyte +25
    // TODO: op_8D_sbyte +29
    // TODO: op_8D_sbyte +20
    // TODO: op_8D_sbyte +20
    return mem_7BF9;    // $CCD0
}

// (body @ $CCD6)

word sub_CCD1(word arg1, word arg2, word arg3, word arg4) {
    // TODO: op_8D_sbyte +29
    return sub_CC42(/*stack underflow*/ regA, 1, 3, 3, 2);    // $CCE0
}

// (body @ $CCE6)

word sub_CCE1(word arg1, word arg2, word arg3, word arg4) {
    // TODO: op_8D_sbyte +26
    // TODO: op_8D_sbyte +29
    // TODO: op_8D_sbyte +26
    return mem_7FDF;    // $CCF8
}

// (body @ $CCFE)

word sub_CCF9(word arg1, word arg2, word arg3, word arg4) {
    // TODO: op_8D_sbyte +19
    // TODO: op_8D_sbyte +31
    if ((mem_6F5D != 0x00FF)) {    // $CD10
    }
L_CD1F:
    return mem_6F5D;    // $CD1F
}

// (body @ $CD25)

word sub_CD20(word arg1, word arg2, word arg3, word arg4) {
    if (mem_7FC9) {    // $CD33
    // TODO: op_8D_sbyte +33
    // TODO: op_8D_sbyte +48
    // TODO: op_8D_sbyte +48
    }
L_CD4F:
    if (mem_7FC7) {    // $CD52
    local11 = 0;    // $CD56
L_CD57:
    local11 = 0xF67A;    // $CD5F
    local11 = (local11 + 1);    // $CD66
    if (((unsigned)local11 >= (unsigned)4)) goto L_CD57;    // $CD6A
    // TODO: op_8D_sbyte +36
    // TODO: push_imm_word $15B0
    // TODO: push_imm_word $845C
    }
L_CD7E:
    if ((mem_6F5D != 0x00FF)) {    // $CD8A
    }
L_CD99:
    // TODO: op_8D_sbyte +20
    return mem_7BFB;    // $CDAE
}

// (body @ $CDB4)

word sub_CDAF(word arg1, word arg2, word arg3, word arg4) {
    // TODO: cmp_ugt
    if (mem_7FCF) {    // $CDC2
    }
L_CDC9:
    return mem_7FCF;    // $CDC9
}

// (body @ $CDCF)

word sub_CDCA(word arg1, word arg2, word arg3, word arg4) {
    // TODO: op_A0_A3_byte $000B
    if (!((? <= 95))) goto L_CDF4;    // $CDD5
    // TODO: op_A0_A3_byte $000B
    // TODO: cmp_sge
    if (!((? <= 95))) goto L_CDF4;    // $CDDE
    goto L_CE11;    // $CDE3
L_CDE6:
    // TODO: op_A0_A3_byte $000B
    // TODO: cmp_sge
    if (!(47)) goto L_CDFD;    // $CDEC
    goto L_CE11;    // $CDF1
L_CDF4:
    // TODO: op_A0_A3_byte $000B
    if ((43 <= 65)) goto L_CDE6;    // $CDFA
L_CDFD:
    // TODO: op_A0_A3_byte $000B
    if (((43 <= 65) <= 45)) {    // $CE03
    // TODO: op_A0_A3_byte $000B
    // TODO: cmp_sge
    if (((43 <= 65) <= 45)) {    // $CE0C
L_CE11:
    // TODO: op_A0_A3_byte $000B
L_CE16:
    // TODO: op_A0_A3_byte $000B
    // TODO: op_A0_A3_byte $000B
    return (58 - 40);    // $CE1C
    }
    }
L_CE1D:
    // TODO: op_A0_A3_byte $000B
    // TODO: op_D9 SWITCH_noncontig       count=12
    goto L_CE11;    // $CE57
    goto L_CE16;    // $CE5C
    goto L_CE16;    // $CE61
    goto L_CE11;    // $CE66
    // TODO: op_A0_A3_byte $000B
    goto L_CE16;    // $CE70
    goto L_CE16;    // $CE75
    goto L_CE11;    // $CE7A
    goto L_CE16;    // $CE7E
}

// (body @ $CE86)

word sub_CE81(word arg1, word arg2, word arg3, word arg4) {
    // TODO: op_A0_A3_byte $000B
    if (((? == 10))) return sub_CDAF();    // $CE8B
    // TODO: op_A0_A3_byte $000B
    // TODO: op_A0_A3_byte $000B
    // TODO: op_A0_A3_byte $000B
    // TODO: PUSH_abs $7FCF
    // TODO: PUSH_abs $7FCD
    // TODO: PUSH_abs $7FCF
    // TODO: PUSH_abs $7FCD
    // TODO: cmp_ugt
    if (mem_7FCD) {    // $CEBD
    }
L_CEC3:
    return sub_CDAF();    // $CEC3
}

// (body @ $CEC9)

word sub_CEC4(word arg1, word arg2, word arg3, word arg4) {
    goto L_CF1E;    // $CEC9
L_CECC:
    // TODO: op_A0_A3_byte $FFFD
    if ((? != 10)) goto L_CEEC;    // $CED1
    if ((local11 == mem_7FCD)) goto L_CF1B;    // $CED9
    // TODO: loadA_frameaddr $FFDB
    // TODO: PUSH_abs $7FCF
    goto L_CF13;    // $CEE9
L_CEEC:
    // TODO: op_81_byte $FB
    // TODO: op_85_byte $FB
    // TODO: op_A0_A3_byte $FFFD
    *(byte*)((((mem_7FCD - 1) + 1) - 1)) = sub_CDCA((((mem_7FCD - 1) + 1) - 1));    // $CEFB
    if ((mem_7FCD == 32)) {    // $CF06
    // TODO: loadA_frameaddr $FFDB
    // TODO: PUSH_abs $7FCF
    // TODO: op_8D_sbyte +31
L_CF13:
    // TODO: PUSH_abs $7FCF
    local11 = 32;    // $CF16
L_CF1B:
L_CF1E:
    local11 = mem_7FCD;    // $CF21
    // TODO: loadA_frameaddr $FFDB
    // TODO: op_85_byte $FB
    }
L_CF27:
    arg1 = (arg1 + 1);    // $CF29
    // TODO: op_A0_A3_byte $FFFD
    if (*(byte*)(((arg1 + 1) - 1))) goto L_CECC;    // $CF2F
    if ((local11 != mem_7FCD)) {    // $CF37
    // TODO: loadA_frameaddr $FFDB
    // TODO: PUSH_abs $7FCF
    // TODO: PUSH_abs $7FCF
    local11 = mem_7FCD;    // $CF4A
    }
L_CF4F:
    return sub_CC54(/*stack underflow*/ regA, /*stack underflow*/ regA, /*stack underflow*/ regA, 4, (local11 != mem_7FCD), (mem_7FCD - 1));    // $CF4F
}

// (body @ $CF55)

word sub_CF50(word arg1, word arg2, word arg3, word arg4) {
    return syscall_dispatch(1, 0, 5);    // $CF5C
}

// (body @ $CF62)

word sub_CF5D(word arg1, word arg2, word arg3, word arg4) {
    return syscall_dispatch(0, 0, 8);    // $CF69
}

// (body @ $CF6F)

word sub_CF6A(word arg1, word arg2, word arg3, word arg4) {
    // TODO: op_87_byte $13
    arg4 = ?;    // $CF71
    arg3 = ?;    // $CF72
    arg2 = ?;    // $CF73
    arg1 = ?;    // $CF74
    return syscall_dispatch(/*via arg4*/ ?, /*via arg4*/ ?, /*via arg4*/ ?, /*via arg4*/ ?, /*via arg4*/ ?, 0, 13);    // $CF7B
}

// (body @ $CF81)

word sub_CF7C(word arg1, word arg2, word arg3, word arg4) {
    arg4 = ?;    // $CF81
    arg3 = ?;    // $CF82
    arg2 = ?;    // $CF83
    arg1 = ?;    // $CF84
    return syscall_dispatch(/*via arg4*/ ?, /*via arg4*/ ?, /*via arg4*/ ?, /*via arg4*/ ?, 1);    // $CF8A
}

// (body @ $CF90)

word sub_CF8B(word arg1, word arg2, word arg3, word arg4) {
    arg2 = ?;    // $CF90
    arg1 = ?;    // $CF91
    return syscall_dispatch(/*via arg2*/ ?, /*via arg2*/ ?, 4);    // $CF97
}

// (body @ $CF9D)

word sub_CF98(word arg1, word arg2, word arg3, word arg4) {
    if (((unsigned)arg2 >= (unsigned)arg3)) {    // $CFA0
    *(word*)(arg1) = (*(word*)(arg1) + 1);    // $CFA7
    if (((unsigned)arg2 >= (unsigned)10)) {    // $CFAD
    } else {
    }
L_CFB9:
    *(byte*)(((*(word*)(arg1) + 1) - 1)) = (arg2 + 55);    // $CFB9
    return 0;    // $CFBB
L_CFBC:
    arg3 = 10;    // $CFBC
    // TODO: div_unsigned
    arg1 = arg3;    // $CFC1
    local11 = sub_CF98(/*via arg3*/ 10, /*via arg3*/ 10, arg2);    // $CFC6
    arg3 = arg3;    // $CFC7
    // TODO: mod_unsigned
    arg1 = arg3;    // $CFCC
    return (local11 + 1);    // $CFD3
    }
    }
}

// (body @ $CFD9)

word sub_CFD4(word arg1, word arg2, word arg3, word arg4) {
    local11 = 0;    // $CFDA
    goto L_CFED;    // $CFDB
L_CFDE:
    // TODO: op_A0_A3_byte $FFFD
    local11 = ((local11 * 10) + (local11 * 10));    // $CFE7
    *(word*)(arg1) = (*(word*)(arg1) + 1);    // $CFEC
L_CFED:
    // TODO: op_A0_A3_byte $FFFD
    if (((*(byte*)(*(word*)(arg1)) + -48) < 10)) goto L_CFDE;    // $CFF7
    return local11;    // $CFFB
}

// (body @ $D001)

word sub_CFFC(word arg1, word arg2, word arg3, word arg4) {
    arg1 = (arg1 + 2);    // $D003
    // TODO: op_85_byte $FD
    // TODO: op_85_byte $E9
    goto L_D018;    // $D00C
L_D00F:
    arg2 = (arg2 + 1);    // $D011
    // TODO: op_A0_A3_byte $FFFF
    *(byte*)(((arg2 + 1) - 1)) = ((arg2 + 1) - 1);    // $D017
L_D018:
    // TODO: op_81_byte $FD
    // TODO: op_85_byte $FD
    // TODO: op_A0_A3_byte $FFFF
    if (!(*(byte*)(((((arg2 + 1) - 1) + 1) - 1)))) goto L_D130;    // $D022
    // TODO: op_A0_A3_byte $FFFF
    if (!((*(byte*)(((((arg2 + 1) - 1) + 1) - 1)) == 37))) goto L_D00F;    // $D02B
    // TODO: loadA_frameaddr $FFF3
    // TODO: op_85_byte $F1
    // TODO: op_85_byte $EB
    // TODO: op_85_byte $EF
    // TODO: op_81_byte $FD
    // TODO: op_A0_A3_byte $FFFF
    // TODO: op_A0_A3_byte $FFFF
    if (sub_CA65(*(byte*)(0))) {    // $D047
    // TODO: loadA_frameaddr $FFFD
    } else {
    }
L_D056:
    // TODO: op_85_byte $ED
    // TODO: op_81_byte $FD
    // TODO: op_85_byte $FD
    // TODO: op_A0_A3_byte $FFFF
    if ((*(byte*)(((0 + 1) - 1)) == 46)) {    // $D065
    // TODO: loadA_frameaddr $FFFD
    // TODO: op_85_byte $EB
    // TODO: op_85_byte $EF
    // TODO: op_81_byte $FD
    // TODO: op_85_byte $FD
    // TODO: op_A0_A3_byte $FFFF
    }
L_D07F:
    // TODO: op_A0_A3_byte $FFFF
    // TODO: op_D9 SWITCH_noncontig       count=4
    // TODO: op_81_byte $E9
    // TODO: op_85_byte $E9
    // TODO: loadA_frameaddr $FFF1
    // TODO: op_81_byte $ED
    // TODO: op_85_byte $ED
    goto L_D0E5;    // $D0B4
    // TODO: op_81_byte $E9
    // TODO: op_85_byte $E9
    // TODO: op_85_byte $F1
    // TODO: op_87_byte $F1
    // TODO: op_81_byte $ED
    // TODO: op_85_byte $ED
    goto L_D0FC;    // $D0CD
    // TODO: op_81_byte $ED
    // TODO: op_85_byte $ED
    // TODO: op_81_byte $F1
    // TODO: op_85_byte $F1
    // TODO: op_81_byte $E9
    // TODO: op_85_byte $E9
    *(byte*)(((((sub_CF98(10, *(word*)(((sub_CB30(*(byte*)(((0 + 1) - 1))) + 2) + -2)), *(word*)(((sub_CB30(*(byte*)(((0 + 1) - 1))) + 2) + -2))) - sub_CA7E(/*stack underflow*/ regA)) - 1) + 1) - 1)) = *(word*)(((((((sub_CF98(10, *(word*)(((sub_CB30(*(byte*)(((0 + 1) - 1))) + 2) + -2)), *(word*)(((sub_CB30(*(byte*)(((0 + 1) - 1))) + 2) + -2))) - sub_CA7E(/*stack underflow*/ regA)) - 1) + 1) - 1) + 2) + -2));    // $D0E4
L_D0E5:
    // TODO: op_87_byte $F1
    *(byte*)(sub_CA7E(/*stack underflow*/ regA)) = 0;    // $D0E8
    // TODO: loadA_frameaddr $FFF3
    // TODO: op_85_byte $F1
    // TODO: op_85_byte $EF
    goto L_D0FC;    // $D0F1
L_D0F4:
    arg2 = (arg2 + 1);    // $D0F6
    *(byte*)(((arg2 + 1) - 1)) = 32;    // $D0FB
L_D0FC:
    // TODO: op_81_byte $ED
    // TODO: op_85_byte $ED
    // TODO: setB_imm4_50
    if ((((32 - 1) + 1) > sub_CA7E(/*stack underflow*/ regA))) goto L_D0F4;    // $D104
L_D107:
    // TODO: op_81_byte $F1
    if (!(*(byte*)((((32 - 1) + 1) > sub_CA7E(/*stack underflow*/ regA))))) goto L_D018;    // $D10A
    // TODO: op_81_byte $EF
    if (!(*(byte*)((((32 - 1) + 1) > sub_CA7E(/*stack underflow*/ regA))))) goto L_D119;    // $D10F
    // TODO: op_81_byte $EB
    // TODO: setB_imm4_50
    if ((*(byte*)((((32 - 1) + 1) > sub_CA7E(/*stack underflow*/ regA))) > sub_CA7E(/*stack underflow*/ regA))) {    // $D116
L_D119:
    arg2 = (arg2 + 1);    // $D11B
    // TODO: op_81_byte $F1
    *(byte*)(((arg2 + 1) - 1)) = *(byte*)(((arg2 + 1) - 1));    // $D121
    // TODO: op_81_byte $EB
    // TODO: op_85_byte $EB
    }
L_D127:
    // TODO: op_81_byte $F1
    // TODO: op_85_byte $F1
    goto L_D107;    // $D12C
    return ((*(byte*)(((arg2 + 1) - 1)) - 1) + 1);    // $D12F
L_D130:
    arg2 = sub_CA7E(/*stack underflow*/ regA);    // $D130
    *(byte*)(sub_CA7E(/*stack underflow*/ regA)) = 0;    // $D132
    return 0;    // $D133
    }
}

// (body @ $D139)

word sub_D134(word arg1, word arg2, word arg3, word arg4) {
    // TODO: loadA_frameaddr $FF6A
    // TODO: loadA_frameaddr $000B
    // TODO: loadA_frameaddr $FF6A
    return redraw_window(sub_CFFC(?, ?));    // $D14D
}

// (body @ $D153)

word sub_D14E(word arg1, word arg2, word arg3, word arg4) {
    local11 = 0;    // $D154
    // TODO: switch SWITCH_contig          limit=5
L_D16A:
    local11 = 0;    // $D16A
L_D16B:
    // TODO: cmp_ugt
    if (local11) goto L_D1C9;    // $D16E
L_D171:
    local11 = (local11 & 1);    // $D174
    if (((local11 & 1) != mem_7FDF)) {    // $D179
    local9 = mem_7FCD;    // $D17F
    local8 = mem_7FCF;    // $D183
    // TODO: op_8D_sbyte +26
    // TODO: op_8D_sbyte +29
    // TODO: op_8D_sbyte +26
    // TODO: op_8D_sbyte +20
    // TODO: op_8D_sbyte +26
    // TODO: op_8D_sbyte +21
    // TODO: push_imm_word $F68A
    local8 = mem_7FDF;    // $D1A3
    local9 = mem_7FDF;    // $D1A4
    }
L_D1AD:
    if ((mem_7FE7 == 2)) goto L_D269;    // $D1B2
    // TODO: op_D9 SWITCH_noncontig       count=2
L_D1C9:
L_D1CA:
    local11 = 0;    // $D1CA
    local10 = 2;    // $D1CB
    if (!((*(byte*)((local11 + 0x7FD5)) != ui_helper_d772(/*stack underflow*/ regA)))) goto L_D171;    // $D1D9
    goto L_D1CA;    // $D1DE
L_D1E4:
    local10 = selected_province_idx;    // $D1E4
    goto L_D16B;    // $D1E5
    goto L_D1E4;    // $D1EB
    if ((mem_7FE1 == 0x00FF)) {    // $D1F5
    goto L_D1FE;    // $D1F9
L_D1FC:
L_D1FE:
    local11 = (local11 + 1);    // $D1FE
    if (!((*(byte*)((local11 + 0x7FD5)) != ui_helper_d77e()))) goto L_D214;    // $D20B
    if (((unsigned)local11 >= (unsigned)8)) goto L_D1FC;    // $D211
L_D214:
    // TODO: cmp_ult
    if (local11) {    // $D217
    goto L_D220;    // $D21B
L_D21E:
L_D220:
    local11 = (local11 + 1);    // $D220
    // TODO: PUSH_abs $6F63 (battle_defending_province)
    if ((*(byte*)((local11 + 0x7FD5)) != ui_helper_d772(/*stack underflow*/ regA))) goto L_D21E;    // $D231
    local11 = (local11 + 1);    // $D236
    }
L_D237:
    }
L_D23D:
    local11 = mem_7FE1;    // $D240
    if (!(mem_7BE8)) goto L_D16B;    // $D244
    // TODO: bitxor
    goto L_D16A;    // $D24B
    goto L_D16A;    // $D24F
    // TODO: PUSH_abs $7FE7
L_D269:
    local11 = 3;    // $D269
    return syscall_dispatch(/*stack underflow*/ regA, 6);    // $D26F
    // TODO: push_imm_word $00F8
    // TODO: push_imm_word $00F8
    goto L_D269;    // $D284
}

// (body @ $D28C)

word sub_D287(word arg1, word arg2, word arg3, word arg4) {
L_D28C:
    if (sub_D14E()) goto L_D28C;    // $D28F
    local11 = 0;    // $D293
L_D294:
    local11 = sub_D14E();    // $D297
    if (!(sub_D14E())) goto L_D294;    // $D298
    return local11;    // $D29C
}

// (body @ $D2A2)

word sub_D29D(word arg1, word arg2, word arg3, word arg4) {
    if (arg1) {    // $D2A3
    } else {
    }
L_D2AC:
    if (arg1) goto L_D2CA;    // $D2B0
    // TODO: push_imm_word $00F8
    // TODO: push_imm_word $00F8
    // TODO: op_8D_sbyte +19
    goto L_D2F8;    // $D2C7
L_D2CA:
    if ((arg1 == 1)) {    // $D2CD
    // TODO: push_imm_word $00F8
    // TODO: push_imm_word $00F8
    } else {
    // TODO: PUSH_abs $7FE7
    }
L_D2EC:
L_D2F8:
    return frame_counter;    // $D2F8
    }
    }
}

// (body @ $D2FE)

word sub_D2F9(word arg1, word arg2, word arg3, word arg4) {
    // TODO: op_8D_sbyte +19
    return sub_CC42(/*stack underflow*/ regA, 1, 9, 8, 2);    // $D308
}

// (body @ $D30E)

word sub_D309(word arg1, word arg2, word arg3, word arg4) {
    // TODO: op_8D_sbyte +26
    // TODO: op_8D_sbyte +20
    return sub_CC42(/*stack underflow*/ regA, /*stack underflow*/ regA, 1, 9, 2);    // $D319
}

// (body @ $D31F)

word sub_D31A(word arg1, word arg2, word arg3, word arg4) {
    return sub_D309();    // $D325
}

// (body @ $D32B)

word sub_D326(word arg1, word arg2, word arg3, word arg4) {
    if (mem_7FC5) {    // $D32E
    }
L_D338:
    if (mem_7FD1) {    // $D33B
    } else {
    }
L_D345:
    arg1 = ?;    // $D34B
    return redraw_window(/*via arg1*/ ?);    // $D350
    }
}

// (body @ $D356)

word sub_D351(word arg1, word arg2, word arg3, word arg4) {
    arg1 = ?;    // $D356
L_D360:
    local11 = sub_D287();    // $D363
    if (!((sub_D287() != 64))) goto L_D378;    // $D367
    if ((local11 == 0x0080)) goto L_D378;    // $D36F
    if ((local11 != 2)) goto L_D360;    // $D375
L_D378:
    if ((local11 == 64)) {    // $D381
    // TODO: op_8D_sbyte +60
    } else {
    if ((local11 != 0x0080)) goto L_D3A0;    // $D393
    // TODO: op_8D_sbyte +62
    goto L_D3A1;    // $D39D
L_D3A0:
    }
L_D3A1:
    local11 = 0;    // $D3A1
    return local11;    // $D3A6
    }
}

// (body @ $D3AC)

word sub_D3A7(word arg1, word arg2, word arg3, word arg4) {
    // TODO: push_imm_word $F695
L_D3B8:
    local11 = sub_D287();    // $D3BB
    if (!((sub_D287() != 64))) goto L_D3CA;    // $D3BF
    if ((local11 != 0x0080)) goto L_D3B8;    // $D3C7
L_D3CA:
    if ((local11 == 64)) {    // $D3D3
    // TODO: op_8D_sbyte +89
    } else {
    // TODO: op_8D_sbyte +78
    }
L_D3E7:
    local11 = 0;    // $D3E7
    return local11;    // $D3EC
    }
}

// (body @ $D3F2)

word sub_D3ED(word arg1, word arg2, word arg3, word arg4) {
    local4 = 0;    // $D3F3
    local6 = 0;    // $D3F5
    local5 = 0;    // $D3F7
L_D3F8:
    // TODO: loadA_frameaddr $FFF4
    *(word*)(((local5 << 1) + 0)) = 255;    // $D404
    local5 = (local5 + 1);    // $D407
    // TODO: cmp_sge
    if (local5) goto L_D3F8;    // $D40B
    local6 = 5;    // $D40E
    // TODO: push_imm_word $F69E
    local2 = 0;    // $D426
L_D427:
    // TODO: op_D9 SWITCH_noncontig       count=6
    if (((mem_7BE0 == 1))) return -1;    // $D451
    return 0;    // $D458
    local2 = 0;    // $D45F
L_D460:
    if (!(local2)) goto L_D427;    // $D461
    local3 = 0;    // $D465
    goto L_D573;    // $D466
    // TODO: loadA_frameaddr $FFF4
    *(word*)(((local4 << 1) + 0)) = (*(word*)(((local4 << 1) + 0)) + 1);    // $D474
    // TODO: cmp_ult
    if ((*(word*)(((local4 << 1) + 0)) + 1)) {    // $D477
    // TODO: loadA_frameaddr $FFF4
    *(word*)(((local4 << 1) + (*(word*)(((local4 << 1) + 0)) + 1))) = 0;    // $D484
    }
L_D485:
    // TODO: loadA_frameaddr $FFF4
    // TODO: push_imm_word $F6A1
L_D492:
    goto L_D460;    // $D4AC
    // TODO: loadA_frameaddr $FFF4
    *(word*)(((local4 << 1) + sub_D29D(1))) = (*(word*)(((local4 << 1) + sub_D29D(1))) - 1);    // $D4BA
    // TODO: cmp_ult
    if ((*(word*)(((local4 << 1) + sub_D29D(1))) - 1)) {    // $D4BD
    // TODO: loadA_frameaddr $FFF4
    *(word*)(((local4 << 1) + (*(word*)(((local4 << 1) + sub_D29D(1))) - 1))) = 0;    // $D4CA
    }
L_D4CB:
    // TODO: loadA_frameaddr $FFF4
    // TODO: push_imm_word $F6A4
    goto L_D492;    // $D4D8
    if (!(local4)) goto L_D460;    // $D4DC
    // TODO: push_imm_word $F6A7
    // TODO: loadA_frameaddr $FFF4
    local4 = (local4 - 1);    // $D4FF
    *(word*)(((((local4 - 1) + 1) << 1) + sub_D29D(1))) = 255;    // $D508
L_D509:
    goto L_D460;    // $D50E
    if (!(((arg1 - 1) != local4))) goto L_D460;    // $D515
    if (local4) goto L_D528;    // $D519
    // TODO: loadA_frameaddr $FFF4
    if (!(*(word*)(((local4 << 1) + local4)))) goto L_D460;    // $D525
L_D528:
    // TODO: loadA_frameaddr $FFF4
    local4 = (local4 + 1);    // $D53A
    *(word*)((((local4 + 1) << 1) + mem_7FCD)) = 0;    // $D540
    // TODO: loadA_frameaddr $FFF4
    // TODO: push_imm_word $F6A9
    goto L_D509;    // $D55E
L_D561:
    // TODO: loadA_frameaddr $FFF4
    local3 = ((local3 * 10) + *(word*)(((local5 << 1) + sub_D29D(1))));    // $D570
L_D573:
    local5 = (local5 + 1);    // $D573
    // TODO: loadA_frameaddr $FFF4
    if ((*(word*)(((local5 << 1) + (local5 + 1))) != 0x00FF)) goto L_D561;    // $D581
    return local3;    // $D585
}

// (body @ $D58B)

word sub_D586(word arg1, word arg2, word arg3, word arg4) {
    goto L_D596;    // $D58C
L_D58F:
    arg1 = (arg1 / 0);    // $D593
L_D596:
    local11 = (local11 + 1);    // $D596
    if (arg1) goto L_D58F;    // $D598
    return local11;    // $D59C
}

// (body @ $D5A2)

word sub_D59D(word arg1, word arg2, word arg3, word arg4) {
    arg2 = ?;    // $D5A2
    local11 = sub_D586(/*via arg2*/ ?);    // $D5A7
    local9 = mem_7FCD;    // $D5AB
    local8 = mem_7FCF;    // $D5AF
L_D5B0:
    local8 = ?;    // $D5B0
    local9 = ?;    // $D5B1
    goto L_D5C2;    // $D5B7
L_D5BA:
    // TODO: op_8D_sbyte +32
L_D5C2:
    local10 = (local10 + 1);    // $D5C2
    if ((local10 < local11)) goto L_D5BA;    // $D5C6
    local8 = local11;    // $D5C9
    local9 = local11;    // $D5CA
    local11 = local11;    // $D5CF
    local7 = sub_D3ED(/*stack underflow*/ regA);    // $D5D4
    // TODO: setB_imm4_50
    // TODO: cmp_sge
    if (local7) goto L_D5E7;    // $D5D8
    if (!((local7 <= arg1))) goto L_D5B0;    // $D5DE
    // TODO: cmp_sge
    if (!(local7)) goto L_D5B0;    // $D5E4
L_D5E7:
    return local7;    // $D5E8
}

// (body @ $D5EE)

word sub_D5E9(word arg1, word arg2, word arg3, word arg4) {
    arg2 = ?;    // $D5EE
    arg1 = ?;    // $D5EF
    // TODO: push_imm_word $F6AC
    arg2 = ?;    // $D5F7
    arg1 = ?;    // $D5F8
    local11 = sub_D59D(/*via arg2*/ ?, /*via arg2*/ ?);    // $D5FD
    // TODO: setB_imm4_50
    if ((local11 > ?)) {    // $D601
    }
L_D607:
    return local11;    // $D608
}

// (body @ $D60E)

word sub_D609(word arg1, word arg2, word arg3, word arg4) {
    // TODO: op_8D_sbyte +26
    // TODO: push_imm_word $F6B7
    local11 = sub_D287();    // $D61F
    return local11;    // $D627
}

// (body @ $D62D)

word sub_D628(word arg1, word arg2, word arg3, word arg4) {
    local10 = 0;    // $D62E
    local11 = 0;    // $D62F
    goto L_D64E;    // $D630
L_D633:
    if (*(byte*)((local10 + 0x6DA2))) goto L_D648;    // $D639
    local10 = 0x6DA2;    // $D63C
    if ((sub_D98D(/*stack underflow*/ regA) == 0x00FF)) {    // $D645
L_D648:
    local11 = (local11 + 1);    // $D64A
    }
L_D64B:
    local10 = (local10 + 1);    // $D64D
L_D64E:
    if (((unsigned)local10 >= (unsigned)scenario_fief_count)) goto L_D633;    // $D653
    if ((local11 == 1)) {    // $D659
    if (sub_D982()) {    // $D65F
    } else {
    }
L_D667:
    local11 = (local11 & 0);    // $D66A
L_D66B:
    if ((local11 != 1)) {    // $D66E
    } else {
    }
L_D676:
    return 0;    // $D676
    }
    }
    }
}

// (body @ $D67C)

word sub_D677(word arg1, word arg2, word arg3, word arg4) {
    // TODO: PUSH_abs $6D9F
    // TODO: push_imm_word $F6C4
    return ui_helper_d134(/*stack underflow*/ regA, /*stack underflow*/ regA);    // $D686
}

// (body @ $D68C)

word sub_D687(word arg1, word arg2, word arg3, word arg4) {
    // TODO: switch SWITCH_contig          limit=4
    // TODO: push_imm_word $F6C7
L_D6A1:
    return redraw_window(/*stack underflow*/ regA);    // $D6A5
    // TODO: push_imm_word $F6CE
    goto L_D6A1;    // $D6A9
    // TODO: push_imm_word $F6D5
    goto L_D6A1;    // $D6AF
    // TODO: push_imm_word $F6DA
    goto L_D6A1;    // $D6B5
}

// (body @ $D6BD)

word sub_D6B8(word arg1, word arg2, word arg3, word arg4) {
    if (arg3) {    // $D6BE
    // TODO: ext_op $25
    // TODO: ext_op $14
    // TODO: ext_op $25
    // TODO: ext_op $14
    // TODO: ext_op $25
    // TODO: ext_op $15
    // TODO: ext_op $01
    // TODO: ext_op $15
    // TODO: ext_op $02
    // TODO: ext_op $27
    } else {
    }
L_D6DD:
    return -1;    // $D6DD
    }
}

// (body @ $D6E3)

word sub_D6DE(word arg1, word arg2, word arg3, word arg4) {
    if (arg1) goto L_D6ED;    // $D6E4
    if (!(arg2)) return 0;    // $D6E8
    // TODO: ext_op $26
    // TODO: ext_op $14
    // TODO: ext_op $26
    // TODO: ext_op $15
    // TODO: ext_op $03
    // TODO: ext_op $14
    // TODO: ext_op $26
    // TODO: ext_op $19
    // TODO: ext_op $01
    // TODO: ext_op $15
    // TODO: ext_op $02
    // TODO: ext_op $27
    return local0;    // $D70C
}

// (body @ $D712)

word sub_D70D(word arg1, word arg2, word arg3, word arg4) {
    if (((arg2 == 100))) return arg1;    // $D716
    return (((((arg2 % 10) * (arg1 / 10)) / 10) + (((arg1 % 10) * arg2) / 100)) + ((arg2 / 10) * (arg1 / 10)));    // $D73D
}

// (body @ $D743)

word sub_D73E(word arg1, word arg2, word arg3, word arg4) {
    goto L_D751;    // $D743
L_D746:
    local11 = 240;    // $D749
L_D74A:
    local11 = (local11 - 1);    // $D74C
    if (local11) goto L_D74A;    // $D74E
L_D751:
    arg1 = (arg1 - 1);    // $D753
    if (((arg1 - 1) + 1)) goto L_D746;    // $D755
    return ((arg1 - 1) + 1);    // $D758
}

// (body @ $D75E)

word sub_D759(word arg1, word arg2, word arg3, word arg4) {
    // TODO: PUSH_abs $6D65
    return sub_D73E(/*stack underflow*/ regA);    // $D765
}

// (body @ $D76B)

word sub_D766(word arg1, word arg2, word arg3, word arg4) {
    return ui_helper_cc89();    // $D771
}

// (body @ $D777)

word sub_D772(word arg1, word arg2, word arg3, word arg4) {
    return *(byte*)((arg1 + 0x6E15));    // $D77D
}

// (body @ $D783)

word sub_D77E(word arg1, word arg2, word arg3, word arg4) {
    // TODO: PUSH_abs $6F5F (selected_province_idx)
    return ui_helper_d772(/*stack underflow*/ regA);    // $D78A
}

// (body @ $D790)

word sub_D78B(word arg1, word arg2, word arg3, word arg4) {
    // TODO: push_imm_word $F6E1
    arg1 = ?;    // $D797
    local11 = ((ui_helper_d772(/*via arg1*/ ?) * 9) + 0x77A8);    // $D7A2
    // TODO: op_8D_sbyte +44
    return sub_CE81(/*stack underflow*/ regA);    // $D7AE
}

// (body @ $D7B4)

word sub_D7AF(word arg1, word arg2, word arg3, word arg4) {
    // TODO: push_imm_word $F6E7
    arg1 = ?;    // $D7BB
    local11 = ((ui_helper_d772(/*via arg1*/ ?) * 9) + 0x77A8);    // $D7C6
    return redraw_window(((ui_helper_d772(/*via arg1*/ ?) * 9) + 0x77A8));    // $D7CC
}

// (body @ $D7D2)

word sub_D7CD(word arg1, word arg2, word arg3, word arg4) {
    return ((arg1 * 7) + 0x752F);    // $D7D9
}

// (body @ $D7DF)

word sub_D7DA(word arg1, word arg2, word arg3, word arg4) {
    arg1 = ?;    // $D7DF
    return sub_D7CD(ui_helper_d772(/*via arg1*/ ?));    // $D7E9
}

// (body @ $D7EF)

word sub_D7EA(word arg1, word arg2, word arg3, word arg4) {
    // TODO: PUSH_abs $6F5F (selected_province_idx)
    return sub_D7DA(/*stack underflow*/ regA);    // $D7F6
}

// (body @ $D7FC)

word sub_D7F7(word arg1, word arg2, word arg3, word arg4) {
    local11 = ((arg1 * 26) + 0x7001);    // $D804
    if (*(word*)((local11 + 8))) goto L_D814;    // $D808
    *(word*)((local11 + 14)) = 0;    // $D812
    *(word*)((local11 + 12)) = 0;    // $D813
L_D814:
    return 0;    // $D814
}

// (body @ $D81A)

word sub_D815(word arg1, word arg2, word arg3, word arg4) {
    local11 = ((arg1 * 26) + 0x7011);    // $D822
    if (*(word*)(local11)) goto L_D835;    // $D825
    *(word*)((local11 + 6)) = 0;    // $D832
    *(word*)((local11 + 4)) = 0;    // $D833
    *(word*)((local11 + 2)) = 0;    // $D834
L_D835:
    return 0;    // $D835
}

// (body @ $D83B)

word sub_D836(word arg1, word arg2, word arg3, word arg4) {
    local7 = ((arg1 * 26) + 0x7001);    // $D843
    local10 = local7;    // $D845
    goto L_D863;    // $D846
L_D849:
    local11 = 0x7001;    // $D849
    *(word*)(0x7001) = min_word(*(word*)((local7 + 24)), *(word*)(local11));    // $D856
    // TODO: setB_imm4_50
    if ((*(word*)(local11) < 0x7001)) {    // $D85B
    local11 = 0x7001;    // $D85E
    *(word*)(0x7001) = 0;    // $D860
    }
L_D861:
L_D863:
    local11 = (local11 + 2);    // $D863
    if (((unsigned)local11 >= (unsigned)(local10 + 24))) goto L_D849;    // $D86B
    // TODO: op_8D_sbyte +100
    *(word*)((local10 + 24)) = min_word((local7 + 10), *(word*)((local7 + 10)));    // $D87B
    local9 = 0;    // $D87D
    arg1 = (local10 + 24);    // $D87E
    local6 = sub_D7DA(/*via arg1*/ (local10 + 24));    // $D883
    local8 = sub_D7DA(/*via arg1*/ (local10 + 24));    // $D884
    goto L_D8A9;    // $D885
L_D888:
    if ((*(byte*)(local8) > 0x00EB)) {    // $D88E
    local8 = 0x00EB;    // $D891
    *(byte*)(0x00EB) = 0;    // $D893
    }
L_D894:
    if ((*(byte*)(local8) > 0x00D2)) {    // $D89A
    local8 = 0x00D2;    // $D89D
    *(byte*)(0x00D2) = -46;    // $D8A0
    }
L_D8A1:
    local8 = (local8 + 1);    // $D8A3
    local9 = (local9 + 1);    // $D8A7
L_D8A9:
    if (((unsigned)local9 >= (unsigned)6)) goto L_D888;    // $D8AC
    arg1 = 6;    // $D8AF
    arg1 = 6;    // $D8B4
    return sub_D7F7(/*via arg1*/ 6);    // $D8B9
}

// (body @ $D8BF)

word sub_D8BA(word arg1, word arg2, word arg3, word arg4) {
    if ((!((arg1 >= 1)))) return 0;    // $D8C2
    arg1 = 1;    // $D8C7
    arg1 = const_two;    // $D8E4
    local11 = math32_3arg(/*via arg1*/ const_two, (sqrt_int(((*(word*)(arg2) + *(word*)(arg3)) / 2)) + sqrt_int(/*via arg1*/ 1)), (-const_two));    // $D8E9
    if (!(local11)) return 0;    // $D8EB
    return local11;    // $D8F1
}

// (body @ $D8F7)

word sub_D8F2(word arg1, word arg2, word arg3, word arg4) {
    arg2 = ?;    // $D8FD
    local11 = sub_D8BA(/*via arg2*/ ?, (arg1 + 8), (arg1 + 12));    // $D902
    local10 = (arg1->header - arg1->loyalty);    // $D90D
    if ((!((local11 <= (arg1->header - arg1->loyalty))))) return local10;    // $D912
    return local11;    // $D918
}

// (body @ $D91E)

word sub_D919(word arg1, word arg2, word arg3, word arg4) {
    arg2 = ?;    // $D924
    local11 = sub_D8BA(/*via arg2*/ ?, (arg1 + 4), (arg1 + 14));    // $D929
    local10 = (arg1->header - arg1->wealth);    // $D934
    if ((!((local11 <= (arg1->header - arg1->wealth))))) return local10;    // $D939
    return local11;    // $D93F
}

// (body @ $D945)

word sub_D940(word arg1, word arg2, word arg3, word arg4) {
    arg2 = ?;    // $D945
    arg1 = ?;    // $D946
    arg1->loyalty = (arg1->loyalty + sub_D8F2(/*via arg2*/ ?, /*via arg2*/ ?));    // $D952
    arg2 = sub_D8F2(/*via arg2*/ ?, /*via arg2*/ ?);    // $D953
    arg1 = sub_D8F2(/*via arg2*/ ?, /*via arg2*/ ?);    // $D954
    arg1->wealth = (arg1->wealth + sub_D919(/*via arg2*/ sub_D8F2(/*via arg2*/ ?, /*via arg2*/ ?), /*via arg2*/ sub_D8F2(/*via arg2*/ ?, /*via arg2*/ ?)));    // $D960
    return (arg1->wealth + sub_D919(/*via arg2*/ sub_D8F2(/*via arg2*/ ?, /*via arg2*/ ?), /*via arg2*/ sub_D8F2(/*via arg2*/ ?, /*via arg2*/ ?)));    // $D961
}

// (body @ $D967)

word sub_D962(word arg1, word arg2, word arg3, word arg4) {
    // TODO: loadA_mem_byte $6DA1
    // TODO: storeA_mem_byte $6DA1
    return (? | -128);    // $D971
}

// (body @ $D977)

word sub_D972(word arg1, word arg2, word arg3, word arg4) {
    arg1 = ?;    // $D977
    return *(byte*)((ui_helper_d772(/*via arg1*/ ?) + 0x6DD4));    // $D981
}

// (body @ $D987)

word sub_D982(word arg1, word arg2, word arg3, word arg4) {
    // TODO: cmp_ult
    return mem_6E09;    // $D98C
}

// (body @ $D992)

word sub_D98D(word arg1, word arg2, word arg3, word arg4) {
    return *(byte*)((arg1 + 0x6CF7));    // $D998
}

// (body @ $D99E)

word sub_D999(word arg1, word arg2, word arg3, word arg4) {
    return (*(byte*)((arg1 + 0x6CF7)) == 0x00FF);    // $D9A8
}

// (body @ $D9AE)

word sub_D9A9(word arg1, word arg2, word arg3, word arg4) {
    return *(byte*)((selected_province_idx + 0x6DA2));    // $D9B6
}

// (body @ $D9BC)

word sub_D9B7(word arg1, word arg2, word arg3, word arg4) {
    arg1 = ?;    // $D9C0
    return (ui_helper_d772(ui_helper_d77e()) == ?);    // $D9C7
}

// (body @ $D9CD)

word sub_D9C8(word arg1, word arg2, word arg3, word arg4) {
    return (arg1 + 0x6CF7);    // $D9D2
}

// (body @ $D9D8)

word sub_D9D3(word arg1, word arg2, word arg3, word arg4) {
    return redraw_window(((arg1 * 10) + 0x7985));    // $D9E4
}

// (body @ $D9EA)

word sub_D9E5(word arg1, word arg2, word arg3, word arg4) {
    // TODO: setB_imm4_50
    return ((*(byte*)((arg1 + 0x6F65)) & 0x0080) != 0x0080);    // $D9F6
}

// (body @ $D9FC)

word sub_D9F7(word arg1, word arg2, word arg3, word arg4) {
    if ((*(byte*)((arg1 + 0x7B79)) == 6)) {    // $DA04
    } else {
    if (!((*(byte*)((arg1 + 0x7B79)) == 7))) goto L_DA1E;    // $DA15
    goto L_DA21;    // $DA1B
L_DA1E:
    }
L_DA21:
    local11 = 0xF6FE;    // $DA21
    return local11;    // $DA23
    }
}

// (body @ $DA29)

word sub_DA24(word arg1, word arg2, word arg3, word arg4) {
    // TODO: op_87_byte $13
    arg4 = ?;    // $DA2B
    arg3 = ?;    // $DA2C
    arg3 = 1;    // $DA3B
    arg4 = 1;    // $DA3C
    arg1 = 1;    // $DA42
    return min_word(/*stack underflow*/ regA, (pct_op(/*via arg1*/ 1, math32_2arg(/*via arg4*/ 1, pct_op(math32_2arg(/*via arg4*/ ?, /*via arg4*/ ?), (arg2 | 1)))) + 1));    // $DA4E
}

// (body @ $DA54)

word sub_DA4F(word arg1, word arg2, word arg3, word arg4) {
    if (((unsigned)selected_province_idx >= (unsigned)battle_defending_province)) {    // $DA5B
    } else {
    }
L_DA73:
    *(byte*)((((battle_defending_province * 54) + selected_province_idx) + 0x6193)) = 70;    // $DA7B
    return 70;    // $DA7C
    }
}

// (body @ $DA82)

word sub_DA7D(word arg1, word arg2, word arg3, word arg4) {
    local11 = ui_helper_d77e();    // $DA85
    // TODO: PUSH_abs $6F63 (battle_defending_province)
    local10 = ui_helper_d772(/*stack underflow*/ regA);    // $DA8D
    if (((unsigned)local11 >= (unsigned)local10)) {    // $DA91
    } else {
    }
L_DAA1:
    *(byte*)((((local11 * 54) + local10) + 0x6193)) = 90;    // $DAA9
    return 90;    // $DAAA
    }
}

// (body @ $DAB0)

word sub_DAAB(word arg1, word arg2, word arg3, word arg4) {
    // TODO: push_imm_word $6F4F
    if ((scenario_fief_count == 17)) {    // $DABA
    } else {
    }
L_DACC:
    return 0x6F4F;    // $DAD6
    }
}

// (body @ $DADC)

word sub_DAD7(word arg1, word arg2, word arg3, word arg4) {
    // TODO: PUSH_abs $6F5F (selected_province_idx)
    local10 = 0x6F4F;    // $DAE6
    local11 = 0x6F4F;    // $DAE7
    goto L_DB04;    // $DAE8
L_DAEB:
    if ((sub_D98D(*(byte*)(local10)) != 0x00FF)) {    // $DAF6
    local11 = (local11 + 1);    // $DAFB
    *(byte*)(((local11 + 1) - 1)) = *(byte*)(local10);    // $DB00
    }
L_DB01:
    local10 = (local10 + 1);    // $DB03
L_DB04:
    if ((*(byte*)(local10) != 0x00FF)) goto L_DAEB;    // $DB0A
    local11 = 0x00FF;    // $DB0D
    *(byte*)(0x00FF) = -1;    // $DB10
    return -1;    // $DB11
}

// (body @ $DB17)

word sub_DB12(word arg1, word arg2, word arg3, word arg4) {
    if ((scenario_fief_count == 17)) {    // $DB1D
    // TODO: PUSH_abs $6F63 (battle_defending_province)
    return (ui_helper_d772(/*stack underflow*/ regA) == 3);    // $DB29
    }
L_DB2A:
    // TODO: PUSH_abs $6F63 (battle_defending_province)
    return (ui_helper_d772(/*stack underflow*/ regA) == 20);    // $DB34
}

// (body @ $DB3A)

word sub_DB35(word arg1, word arg2, word arg3, word arg4) {
    if (sub_D982()) {    // $DB44
    }
L_DB4A:
    return sub_D962();    // $DB4A
}

// (body @ $DB50)

word sub_DB4B(word arg1, word arg2, word arg3, word arg4) {
    if ((*(byte*)((arg1 + 0x6CF7)) != 0x00FF)) {    // $DB5A
    arg1 = 0x00FF;    // $DB5D
    }
L_DB6D:
    return redraw_window(((ui_helper_d772(/*via arg1*/ 0x00FF) * 9) + 0x77A8));    // $DB6D
}

// (body @ $DB73)

word sub_DB6E(word arg1, word arg2, word arg3, word arg4) {
    if ((*(byte*)((arg1 + 0x6CF7)) != 0x00FF)) {    // $DB7D
    arg1 = 0x00FF;    // $DB80
    } else {
    // TODO: push_imm_word $F706
    }
L_DB92:
    return redraw_window(((ui_helper_d772(/*via arg1*/ 0x00FF) * 9) + 0x77A8));    // $DB96
    }
}

// (body @ $DB9C)

word sub_DB97(word arg1, word arg2, word arg3, word arg4) {
    arg1 = ?;    // $DB9C
    *(byte*)((sub_D7DA(/*via arg1*/ ?) + 6)) = 0;    // $DBA4
    local8 = 0;    // $DBA6
L_DBA7:
    local10 = ((((rng_mod(5) * 125) + (rng_mod(5) * 25)) + (rng_mod(5) * 5)) + rng_mod(5));    // $DBCC
    if ((scenario_fief_count == 50)) {    // $DBD3
    } else {
    }
L_DBDD:
    local9 = 17;    // $DBDD
    local11 = 0;    // $DBDF
    local8 = 0;    // $DBE1
    goto L_DBF6;    // $DBE2
L_DBE5:
    if ((*(word*)(((local11 << 1) + 0x6EB1)) == local10)) {    // $DBEE
    local8 = 0;    // $DBF2
    }
L_DBF3:
    local11 = (local11 + 1);    // $DBF5
L_DBF6:
    if (((unsigned)local11 >= (unsigned)local9)) goto L_DBE5;    // $DBF9
    if (!(local8)) goto L_DBA7;    // $DBFD
    arg1 = local9;    // $DC00
    *(word*)(((ui_helper_d772(/*via arg1*/ local9) << 1) + 0x6EB1)) = local10;    // $DC0C
    return local10;    // $DC0D
    }
}

// (body @ $DC13)

word sub_DC0E(word arg1, word arg2, word arg3, word arg4) {
    // TODO: cmp_ugt
    if (arg1) {    // $DC17
    // TODO: loadA_mem_byte $6E4A
    // TODO: storeA_mem_byte $6E4A
    // TODO: loadA_mem_byte $6E4A
    return *(byte*)(((arg1 - 1) + 0x6E4B));    // $DC29
    }
L_DC2A:
    // TODO: loadA_mem_byte $6E4A
    // TODO: storeA_mem_byte $6E4A
    // TODO: loadA_mem_byte $6E4A
    *(byte*)(((*(byte*)(((arg1 - 1) + 0x6E4B)) + 1) + 0x6E4A)) = arg1;    // $DC3A
    return arg1;    // $DC3B
}

// (body @ $DC41)

word sub_DC3C(word arg1, word arg2, word arg3, word arg4) {
    local10 = 0x6E7F;    // $DC44
    local11 = 0;    // $DC46
    goto L_DC5D;    // $DC47
L_DC4A:
    if ((*(byte*)(local10) == arg1)) {    // $DC4E
    local10 = arg1;    // $DC51
    *(byte*)(arg1) = -1;    // $DC54
    }
L_DC55:
    local10 = (local10 + 1);    // $DC57
    local11 = (local11 + 1);    // $DC5B
L_DC5D:
    if (((unsigned)local11 >= (unsigned)scenario_fief_count)) goto L_DC4A;    // $DC62
    return ((unsigned)local11 >= (unsigned)scenario_fief_count);    // $DC65
}

// (body @ $DC6B)

word sub_DC66(word arg1, word arg2, word arg3, word arg4) {
    // TODO: cmp_ugt
    if (!(!(arg1))) return arg1;    // $DC6F
    if ((scenario_fief_count == 50)) {    // $DC7A
    } else {
    }
L_DC87:
    return *(byte*)((arg1 + 0xF70E));    // $DC87
    }
}

// (body @ $DC8D)

word sub_DC88(word arg1, word arg2, word arg3, word arg4) {
    // TODO: loadA_frameaddr $FFFF
    // TODO: PUSH_abs $6F63 (battle_defending_province)
    // TODO: op_A0_A3_byte $FFFF
    return sub_CBBD(/*stack underflow*/ regA, 1, ((((sub_DC66((arg2 * 11)) * 55) + ?) + arg1) + 0xA57E), 4);    // $DCB1
}

// (body @ $DCB7)

word sub_DCB2(word arg1, word arg2, word arg3, word arg4) {
L_DCB7:
    // TODO: loadA_frameaddr $FFF3
    local9 = ?;    // $DCBA
    local11 = (rng_mod(11) << 1);    // $DCC1
    local10 = (rng_mod(11) << 1);    // $DCC8
    local9 = ?;    // $DCC9
    *(byte*)(0xF930) = *(byte*)((local11 + 0xF930));    // $DCD0
    local9 = (local9 + 1);    // $DCD3
    local11 = (local11 + 1);    // $DCD7
    *(byte*)((local9 + 1)) = *(byte*)(((local11 + 1) + 0xF930));    // $DCDD
    local9 = (local9 + 1);    // $DCE0
    *(byte*)((local9 + 1)) = *(byte*)((local10 + 0xF95D));    // $DCE8
    local9 = (local9 + 1);    // $DCEB
    local10 = (local10 + 1);    // $DCEF
    *(byte*)((local9 + 1)) = *(byte*)(((local10 + 1) + 0xF95D));    // $DCF5
    local9 = (local9 + 1);    // $DCF8
    *(byte*)((local9 + 1)) = 0;    // $DCFB
    local8 = 0;    // $DCFD
    goto L_DD1C;    // $DCFF
L_DD02:
    // TODO: loadA_frameaddr $FFF3
    if (sub_CAB0(((local11 * 9) + 0x77A8), ((local11 * 9) + 0x77A8))) goto L_DD1A;    // $DD12
    local8 = 0;    // $DD16
    goto L_DD25;    // $DD17
L_DD1A:
L_DD1C:
    local11 = (local11 + 1);    // $DD1C
    if (((unsigned)local11 >= (unsigned)scenario_fief_count)) goto L_DD02;    // $DD22
L_DD25:
    if (local8) goto L_DCB7;    // $DD26
    // TODO: loadA_frameaddr $FFF3
    return sub_CAD9(local8, ((arg1 * 9) + 0x77A8));    // $DD39
}

// (body @ $DD3F)

word sub_DD3A(word arg1, word arg2, word arg3, word arg4) {
    // TODO: loadA_frameaddr $FFF8
    local6 = ?;    // $DD42
    goto L_DD67;    // $DD44
L_DD47:
    // TODO: bitxor
    if (sub_D9B7(*(byte*)(local7))) goto L_DD65;    // $DD50
    if (sub_D999(*(byte*)(local7))) goto L_DD65;    // $DD5A
    local6 = (local6 + 1);    // $DD5F
    *(byte*)(((local6 + 1) - 1)) = *(byte*)(local7);    // $DD64
L_DD65:
L_DD67:
    local7 = (local7 + 1);    // $DD67
    if ((*(byte*)(local7) != 0x00FF)) goto L_DD47;    // $DD6E
    local6 = 0x00FF;    // $DD71
    *(byte*)(0x00FF) = -1;    // $DD74
    arg2 = 0x00FF;    // $DD76
    // TODO: loadA_frameaddr $FFF8
    return sub_CBBD(/*via arg2*/ 0x00FF, 8, -1, 0);    // $DD80
}

// (body @ $DD86)

word sub_DD81(word arg1, word arg2, word arg3, word arg4) {
    arg1 = ?;    // $DD86
    // TODO: op_8D_sbyte +20
    *(byte*)(?) = (rng_mod(sub_D7DA(/*via arg1*/ ?)) + 20);    // $DD94
    arg1 = ?;    // $DD95
    local10 = (sub_D7DA(/*via arg1*/ ?) + 1);    // $DD9B
    goto L_DDC8;    // $DD9C
L_DD9F:
    local11 = ?;    // $DD9F
    // TODO: op_8D_sbyte +20
    *(byte*)(?) = pct_op((rng_mod(/*stack underflow*/ regA) + 50), *(byte*)(local11));    // $DDB0
    if ((*(byte*)(local11) < 30)) {    // $DDB6
    } else {
    }
L_DDBF:
    *(byte*)(local11) = (*(byte*)(local11) + 0);    // $DDC5
L_DDC8:
    local11 = (local11 + 1);    // $DDC8
    if (((unsigned)local11 <= (unsigned)(local10 + 4))) goto L_DD9F;    // $DDCF
    local8 = ((arg1 * 26) + 0x7001);    // $DDDA
    goto L_DE45;    // $DDDB
L_DDDE:
    if (!((((arg1 * 26) + 0x7017) == local9))) goto L_DE0A;    // $DDE8
    local9 = local9;    // $DDEB
    // TODO: op_8D_sbyte +31
    *(word*)(local9) = pct_op((rng_mod(/*stack underflow*/ regA) + 50), *(word*)(local9));    // $DDFC
    if (!((*(word*)(local9) < 50))) goto L_DE3B;    // $DE02
    goto L_DE3C;    // $DE07
L_DE0A:
    local9 = 50;    // $DE0A
    if (*(byte*)((arg1 + 0x6DA2))) {    // $DE11
    // TODO: op_8D_sbyte +20
    } else {
    // TODO: op_8D_sbyte +30
    }
L_DE27:
    *(word*)(0x6DA2) = pct_op((rng_mod(/*stack underflow*/ regA) + 30), *(word*)(local9));    // $DE2F
    if ((*(word*)(local9) < 10)) {    // $DE34
    } else {
    }
L_DE3C:
    *(word*)(local9) = (*(word*)(local9) + 0);    // $DE42
L_DE45:
    local9 = (local9 + 2);    // $DE45
    if (((unsigned)local9 >= (unsigned)(local8 + 24))) goto L_DDDE;    // $DE4D
    // TODO: op_8D_sbyte +50
    *(word*)(((arg1 * 26) + 0x700D)) = (*(word*)(((arg1 * 26) + 0x700D)) + 0x700D);    // $DE5E
    // TODO: op_8D_sbyte +50
    *(word*)(((arg1 * 26) + 0x7013)) = (*(word*)(((arg1 * 26) + 0x7013)) + 0x7013);    // $DE6D
    *(byte*)((arg1 + 0x6D2D)) = 20;    // $DE76
    return 20;    // $DE77
    }
    }
    }
}

// (body @ $DE7D)

word sub_DE78(word arg1, word arg2, word arg3, word arg4) {
    // TODO: loadA_mem_byte $6DA1
    if (!(!((? & 32)))) return 0xF72E;    // $DE83
    // TODO: loadA_mem_byte $6DA1
    if (!(!((0xF72E & 16)))) return 0x796A;    // $DE90
    // TODO: op_D9 SWITCH_noncontig       count=4
L_DEB0:
    local11 = 0xF720;    // $DEB0
    return local11;    // $DEB2
    goto L_DEB0;    // $DEB6
    arg1 = 16;    // $DEB9
    goto L_DEB0;    // $DEBE
}

// (body @ $DEC6)

word sub_DEC1(word arg1, word arg2, word arg3, word arg4) {
    if ((mem_6F57 == battle_defending_province)) {    // $DECD
    } else {
    }
L_DED9:
    local8 = battle_defending_province;    // $DED9
    local10 = ui_helper_d772(battle_defending_province);    // $DEDF
    // TODO: PUSH_abs $6F57
    local9 = ui_helper_d772(/*stack underflow*/ regA);    // $DEE7
    local9 = battle_defending_province;    // $DEED
    goto L_DF33;    // $DEF3
L_DEF6:
    local11 = battle_defending_province;    // $DEF6
    if ((ui_helper_d772(/*stack underflow*/ regA) == local9)) {    // $DEFD
    local11 = local9;    // $DF00
    if (sub_D999(/*stack underflow*/ regA)) goto L_DF31;    // $DF05
    *(byte*)((local11 + 0x6E15)) = local10;    // $DF0F
    *(byte*)((local11 + 0x6DA2)) = 0;    // $DF17
    local8 = 0x6CF7;    // $DF1E
    if (sub_D98D((local11 + 0x6CF7))) {    // $DF23
    } else {
    }
L_DF2B:
    *(byte*)(0x6CF7) = 0;    // $DF2B
    local11 = 0x6CF7;    // $DF2C
L_DF31:
L_DF33:
    local11 = (local11 + 1);    // $DF33
    if (((unsigned)local11 >= (unsigned)scenario_fief_count)) goto L_DEF6;    // $DF39
    return ((unsigned)local11 >= (unsigned)scenario_fief_count);    // $DF3C
    }
    }
    }
}

// (body @ $DF42)

word sub_DF3D(word arg1, word arg2, word arg3, word arg4) {
    arg1 = ?;    // $DF42
    local11 = sub_D7DA(/*via arg1*/ ?);    // $DF47
    *(byte*)((local11 + 2)) = (*(byte*)((local11 + 2)) + 1);    // $DF4D
    *(byte*)((local11 + 4)) = (*(byte*)((local11 + 4)) + 1);    // $DF53
    *(byte*)((local11 + 5)) = (*(byte*)((local11 + 5)) + 1);    // $DF59
    arg2 = ?;    // $DF5A
    local11 = sub_D7DA(/*via arg2*/ ?);    // $DF5F
    *(byte*)((local11 + 2)) = (*(byte*)((local11 + 2)) - 1);    // $DF65
    *(byte*)((local11 + 4)) = (*(byte*)((local11 + 4)) - 1);    // $DF6B
    *(byte*)((local11 + 5)) = (*(byte*)((local11 + 5)) - 1);    // $DF71
    return (*(byte*)((local11 + 5)) - 1);    // $DF72
}

// (body @ $DF78)

word sub_DF73(word arg1, word arg2, word arg3, word arg4) {
    local9 = ((selected_province_idx * 26) + 0x7013);    // $DF82
    local10 = ((battle_defending_province * 26) + 0x7013);    // $DF8D
    local11 = *(word*)((local10 + 6));    // $DF91
    local8 = 0;    // $DF93
L_DF94:
    local10 = 0x7013;    // $DF94
    local11 = 0x7013;    // $DF95
    // TODO: PUSH_abs $6F87
    // TODO: PUSH_abs $6F81
    *(word*)(0x7013) = sub_DA24(/*stack underflow*/ regA, /*stack underflow*/ regA, /*stack underflow*/ regA, *(word*)(local9), *(word*)(local10));    // $DFA6
    local8 = (local8 + 1);    // $DFA9
    local10 = (local10 + 2);    // $DFAD
    local9 = (local9 + 2);    // $DFB2
    if (((unsigned)local8 >= (unsigned)3)) goto L_DF94;    // $DFB8
    return ((unsigned)local8 >= (unsigned)3);    // $DFBB
}

// (body @ $DFC1)

word sub_DFBC(word arg1, word arg2, word arg3, word arg4) {
    local11 = battle_defending_province;    // $DFC4
    goto L_DFEC;    // $DFC6
L_DFC9:
    if (tax_helper_db12()) {    // $DFCC
    if ((*(byte*)((battle_defending_province + 0x6D2D)) > 30)) {    // $DFDA
    *(byte*)((battle_defending_province + 0x6D2D)) = 30;    // $DFE7
    }
    }
L_DFE8:
L_DFEC:
    if (((unsigned)battle_defending_province >= (unsigned)scenario_fief_count)) goto L_DFC9;    // $DFF6
    return battle_defending_province;    // $DFFD
}

// (body @ $E003)

word sub_DFFE(word arg1, word arg2, word arg3, word arg4) {
    local11 = ((arg2->arms / 50) + 20);    // $E00C
    // TODO: cmp_ugt
    if (*(byte*)(((arg1 * 5) + 0x76AB))) {    // $E017
    *(byte*)(((arg1 * 5) + 0x76A9)) = (*(byte*)(((arg1 * 5) + 0x76A9)) + (*(byte*)(((arg1 * 5) + 0x76AB)) - local11));    // $E030
    *(byte*)(((arg1 * 5) + 0x76AB)) = local11;    // $E03A
    }
L_E03B:
    return local11;    // $E03B
}

// (body @ $E041)

word sub_E03C(word arg1, word arg2, word arg3, word arg4) {
    // TODO: PUSH_abs $6F63 (battle_defending_province)
    local6 = ((battle_defending_province * 26) + 0x7001);    // $E052
    local8 = (selected_province_idx == 50);    // $E059
    local9 = (mem_6F57 == battle_defending_province);    // $E061
    if (local9) {    // $E063
    }
L_E080:
    if (local8) goto L_E0A6;    // $E081
    local6 = 0x76A9;    // $E087
    // TODO: PUSH_abs $6F63 (battle_defending_province)
    if (local9) {    // $E090
    // TODO: PUSH_abs $6F63 (battle_defending_province)
    // TODO: PUSH_abs $6F5F (selected_province_idx)
    } else {
    // TODO: PUSH_abs $6F5F (selected_province_idx)
    // TODO: PUSH_abs $6F63 (battle_defending_province)
    }
L_E0A2:
L_E0A6:
    // TODO: loadA_mem_byte $6DA1
    if ((sub_DF3D(/*stack underflow*/ regA, /*stack underflow*/ regA) & 32)) goto L_E0B3;    // $E0AC
    if (local8) goto L_E0B7;    // $E0B0
L_E0B3:
    goto L_E0B8;    // $E0B4
L_E0B7:
L_E0B8:
    local7 = 0;    // $E0B8
    if (local7) {    // $E0BA
    if (local9) goto L_E0CB;    // $E0BE
    }
L_E0CB:
    local6 = 32;    // $E0CB
    *(word*)(mem_6F83) = (mem_6F7D + mem_6F83);    // $E0D3
    *(word*)((local6 + 6)) = (mem_6F7F + mem_6F85);    // $E0DE
    *(word*)((local6 + 16)) = (mem_6F81 + mem_6F87);    // $E0EA
    if (local7) {    // $E0EC
    *(word*)((local6 + 8)) = (*(word*)((local6 + 8)) - pct_op((rng_mod(10) + 10), *(word*)((local6 + 8))));    // $E105
    }
L_E106:
    local10 = (battle_defending_province + 0x6E15);    // $E10D
    if (local8) goto L_E120;    // $E10F
    local9 = 0x6E15;    // $E112
    if (sub_D9E5(/*stack underflow*/ regA)) {    // $E117
    } else {
    if (!(local9)) goto L_E19C;    // $E121
    if (!(local8)) goto L_E178;    // $E125
    if (!(*(byte*)((battle_defending_province + 0x6DA2)))) goto L_E16E;    // $E130
    goto L_E165;    // $E142
L_E145:
    local11 = 0x6DA2;    // $E148
    if (!((ui_helper_d772(*(byte*)(local10)) == 0x6DA2))) goto L_E163;    // $E14F
    if ((local11 == battle_defending_province)) goto L_E163;    // $E157
    local11 = battle_defending_province;    // $E15A
    *(byte*)(sub_D9C8(/*stack underflow*/ regA)) = -1;    // $E162
L_E163:
L_E165:
    local11 = (local11 + 1);    // $E165
    if (((unsigned)local11 >= (unsigned)scenario_fief_count)) goto L_E145;    // $E16B
L_E16E:
    // TODO: PUSH_abs $6F63 (battle_defending_province)
    goto L_E19C;    // $E175
L_E178:
    local10 = scenario_fief_count;    // $E178
    *(byte*)(scenario_fief_count) = ui_helper_d77e();    // $E17C
    // TODO: PUSH_abs $6F63 (battle_defending_province)
    // TODO: PUSH_abs $6F5F (selected_province_idx)
    if (!(sub_D98D(sub_D9C8(/*stack underflow*/ regA)))) goto L_E193;    // $E18C
    goto L_E194;    // $E190
L_E193:
L_E194:
    *(byte*)(scenario_fief_count) = 0;    // $E194
    // TODO: PUSH_abs $6F63 (battle_defending_province)
    }
L_E19C:
    if (local8) goto L_E1C7;    // $E19D
    if (local9) {    // $E1A1
    // TODO: loadA_mem_byte $6F65
    // TODO: ashr_by_regB
    *(byte*)((battle_defending_province + 0x6DA2)) = (battle_defending_province + 0x6DA2);    // $E1B1
    // TODO: bitxor
    *(byte*)((selected_province_idx + 0x6DA2)) = *(byte*)((selected_province_idx + 0x6DA2));    // $E1C6
    }
L_E1C7:
    // TODO: loadA_mem_byte $6DA1
    // TODO: storeA_mem_byte $6DA1
    // TODO: PUSH_abs $6F63 (battle_defending_province)
    if (local8) goto L_E1E6;    // $E1DC
    // TODO: PUSH_abs $6F5F (selected_province_idx)
L_E1E6:
    return cap_fief_stats(/*stack underflow*/ regA);    // $E1E6
    }
    }
}

// (body @ $E1EC)

word sub_E1E7(word arg1, word arg2, word arg3, word arg4) {
    // TODO: op_8D_sbyte +29
    goto L_E211;    // $E1F3
L_E1F6:
    *(byte*)((((local11 * 54) + arg1) + 0x6193)) = 0;    // $E20D
    *(byte*)((((arg1 * 54) + local11) + 0x6193)) = 0;    // $E20E
L_E211:
    local11 = (local11 + 1);    // $E211
    if (((unsigned)local11 >= (unsigned)scenario_fief_count)) goto L_E1F6;    // $E217
    return ((unsigned)local11 >= (unsigned)scenario_fief_count);    // $E21A
}

// (body @ $E220)

word sub_E21B(word arg1, word arg2, word arg3, word arg4) {
    // TODO: push_imm_word $00FF
    *(byte*)(0x6E15) = sub_DC0E((arg1 + 0x6E15));    // $E22D
    arg1 = 0x6E15;    // $E22E
    arg1 = 0x6E15;    // $E238
    // TODO: push_imm_word $F735
    *(byte*)((arg1 + 0x6CF7)) = 0;    // $E259
    *(byte*)((arg1 + 0x6DA2)) = 0;    // $E261
    arg1 = 0x6DA2;    // $E262
    arg1 = 0x6DA2;    // $E267
    arg1 = 0x6DA2;    // $E26C
    return confirm_prompt();    // $E274
}

// (body @ $E27A)

word sub_E275(word arg1, word arg2, word arg3, word arg4) {
    arg1 = ?;    // $E27A
    arg1 = ?;    // $E27F
    // TODO: push_imm_word $F74F
    arg1 = 0x77A8;    // $E296
    if (sub_D98D(/*via arg1*/ 0x77A8)) {    // $E29B
    // TODO: PUSH_abs $6D9F
    // TODO: push_imm_word $F75B
    }
L_E2AB:
    return confirm_prompt();    // $E2AE
}

// (body @ $E2B4)

word sub_E2AF(word arg1, word arg2, word arg3, word arg4) {
    local10 = 0;    // $E2B5
    local11 = ((arg1 * 5) + 0x76A9);    // $E2BD
    goto L_E2CF;    // $E2BE
L_E2C1:
    local11 = (local11 + 1);    // $E2C3
    arg2 = (arg2 + 1);    // $E2C8
    *(byte*)(((local11 + 1) - 1)) = *(byte*)(((arg2 + 1) - 1));    // $E2CB
    local10 = (local10 + 1);    // $E2CE
L_E2CF:
    if (((unsigned)local10 >= (unsigned)5)) goto L_E2C1;    // $E2D2
    return ((unsigned)local10 >= (unsigned)5);    // $E2D5
}

// (body @ $E2DB)

word sub_E2D6(word arg1, word arg2, word arg3, word arg4) {
    // TODO: push_imm_word $F777
    // TODO: PUSH_abs $6F63 (battle_defending_province)
    // TODO: push_imm_word $F77D
    arg1 = 0x77A8;    // $E30C
    // TODO: push_imm_word $F77F
    return ui_helper_d134(/*via arg1*/ 0x77A8, /*via arg1*/ 0x77A8);    // $E314
}

// (body @ $E31A)

word sub_E315(word arg1, word arg2, word arg3, word arg4) {
    // TODO: PUSH_abs $6F63 (battle_defending_province)
    if (sub_D98D(/*stack underflow*/ regA)) {    // $E321
    local9 = mem_7FD3;    // $E327
    // TODO: push_imm_word $F798
    // TODO: push_imm_word $F7A6
    if (!(ui_helper_d3a7())) goto L_E359;    // $E33D
    // TODO: push_imm_word $F78C
    // TODO: push_imm_word $270F
    local11 = number_input(/*stack underflow*/ regA, 1);    // $E34F
    if (number_input(/*stack underflow*/ regA, 1)) goto L_E35B;    // $E350
    goto L_E35B;    // $E356
L_E359:
    local11 = 0;    // $E35A
L_E35B:
    return local11;    // $E360
    }
L_E361:
    // TODO: PUSH_abs $6D63 (const_two)
    if (rng_mod(/*stack underflow*/ regA)) goto L_E3A2;    // $E368
    // TODO: PUSH_abs $6F5F (selected_province_idx)
    if (!(war_helper_d972(/*stack underflow*/ regA))) goto L_E37D;    // $E372
    if (rng_mod(3)) goto L_E3A2;    // $E37A
L_E37D:
    local10 = *(word*)(((selected_province_idx * 26) + 0x7001));    // $E388
    if ((*(word*)(((selected_province_idx * 26) + 0x7001)) > 0x00C8)) {    // $E38D
    // TODO: op_8D_sbyte +30
    local10 = 0x00C8;    // $E399
    // TODO: op_90_bb $00C8
    return pct_op(/*stack underflow*/ regA, (rng_mod(/*stack underflow*/ regA) + 50));    // $E3A1
    }
L_E3A2:
    return 0;    // $E3A3
}

// (body @ $E3A9)

word sub_E3A4(word arg1, word arg2, word arg3, word arg4) {
    // TODO: PUSH_abs $6F63 (battle_defending_province)
    if (sub_D98D(/*stack underflow*/ regA)) {    // $E3B0
    local9 = mem_7FD3;    // $E3B6
    // TODO: push_imm_word $F7AD
    // TODO: push_imm_word $F78C
    // TODO: push_imm_word $270F
    local11 = number_input(/*stack underflow*/ regA, 1);    // $E3D1
    if (number_input(/*stack underflow*/ regA, 1)) goto L_E3D8;    // $E3D2
L_E3D8:
    return local11;    // $E3DD
    }
L_E3DE:
    // TODO: PUSH_abs $6F5F (selected_province_idx)
    if (!(war_helper_d972(/*stack underflow*/ regA))) goto L_E3F0;    // $E3E5
    if (rng_mod(3)) goto L_E423;    // $E3ED
L_E3F0:
    local10 = *(word*)(((selected_province_idx * 26) + 0x7001));    // $E3FB
    // TODO: PUSH_abs $6D63 (const_two)
    if (rng_mod(/*stack underflow*/ regA)) goto L_E421;    // $E403
    // TODO: op_8D_sbyte +50
    local10 = 0x7001;    // $E40D
    // TODO: op_8D_sbyte +50
    local10 = 0x7001;    // $E415
    goto L_E422;    // $E41E
L_E421:
L_E422:
    return 0;    // $E422
L_E423:
    return 0;    // $E424
}

// (body @ $E42A)

word sub_E425(word arg1, word arg2, word arg3, word arg4) {
    arg1 = ?;    // $E42A
    arg1 = ui_helper_d772(/*via arg1*/ ?);    // $E42F
    arg1 = ?;    // $E430
    goto L_E44A;    // $E436
L_E439:
    local11 = ?;    // $E439
    if ((ui_helper_d772(/*stack underflow*/ regA) == arg1)) {    // $E440
    local11 = arg1;    // $E443
    }
L_E448:
L_E44A:
    local11 = (local11 + 1);    // $E44A
    if (((unsigned)local11 >= (unsigned)scenario_fief_count)) goto L_E439;    // $E450
    return ((unsigned)local11 >= (unsigned)scenario_fief_count);    // $E453
}

// (body @ $E459)

word sub_E454(word arg1, word arg2, word arg3, word arg4) {
    if ((*(byte*)((arg1 + 0x6CF7)) != 0x00FF)) {    // $E463
    // TODO: push_imm_word $F7B2
    // TODO: push_imm_word $F7B8
    *(byte*)((arg1 + 0x6CF7)) = -1;    // $E482
    *(byte*)((arg1 + 0x6DA2)) = 0;    // $E48A
    *(byte*)((arg1 + 0x6D2D)) = 20;    // $E493
    // TODO: push_imm_word $77A3
    arg1 = 0x6D2D;    // $E497
    arg1 = 0x6D2D;    // $E49C
    }
L_E4A1:
    return sub_E554(/*via arg1*/ 0x6D2D);    // $E4A1
}

// (body @ $E4A7)

word sub_E4A2(word arg1, word arg2, word arg3, word arg4) {
    local10 = selected_province_idx;    // $E4AA
    local11 = 0x6F89;    // $E4AE
    goto L_E4C6;    // $E4B0
L_E4B3:
    if (sub_D9A9()) {    // $E4B6
    local11 = (local11 + 1);    // $E4BB
    *(byte*)(((local11 + 1) - 1)) = selected_province_idx;    // $E4C1
    }
L_E4C2:
L_E4C6:
    if (((unsigned)selected_province_idx >= (unsigned)scenario_fief_count)) goto L_E4B3;    // $E4D0
    local11 = scenario_fief_count;    // $E4D3
    *(byte*)(scenario_fief_count) = -1;    // $E4D6
    return selected_province_idx;    // $E4DB
}

// (body @ $E4E1)

word sub_E4DC(word arg1, word arg2, word arg3, word arg4) {
    local10 = 0x6F89;    // $E4E7
    goto L_E501;    // $E4E8
L_E4EB:
    if ((ui_helper_d772(*(byte*)(local11)) != arg1)) {    // $E4F4
    local10 = (local10 + 1);    // $E4F9
    *(byte*)(((local10 + 1) - 1)) = *(byte*)(local11);    // $E4FE
    }
L_E4FF:
L_E501:
    local11 = (local11 + 1);    // $E501
    if ((*(byte*)(local11) != 0x00FF)) goto L_E4EB;    // $E508
    local10 = 0x00FF;    // $E50B
    *(byte*)(0x00FF) = -1;    // $E50E
    return -1;    // $E50F
}

// (body @ $E515)

word sub_E510(word arg1, word arg2, word arg3, word arg4) {
    local9 = 0x6F89;    // $E518
    local10 = 0;    // $E51A
    goto L_E545;    // $E51C
L_E51F:
    local11 = ?;    // $E51F
    if (sub_D999(/*stack underflow*/ regA)) goto L_E543;    // $E524
    local11 = ?;    // $E527
    // TODO: bitxor
    if (sub_D9B7(/*stack underflow*/ regA)) goto L_E543;    // $E52E
    if ((selected_province_idx != local11)) {    // $E536
    local9 = (local9 + 1);    // $E53B
    *(byte*)(((local9 + 1) - 1)) = local11;    // $E53F
    local10 = (local10 + 1);    // $E542
    }
L_E543:
L_E545:
    local11 = (local11 + 1);    // $E545
    if (((unsigned)local11 >= (unsigned)scenario_fief_count)) goto L_E51F;    // $E54B
    local9 = scenario_fief_count;    // $E54E
    *(byte*)(scenario_fief_count) = -1;    // $E551
    return local10;    // $E553
}

// (body @ $E559)

word sub_E554(word arg1, word arg2, word arg3, word arg4) {
    if (!(((unsigned)mem_6F5D <= (unsigned)8))) goto L_E594;    // $E55E
    local11 = mem_7FCD;    // $E564
    local10 = mem_7FCF;    // $E568
    // TODO: op_8D_sbyte +34
    // TODO: loadA_frameaddr $FFDA
    // TODO: loadA_frameaddr $FFDA
    // TODO: op_85_byte $D8
L_E584:
    // TODO: op_81_byte $D8
    if ((*(byte*)(sub_CBBD(/*stack underflow*/ regA, mem_7FCF, ((mem_6F5D * 34) + 0x9E3C), 4)) != 0x00FF)) goto L_E595;    // $E58B
L_E58E:
    local10 = 0x00FF;    // $E58E
    local11 = 0x00FF;    // $E58F
L_E594:
    return ui_helper_cc7b(/*stack underflow*/ regA, /*stack underflow*/ regA);    // $E594
L_E595:
    // TODO: op_81_byte $D8
    // TODO: op_85_byte $D8
    // TODO: op_81_byte $D8
    // TODO: op_85_byte $D8
    // TODO: op_81_byte $D8
    // TODO: op_85_byte $D8
    if (!((*(byte*)(((mem_7FCF + 1) - 1)) == arg1))) goto L_E584;    // $E5B2
    // TODO: PUSH_abs $7FCF
    // TODO: op_8D_sbyte +29
    // TODO: PUSH_abs $7FCF
    // TODO: PUSH_abs $7FCD
    arg1 = 0x8D5A;    // $E5EA
    goto L_E58E;    // $E5EF
}

// (body @ $E5F7)

word sub_E5F2(word arg1, word arg2, word arg3, word arg4) {
    if ((arg1 != mem_6F5D)) {    // $E5FC
    // TODO: op_8D_sbyte +19
    // TODO: op_8D_sbyte +31
    // TODO: op_8D_sbyte +30
    // TODO: op_8D_sbyte +19
    // TODO: op_8D_sbyte +29
    // TODO: push_imm_word $23C8
    local11 = mem_7FCD;    // $E63D
    local10 = mem_7FCF;    // $E641
    // TODO: op_8D_sbyte +34
    // TODO: loadA_frameaddr $FFDA
    // TODO: loadA_frameaddr $FFDA
    // TODO: op_85_byte $D8
    goto L_E67E;    // $E65B
L_E65E:
    // TODO: op_81_byte $D8
    // TODO: op_85_byte $D8
    // TODO: op_81_byte $D8
    // TODO: op_85_byte $D8
    // TODO: op_81_byte $D8
    // TODO: op_85_byte $D8
L_E67E:
    // TODO: op_81_byte $D8
    if ((*(byte*)(sub_DB6E(*(byte*)(((mem_7FCF + 1) - 1)))) != 0x00FF)) goto L_E65E;    // $E685
    local10 = 0x00FF;    // $E688
    local11 = 0x00FF;    // $E689
    }
L_E693:
    return marry_helper_cc35(0);    // $E693
}

// (body @ $E699)

word sub_E694(word arg1, word arg2, word arg3, word arg4) {
    if ((scenario_fief_count == 50)) {    // $E69F
    } else {
    }
L_E6B1:
    return map_helper_e5f2(*(byte*)((mem_7FDD + 0xFED8)));    // $E6B8
    }
}

// (body @ $E6BE)

word sub_E6B9(word arg1, word arg2, word arg3, word arg4) {
    local11 = *(word*)(((mem_6F5B << 1) + 0x6EB1));    // $E6C7
    // TODO: div_unsigned
    local9 = local11;    // $E6CB
    // TODO: mod_unsigned
    local10 = local11;    // $E6CF
    // TODO: div_unsigned
    local8 = local9;    // $E6D3
    // TODO: mod_unsigned
    local9 = local9;    // $E6D7
    // TODO: div_unsigned
    local7 = local8;    // $E6DB
    // TODO: mod_unsigned
    local8 = local8;    // $E6DF
    // TODO: push_imm_word $15B0
    // TODO: push_imm_word $1670
    // TODO: push_imm_word $16D0
    // TODO: push_imm_word $1730
    arg1 = 0xAD84;    // $E72B
    return sub_CBBD(12, (arg1 + 24), ((local7 * 12) + 0xAEAC), 9);    // $E76E
}

// (body @ $E774)

word sub_E76F(word arg1, word arg2, word arg3, word arg4) {
    // TODO: op_85_byte $DA
L_E777:
    // TODO: op_81_byte $DA
    // TODO: op_87_byte $DA
    // TODO: op_81_byte $DA
    // TODO: op_85_byte $DA
    // TODO: op_81_byte $DA
    if (((unsigned)(sub_CF8B(/*stack underflow*/ regA, *(word*)(((0 << 1) + 0xF7CC))) + 1) >= (unsigned)4)) goto L_E777;    // $E78F
    // TODO: cmp_ult
    if (mem_6F5B) goto L_E7A7;    // $E798
    // TODO: PUSH_abs $6F5B
    if (*(byte*)((sub_D7CD(/*stack underflow*/ regA) + 6))) goto L_E7EE;    // $E7A4
L_E7A7:
    // TODO: PUSH_abs $6F5B
    // TODO: op_85_byte $D8
    // TODO: loadA_frameaddr $FFD4
    // TODO: op_87_byte $D8
    // TODO: loadA_frameaddr $FFD4
    // TODO: op_85_byte $D8
    // TODO: op_81_byte $D8
    // TODO: push_imm_word $15B0
    // TODO: op_81_byte $D8
    // TODO: op_81_byte $D8
    // TODO: PUSH_abs $6F5B
    goto L_E7FA;    // $E7EB
L_E7EE:
    // TODO: loadA_frameaddr $FFDC
    // TODO: loadA_frameaddr $FFDC
L_E7FA:
    arg2 = 0xB144;    // $E801
    arg1 = 0xB144;    // $E802
    return mem_7FC7;    // $E80B
}

// (body @ $E811)

word sub_E80C(word arg1, word arg2, word arg3, word arg4) {
    // TODO: loadA_mem_byte $6DA1
    if ((? & 4)) {    // $E816
    }
L_E822:
    return sub_CBB1(14);    // $E822
}

