"""Bulk VM bytecode disassembler — recovered 2026-05-30 (drifted out of tools/, ch6).

Produces disasm/bank_NN_vm.asm: every bytecode subroutine in a bank, walked one
opcode at a time and rendered as a readable VM-assembly listing.

DECODE AUTHORITY (this is the whole point of the recovery):
  Instruction lengths come from the EXECUTION-VALIDATED emulator (nobunaga_vm.
  OPCODE_INFO) — NOT the deleted vm-opcodes.toml the old _vm.asm files used.
  Validation 2026-05-30 (probe via emulator vm_pc-delta + ROM handler reads)
  proved the OLD files had WRONG operand lengths for $84/$86/$88, $A0-$A3, $AA,
  $AF, $DE/$DF (they mis-aligned every instruction after those opcodes, and
  vm_decompile.py inherited the drift). OPCODE_INFO is correct for all of those.

  Two opcodes are variable-length inline JUMP TABLES (the "data interleaved with
  code" case) — decoded from their bank-15 handlers ($EC65 / $EC1D):
    $D5 SWITCH_contiguous   : offs(2)+limit(2)+default(2) + limit*2  -> 7 + 2*limit
    $D9 SWITCH_noncontiguous: count(1)+1 + count*4 + default(2)      -> 5 + 4*count
  The bytes after these opcodes are the table (data); we emit them as `.table`.
  $AD is 1 byte (count) per its handler $EB7D, overriding OPCODE_INFO's stale 4.

SUBROUTINE TILING: bytecode subs begin with a 5-byte stub `20 23 E8 <frame:2>`
(JSR $E823 = vm_entry, then a signed 16-bit frame offset); body starts at +5.
Scanning the bank for `20 23 E8` yields every stub; the stubs partition the
bank, so each sub spans [body_i, stub_{i+1}). A correct length table makes the
walk tile the bank EXACTLY — that is the built-in --check correctness test.

Usage:
  py -3 tools/vm-disasm.py <bank 0-15> [-o out.asm] [--check] [--stdout]
  py -3 tools/vm-disasm.py 15 --check        # validate tiling, don't write
  py -3 tools/vm-disasm.py 2 -o disasm/bank_02_vm.asm

NOTE (drift flag, see ROADMAP): the committed disasm/*_vm.asm were generated by
the old tool with the deleted spec → OLD mnemonics + the wrong lengths above.
vm_decompile.py keys on those OLD mnemonics, so regenerating the 4 existing banks
with this (canonical v2) tool must be paired with updating vm_decompile.py. This
recovery deliberately does NOT clobber them; pass -o explicitly to overwrite.
"""

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))
from na1dream.nobunaga_vm import NobunagaVM, OPCODE_INFO

ROM_NAME = "Nobunaga's Ambition (USA).nes"
VM_ENTRY_STUB = bytes([0x20, 0x23, 0xE8])  # JSR $E823
RETURN_OP = 0xCF

# Opcodes whose operand is a 16-bit code address (for {bytecode}/{native} + label).
WORD_TARGET_OPS = {0xAC: "CALL_abs"}          # word target, no adj byte
CALL_ADJ_OP = 0xE9                            # word target + 1 adj byte
# sbyte-operand opcodes (render operand signed): relative jumps.
SBYTE_OPS = {0xE3, 0xE4, 0xE5, 0xE6, 0xE7, 0xE8}
# 1-byte immediate opcodes rendered as SIGNED decimal (e.g. "+32", "-2") — matches
# the convention the decompiler's value regexes expect. $89/$8F load/add signed
# imm; $8B/$8D/$AE are byte/stack-adjust immediates.
IMM_SIGNED_OPS = {0x89, 0x8B, 0x8D, 0x8F, 0xAE}
# Control-flow classification (from OPCODE_INFO, handler-confirmed).
ABS_BRANCH_OPS = {0xD6, 0xD7, 0xD8}           # word-target jump/branch (collect '>')
# Unconditional terminators: after these, linear fall-through is unreachable. A
# sub ends at one of these once no forward branch/switch target still points past
# it. (Conditional branches $D7/$D8/$E4/$E5/$E7/$E8 fall through, so they are NOT
# here; their forward targets are tracked in walk_sub to extend reachability.)
UNCOND_TERMINATORS = {0xCF, 0xD6, 0xE3, 0xE6, 0xD5, 0xD9}  # RET / JMP / Jback / Jahead / switch×2


def cpu_to_file(bank, addr):
    if bank == 15:
        return 0x10 + 15 * 0x4000 + (addr - 0xC000)
    return 0x10 + bank * 0x4000 + (addr - 0x8000)


def bank_range(bank):
    """(cpu_base, size) for a bank's address window."""
    return (0xC000, 0x4000) if bank == 15 else (0x8000, 0x4000)


def instr_len(mem, pc):
    """True encoded length (opcode + operands) of the VM instruction at `pc`.

    Authority: OPCODE_INFO, with the three handler-verified overrides. Returns a
    length that makes the disassembly tile exactly (see module docstring).
    """
    op = mem.read(pc)
    if op < 0x80:
        return 1                                   # operand in low nibble
    if op == 0xD5:                                 # SWITCH_contiguous
        limit = mem.read(pc + 3) | (mem.read(pc + 4) << 8)
        return 7 + 2 * limit
    if op == 0xD9:                                 # SWITCH_noncontiguous
        count = mem.read(pc + 1) | (mem.read(pc + 2) << 8)
        return 5 + 4 * count
    if op == 0xAD:                                 # COPY: 1 count byte (handler $EB7D)
        return 2
    if op == 0xB7:                                 # LONG/ext_op: 1 index byte at pc+1,
        idx = mem.read(pc + 1)                     # plus a 4-byte inline immediate for
        # ext_op $18/$19 = load_a32/b32_from_ptr3, which copy (ptr3),Y=0..3 and advance
        # ptr3 by 4 (handlers $F4F4/$F500). All other ext_ops take no inline operand.
        # Without this, the 4 immediate bytes get mis-decoded as opcodes (e.g. a 32-bit
        # 0xFFFFFFFF reads as four $FF traps), corrupting the rest of the sub.
        return 6 if idx in (0x18, 0x19) else 2
    info = OPCODE_INFO.get(op)
    n = info[1] if info else 0
    if n < 0:
        n = 0                                      # unknown var-length → treat as bare
    return 1 + n


def find_stubs(mem, base, size):
    """Return sorted list of stub addresses (JSR $E823 occurrences) in the bank."""
    stubs = []
    for off in range(size - 2):
        a = base + off
        if (mem.read(a) == VM_ENTRY_STUB[0] and mem.read(a + 1) == VM_ENTRY_STUB[1]
                and mem.read(a + 2) == VM_ENTRY_STUB[2]):
            stubs.append(a)
    return stubs


def frame_off(mem, stub):
    """Signed 16-bit frame offset stored at stub+3."""
    v = mem.read(stub + 3) | (mem.read(stub + 4) << 8)
    return v - 0x10000 if v >= 0x8000 else v


def is_bytecode_target(mem, addr):
    """Peek a call target's first 3 bytes: JSR $E823 → bytecode sub, else native."""
    return (mem.read(addr) == VM_ENTRY_STUB[0] and mem.read(addr + 1) == VM_ENTRY_STUB[1]
            and mem.read(addr + 2) == VM_ENTRY_STUB[2])


def walk_sub(mem, body, end, labels):
    """Walk one sub starting at `body`, bounded above by `end` (next stub / bank
    end). Returns (instrs, final_pc, branch_targets).

    Termination = linear sweep with terminators (recursive-descent reachability):
    a sub ends at an unconditional terminator (RETURN / unconditional JUMP /
    switch) once `pc` has passed every forward conditional-branch target. This
    stops the last sub of a bank at its real end instead of chewing through the
    trailing data tables (which would make a switch read a garbage count and run
    away). Interior subs still tile exactly to the next stub.
    """
    instrs, targets, pc = [], set(), body
    max_target = body                                  # furthest forward branch target
    while pc < end:
        op = mem.read(pc)
        ln = instr_len(mem, pc)
        raw = [mem.read(pc + i) for i in range(ln)]
        info = OPCODE_INFO.get(op, ("UNK", 0))
        mnem = info[0]
        operand_str, comment = "", ""

        if op < 0x80:
            comment = f"inline operand = {op & 0x0F}"
        elif op == 0xD5:                            # contiguous: default + limit targets
            offs = raw[1] | (raw[2] << 8)
            limit = raw[3] | (raw[4] << 8)
            operand_str = f"limit={limit}"
            default = raw[5] | (raw[6] << 8)
            case_tgts = [raw[7 + 2 * k] | (raw[8 + 2 * k] << 8) for k in range(limit)]
            # Parseable switch table for the decompiler (cases = offs..offs+limit-1).
            sw = " ".join(f"{offs + k}=>${case_tgts[k]:04X}" for k in range(limit))
            comment = (f".table {limit} word targets (contiguous); "
                       f"SWITCH {sw} default=>${default:04X}")
            tgts = [default] + case_tgts
            for t in tgts:
                if body <= t < end:
                    targets.add(t)
                    if t > pc:
                        max_target = max(max_target, t)
        elif op == 0xD9:                            # noncontig: per-entry target + default
            count = raw[1] | (raw[2] << 8)
            operand_str = f"count={count}"
            keys = [raw[3 + 4 * k] | (raw[3 + 4 * k + 1] << 8) for k in range(count)]
            case_tgts = [raw[3 + 4 * k + 2] | (raw[3 + 4 * k + 3] << 8) for k in range(count)]
            default = raw[3 + 4 * count] | (raw[3 + 4 * count + 1] << 8)
            sw = " ".join(f"{keys[k]}=>${case_tgts[k]:04X}" for k in range(count))
            comment = (f".table {count} (key,target) + default (noncontiguous); "
                       f"SWITCH {sw} default=>${default:04X}")
            tgts = case_tgts + [default]
            for t in tgts:
                if body <= t < end:
                    targets.add(t)
                    if t > pc:
                        max_target = max(max_target, t)
        elif op == CALL_ADJ_OP:                     # $E9 word + adj byte
            tgt = raw[1] | (raw[2] << 8)
            adj = raw[3]
            kind = "bytecode" if is_bytecode_target(mem, tgt) else "native"
            lbl = labels.get(tgt)
            tstr = f"${tgt:04X}" + (f" ({lbl})" if lbl else "")
            operand_str = f"{tstr} {{{kind}}}, ${adj:02X}"
        elif op in WORD_TARGET_OPS:                 # $AC call, word target
            tgt = raw[1] | (raw[2] << 8)
            kind = "bytecode" if is_bytecode_target(mem, tgt) else "native"
            lbl = labels.get(tgt)
            operand_str = f"${tgt:04X}" + (f" ({lbl})" if lbl else "") + f" {{{kind}}}"
        elif op in ABS_BRANCH_OPS and ln == 3:      # absolute jump/branch (word)
            tgt = raw[1] | (raw[2] << 8)
            lbl = labels.get(tgt)
            operand_str = f"${tgt:04X}" + (f" ({lbl})" if lbl else "")
            if body <= tgt < end:
                targets.add(tgt)
                if tgt > pc:
                    max_target = max(max_target, tgt)
        elif op in SBYTE_OPS and ln == 2:           # relative jump (signed byte)
            b = raw[1]
            sb = b - 256 if b > 127 else b
            tgt = (pc + ln + sb) & 0xFFFF
            operand_str = f"{sb:+d}  (-> ${tgt:04X})"
            if body <= tgt < end:
                targets.add(tgt)
                if tgt > pc:
                    max_target = max(max_target, tgt)
        elif op in IMM_SIGNED_OPS and ln == 2:      # signed-decimal immediate
            b = raw[1]
            operand_str = f"{(b - 256 if b > 127 else b):+d}"
        elif ln == 2:                               # generic 1-byte operand
            operand_str = f"${raw[1]:02X}"
        elif ln == 3:                               # generic word operand
            w = raw[1] | (raw[2] << 8)
            lbl = labels.get(w)
            operand_str = f"${w:04X}" + (f" ({lbl})" if lbl else "")
        elif ln > 3:                                # multi-byte (e.g. $AD edge)
            operand_str = " ".join(f"${b:02X}" for b in raw[1:])

        instrs.append({"addr": pc, "bytes": raw, "op": op, "mnem": mnem,
                       "operand": operand_str, "comment": comment})
        pc += ln
        if op in UNCOND_TERMINATORS and pc > max_target:
            break                                   # sub ends; rest is data / next sub
    return instrs, pc, targets


def emit_sub(out, stub, end, mem, labels):
    """Append one subroutine's listing (header + walked instructions) to `out`.
    Returns True if the walk MIS-ALIGNED (overran its bound, or stalled without an
    unconditional terminator) — the built-in wrong-length detector."""
    body = stub + 5
    instrs, final_pc, targets = walk_sub(mem, body, end, labels)
    fo = frame_off(mem, stub)
    out.append("; " + "=" * 60)
    out.append(f"; sub ${stub:04X}   (frame_off={fo:+d}, body @ ${body:04X})")
    out.append("; " + "=" * 60)
    for ins in instrs:
        mark = ">" if ins["addr"] in targets else " "
        byts = " ".join(f"{b:02X}" for b in ins["bytes"])
        # keep raw-byte column short so it stays readable; truncate huge tables
        if len(ins["bytes"]) > 12:
            byts = " ".join(f"{b:02X}" for b in ins["bytes"][:12]) + " ..."
        line = (f" {mark}${ins['addr']:04X}  {byts:<26} {ins['mnem']:<22} "
                f"{ins['operand']:<26}")
        if ins["comment"]:
            line = line.rstrip() + f"   ; {ins['comment']}"
        out.append(line.rstrip())
    last_op = instrs[-1]["op"] if instrs else None
    out.append("")
    return final_pc > end or (final_pc < end and last_op not in UNCOND_TERMINATORS)


def sub_at(stubs, base, size, addr):
    """The stub whose span [body, next_stub) contains `addr` (accepts the stub addr, the
    body addr, or any interior instruction address). Returns (stub, end) or (None, None)."""
    bounds = stubs + [base + size]
    for i, stub in enumerate(stubs):
        if stub <= addr < bounds[i + 1]:
            return stub, bounds[i + 1]
    return None, None


def render(bank, stubs, mem, labels, n_labels):
    base, size = bank_range(bank)
    out = []
    out.append("VM bytecode disassembly")
    out.append(f"  ROM:          {ROM_NAME}")
    out.append(f"  mode:         bulk dump of bank {bank}")
    out.append(f"  opcode spec:  vm-opcodes-v2.toml via nobunaga_vm.OPCODE_INFO "
               f"(execution-validated lengths)")
    out.append(f"  labels:       {n_labels} CPU addresses named")
    out.append("")
    out.append(f"  bank {bank}: found {len(stubs)} bytecode-subroutine stubs")
    out.append("")

    bounds = stubs + [base + size]
    misaligned = 0
    for i, stub in enumerate(stubs):
        misaligned += emit_sub(out, stub, bounds[i + 1], mem, labels)
    return "\n".join(out) + "\n", misaligned


def check_tiling(bank, stubs, mem):
    """Artifact-independent correctness test. A sub is well-formed if either it
    tiles exactly to the next stub (interior subs), or it ends earlier on an
    unconditional terminator (last sub / sub followed by data padding). A sub is
    BAD only if it overruns its bound or stalls without a terminator — both of
    which mean a wrong instruction length mis-aligned the walk.

    Returns (tiled, clean_early, bad_list)."""
    base, size = bank_range(bank)
    bounds = stubs + [base + size]
    tiled = clean_early = 0
    bad = []
    for i, stub in enumerate(stubs):
        body, end = stub + 5, bounds[i + 1]
        instrs, final_pc, _ = walk_sub(mem, body, end, {})
        last_op = instrs[-1]["op"] if instrs else None
        if final_pc == end:
            tiled += 1
        elif final_pc < end and last_op in UNCOND_TERMINATORS:
            clean_early += 1
        else:
            bad.append((stub, final_pc, end, last_op))
    return tiled, clean_early, bad


def main():
    ap = argparse.ArgumentParser(description="Bulk VM bytecode disassembler")
    ap.add_argument("bank", type=lambda x: int(x, 0), help="bank number 0-15")
    ap.add_argument("-o", "--out", help="output .asm path (omit = don't write)")
    ap.add_argument("--stdout", action="store_true", help="print listing to stdout")
    ap.add_argument("--check", action="store_true",
                    help="run the exact-tiling correctness test and report")
    ap.add_argument("--sub", type=lambda x: int(x, 16),
                    help="dump ONLY the sub containing this hex address (fetch-at-will, "
                         "from the ROM via the canonical decoder — never the stale *_vm.asm)")
    args = ap.parse_args()

    vm = NobunagaVM()
    vm.switch_bank(args.bank)
    mem, labels = vm.mem, {a: n for a, (n, _c) in vm.labels.items()}
    base, size = bank_range(args.bank)
    stubs = find_stubs(mem, base, size)

    if args.sub is not None:
        stub, end = sub_at(stubs, base, size, args.sub)
        if stub is None:
            sys.exit(f"no bytecode sub in bank {args.bank} contains ${args.sub:04X}")
        out = []
        bad = emit_sub(out, stub, end, mem, labels)
        sys.stdout.write("\n".join(out) + "\n")
        if bad:
            sys.stderr.write(f"WARNING: sub ${stub:04X} did not tile exactly\n")
        return

    if args.check:
        tiled, clean_early, bad = check_tiling(args.bank, stubs, mem)
        print(f"bank {args.bank}: {len(stubs)} stubs | {tiled} tile-to-next-stub, "
              f"{clean_early} end-early-on-terminator, {len(bad)} BAD")
        for stub, fp, end, lo in bad[:20]:
            lt = f"${lo:02X}" if lo is not None else "none"
            print(f"  sub ${stub:04X}: ended ${fp:04X} (bound ${end:04X}, "
                  f"off {fp - end:+d}, last_op {lt})")
        return

    listing, misaligned = render(args.bank, stubs, mem, labels, len(vm.labels))
    if misaligned:
        sys.stderr.write(f"WARNING: {misaligned}/{len(stubs)} subs did not tile "
                         f"exactly (run --check for detail)\n")
    if args.stdout:
        sys.stdout.write(listing)
    if args.out:
        Path(args.out).write_text(listing, encoding="utf-8")
        sys.stderr.write(f"wrote {args.out} ({len(stubs)} subs)\n")
    if not args.out and not args.stdout:
        sys.stderr.write(f"bank {args.bank}: {len(stubs)} subs decoded. "
                         f"Pass -o <path> to write or --stdout to view.\n")


if __name__ == "__main__":
    main()
